// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: course/module.proto

package com.zhijiejiaoyu.glory_api.course;

public interface CreateCourseModuleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:glory_api.CreateCourseModuleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.base.PaginationResponse base_resp = 1;</code>
   * @return Whether the baseResp field is set.
   */
  boolean hasBaseResp();
  /**
   * <code>.base.PaginationResponse base_resp = 1;</code>
   * @return The baseResp.
   */
  com.zhijiejiaoyu.base.PaginationResponse getBaseResp();
  /**
   * <code>.base.PaginationResponse base_resp = 1;</code>
   */
  com.zhijiejiaoyu.base.PaginationResponseOrBuilder getBaseRespOrBuilder();

  /**
   * <code>int64 module_id = 2;</code>
   * @return The moduleId.
   */
  long getModuleId();
}
