// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/user.proto

package com.zhijiejiaoyu.glory_api.user;

/**
 * Protobuf type {@code glory_api.GetUserPagePermissionResponse}
 */
public final class GetUserPagePermissionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:glory_api.GetUserPagePermissionResponse)
    GetUserPagePermissionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetUserPagePermissionResponse.newBuilder() to construct.
  private GetUserPagePermissionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetUserPagePermissionResponse() {
    pagePermission = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetUserPagePermissionResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetUserPagePermissionResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0 = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.zhijiejiaoyu.base.BaseResponse.Builder subBuilder = null;
            if (baseResp != null) {
              subBuilder = baseResp.toBuilder();
            }
            baseResp = input.readMessage(com.zhijiejiaoyu.base.BaseResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(baseResp);
              baseResp = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              pagePermission = new java.util.ArrayList<com.zhijiejiaoyu.glory_api.user.PagePermission>();
              mutable_bitField0_ |= 0x00000001;
            }
            pagePermission.add(
                input.readMessage(com.zhijiejiaoyu.glory_api.user.PagePermission.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        pagePermission = java.util.Collections.unmodifiableList(pagePermission);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zhijiejiaoyu.glory_api.user.UserOuterClass.internal_static_glory_api_GetUserPagePermissionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zhijiejiaoyu.glory_api.user.UserOuterClass.internal_static_glory_api_GetUserPagePermissionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse.class, com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse.Builder.class);
  }

  public static final int BASE_RESP_FIELD_NUMBER = 1;
  private com.zhijiejiaoyu.base.BaseResponse baseResp;
  /**
   * <code>.base.BaseResponse base_resp = 1;</code>
   * @return Whether the baseResp field is set.
   */
  @java.lang.Override
  public boolean hasBaseResp() {
    return baseResp != null;
  }
  /**
   * <code>.base.BaseResponse base_resp = 1;</code>
   * @return The baseResp.
   */
  @java.lang.Override
  public com.zhijiejiaoyu.base.BaseResponse getBaseResp() {
    return baseResp == null ? com.zhijiejiaoyu.base.BaseResponse.getDefaultInstance() : baseResp;
  }
  /**
   * <code>.base.BaseResponse base_resp = 1;</code>
   */
  @java.lang.Override
  public com.zhijiejiaoyu.base.BaseResponseOrBuilder getBaseRespOrBuilder() {
    return getBaseResp();
  }

  public static final int PAGE_PERMISSION_FIELD_NUMBER = 2;
  private java.util.List<com.zhijiejiaoyu.glory_api.user.PagePermission> pagePermission;
  /**
   * <pre>
   * page permission of the user
   * </pre>
   *
   * <code>repeated .glory_api.PagePermission page_permission = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.zhijiejiaoyu.glory_api.user.PagePermission> getPagePermissionList() {
    return pagePermission;
  }
  /**
   * <pre>
   * page permission of the user
   * </pre>
   *
   * <code>repeated .glory_api.PagePermission page_permission = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.zhijiejiaoyu.glory_api.user.PagePermissionOrBuilder> 
      getPagePermissionOrBuilderList() {
    return pagePermission;
  }
  /**
   * <pre>
   * page permission of the user
   * </pre>
   *
   * <code>repeated .glory_api.PagePermission page_permission = 2;</code>
   */
  @java.lang.Override
  public int getPagePermissionCount() {
    return pagePermission.size();
  }
  /**
   * <pre>
   * page permission of the user
   * </pre>
   *
   * <code>repeated .glory_api.PagePermission page_permission = 2;</code>
   */
  @java.lang.Override
  public com.zhijiejiaoyu.glory_api.user.PagePermission getPagePermission(int index) {
    return pagePermission.get(index);
  }
  /**
   * <pre>
   * page permission of the user
   * </pre>
   *
   * <code>repeated .glory_api.PagePermission page_permission = 2;</code>
   */
  @java.lang.Override
  public com.zhijiejiaoyu.glory_api.user.PagePermissionOrBuilder getPagePermissionOrBuilder(
      int index) {
    return pagePermission.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (baseResp != null) {
      output.writeMessage(1, getBaseResp());
    }
    for (int i = 0; i < pagePermission.size(); i++) {
      output.writeMessage(2, pagePermission.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (baseResp != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBaseResp());
    }
    for (int i = 0; i < pagePermission.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, pagePermission.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse)) {
      return super.equals(obj);
    }
    com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse other = (com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse) obj;

    if (hasBaseResp() != other.hasBaseResp()) return false;
    if (hasBaseResp()) {
      if (!getBaseResp()
          .equals(other.getBaseResp())) return false;
    }
    if (!getPagePermissionList()
        .equals(other.getPagePermissionList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBaseResp()) {
      hash = (37 * hash) + BASE_RESP_FIELD_NUMBER;
      hash = (53 * hash) + getBaseResp().hashCode();
    }
    if (getPagePermissionCount() > 0) {
      hash = (37 * hash) + PAGE_PERMISSION_FIELD_NUMBER;
      hash = (53 * hash) + getPagePermissionList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code glory_api.GetUserPagePermissionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:glory_api.GetUserPagePermissionResponse)
      com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhijiejiaoyu.glory_api.user.UserOuterClass.internal_static_glory_api_GetUserPagePermissionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhijiejiaoyu.glory_api.user.UserOuterClass.internal_static_glory_api_GetUserPagePermissionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse.class, com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse.Builder.class);
    }

    // Construct using com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPagePermissionFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (baseRespBuilder == null) {
        baseResp = null;
      } else {
        baseResp = null;
        baseRespBuilder = null;
      }
      if (pagePermissionBuilder == null) {
        pagePermission = java.util.Collections.emptyList();
        bitField0 = (bitField0_ & ~0x00000001);
      } else {
        pagePermissionBuilder.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zhijiejiaoyu.glory_api.user.UserOuterClass.internal_static_glory_api_GetUserPagePermissionResponse_descriptor;
    }

    @java.lang.Override
    public com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse getDefaultInstanceForType() {
      return com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse build() {
      com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse buildPartial() {
      com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse result = new com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse(this);
      int from_bitField0 = bitField0;
      if (baseRespBuilder == null) {
        result.baseResp = baseResp;
      } else {
        result.baseResp = baseRespBuilder.build();
      }
      if (pagePermissionBuilder == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          pagePermission = java.util.Collections.unmodifiableList(pagePermission);
          bitField0 = (bitField0_ & ~0x00000001);
        }
        result.pagePermission = pagePermission;
      } else {
        result.pagePermission = pagePermissionBuilder.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse) {
        return mergeFrom((com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse other) {
      if (other == com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse.getDefaultInstance()) return this;
      if (other.hasBaseResp()) {
        mergeBaseResp(other.getBaseResp());
      }
      if (pagePermissionBuilder == null) {
        if (!other.pagePermission.isEmpty()) {
          if (pagePermission.isEmpty()) {
            pagePermission = other.pagePermission;
            bitField0 = (bitField0_ & ~0x00000001);
          } else {
            ensurePagePermissionIsMutable();
            pagePermission.addAll(other.pagePermission);
          }
          onChanged();
        }
      } else {
        if (!other.pagePermission.isEmpty()) {
          if (pagePermissionBuilder.isEmpty()) {
            pagePermissionBuilder.dispose();
            pagePermissionBuilder = null;
            pagePermission = other.pagePermission;
            bitField0 = (bitField0_ & ~0x00000001);
            pagePermissionBuilder = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPagePermissionFieldBuilder() : null;
          } else {
            pagePermissionBuilder.addAllMessages(other.pagePermission);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0;

    private com.zhijiejiaoyu.base.BaseResponse baseResp;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.zhijiejiaoyu.base.BaseResponse, com.zhijiejiaoyu.base.BaseResponse.Builder, com.zhijiejiaoyu.base.BaseResponseOrBuilder> baseRespBuilder;
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     * @return Whether the baseResp field is set.
     */
    public boolean hasBaseResp() {
      return baseRespBuilder != null || baseResp != null;
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     * @return The baseResp.
     */
    public com.zhijiejiaoyu.base.BaseResponse getBaseResp() {
      if (baseRespBuilder == null) {
        return baseResp == null ? com.zhijiejiaoyu.base.BaseResponse.getDefaultInstance() : baseResp;
      } else {
        return baseRespBuilder.getMessage();
      }
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    public Builder setBaseResp(com.zhijiejiaoyu.base.BaseResponse value) {
      if (baseRespBuilder == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        baseResp = value;
        onChanged();
      } else {
        baseRespBuilder.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    public Builder setBaseResp(
        com.zhijiejiaoyu.base.BaseResponse.Builder builderForValue) {
      if (baseRespBuilder == null) {
        baseResp = builderForValue.build();
        onChanged();
      } else {
        baseRespBuilder.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    public Builder mergeBaseResp(com.zhijiejiaoyu.base.BaseResponse value) {
      if (baseRespBuilder == null) {
        if (baseResp != null) {
          baseResp =
            com.zhijiejiaoyu.base.BaseResponse.newBuilder(baseResp).mergeFrom(value).buildPartial();
        } else {
          baseResp = value;
        }
        onChanged();
      } else {
        baseRespBuilder.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    public Builder clearBaseResp() {
      if (baseRespBuilder == null) {
        baseResp = null;
        onChanged();
      } else {
        baseResp = null;
        baseRespBuilder = null;
      }

      return this;
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    public com.zhijiejiaoyu.base.BaseResponse.Builder getBaseRespBuilder() {
      
      onChanged();
      return getBaseRespFieldBuilder().getBuilder();
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    public com.zhijiejiaoyu.base.BaseResponseOrBuilder getBaseRespOrBuilder() {
      if (baseRespBuilder != null) {
        return baseRespBuilder.getMessageOrBuilder();
      } else {
        return baseResp == null ?
            com.zhijiejiaoyu.base.BaseResponse.getDefaultInstance() : baseResp;
      }
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.zhijiejiaoyu.base.BaseResponse, com.zhijiejiaoyu.base.BaseResponse.Builder, com.zhijiejiaoyu.base.BaseResponseOrBuilder> 
        getBaseRespFieldBuilder() {
      if (baseRespBuilder == null) {
        baseRespBuilder = new com.google.protobuf.SingleFieldBuilderV3<
            com.zhijiejiaoyu.base.BaseResponse, com.zhijiejiaoyu.base.BaseResponse.Builder, com.zhijiejiaoyu.base.BaseResponseOrBuilder>(
                getBaseResp(),
                getParentForChildren(),
                isClean());
        baseResp = null;
      }
      return baseRespBuilder;
    }

    private java.util.List<com.zhijiejiaoyu.glory_api.user.PagePermission> pagePermission =
      java.util.Collections.emptyList();
    private void ensurePagePermissionIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        pagePermission = new java.util.ArrayList<com.zhijiejiaoyu.glory_api.user.PagePermission>(pagePermission);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.zhijiejiaoyu.glory_api.user.PagePermission, com.zhijiejiaoyu.glory_api.user.PagePermission.Builder, com.zhijiejiaoyu.glory_api.user.PagePermissionOrBuilder> pagePermissionBuilder;

    /**
     * <pre>
     * page permission of the user
     * </pre>
     *
     * <code>repeated .glory_api.PagePermission page_permission = 2;</code>
     */
    public java.util.List<com.zhijiejiaoyu.glory_api.user.PagePermission> getPagePermissionList() {
      if (pagePermissionBuilder == null) {
        return java.util.Collections.unmodifiableList(pagePermission);
      } else {
        return pagePermissionBuilder.getMessageList();
      }
    }
    /**
     * <pre>
     * page permission of the user
     * </pre>
     *
     * <code>repeated .glory_api.PagePermission page_permission = 2;</code>
     */
    public int getPagePermissionCount() {
      if (pagePermissionBuilder == null) {
        return pagePermission.size();
      } else {
        return pagePermissionBuilder.getCount();
      }
    }
    /**
     * <pre>
     * page permission of the user
     * </pre>
     *
     * <code>repeated .glory_api.PagePermission page_permission = 2;</code>
     */
    public com.zhijiejiaoyu.glory_api.user.PagePermission getPagePermission(int index) {
      if (pagePermissionBuilder == null) {
        return pagePermission.get(index);
      } else {
        return pagePermissionBuilder.getMessage(index);
      }
    }
    /**
     * <pre>
     * page permission of the user
     * </pre>
     *
     * <code>repeated .glory_api.PagePermission page_permission = 2;</code>
     */
    public Builder setPagePermission(
        int index, com.zhijiejiaoyu.glory_api.user.PagePermission value) {
      if (pagePermissionBuilder == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePagePermissionIsMutable();
        pagePermission.set(index, value);
        onChanged();
      } else {
        pagePermissionBuilder.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * page permission of the user
     * </pre>
     *
     * <code>repeated .glory_api.PagePermission page_permission = 2;</code>
     */
    public Builder setPagePermission(
        int index, com.zhijiejiaoyu.glory_api.user.PagePermission.Builder builderForValue) {
      if (pagePermissionBuilder == null) {
        ensurePagePermissionIsMutable();
        pagePermission.set(index, builderForValue.build());
        onChanged();
      } else {
        pagePermissionBuilder.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * page permission of the user
     * </pre>
     *
     * <code>repeated .glory_api.PagePermission page_permission = 2;</code>
     */
    public Builder addPagePermission(com.zhijiejiaoyu.glory_api.user.PagePermission value) {
      if (pagePermissionBuilder == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePagePermissionIsMutable();
        pagePermission.add(value);
        onChanged();
      } else {
        pagePermissionBuilder.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * page permission of the user
     * </pre>
     *
     * <code>repeated .glory_api.PagePermission page_permission = 2;</code>
     */
    public Builder addPagePermission(
        int index, com.zhijiejiaoyu.glory_api.user.PagePermission value) {
      if (pagePermissionBuilder == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePagePermissionIsMutable();
        pagePermission.add(index, value);
        onChanged();
      } else {
        pagePermissionBuilder.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * page permission of the user
     * </pre>
     *
     * <code>repeated .glory_api.PagePermission page_permission = 2;</code>
     */
    public Builder addPagePermission(
        com.zhijiejiaoyu.glory_api.user.PagePermission.Builder builderForValue) {
      if (pagePermissionBuilder == null) {
        ensurePagePermissionIsMutable();
        pagePermission.add(builderForValue.build());
        onChanged();
      } else {
        pagePermissionBuilder.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * page permission of the user
     * </pre>
     *
     * <code>repeated .glory_api.PagePermission page_permission = 2;</code>
     */
    public Builder addPagePermission(
        int index, com.zhijiejiaoyu.glory_api.user.PagePermission.Builder builderForValue) {
      if (pagePermissionBuilder == null) {
        ensurePagePermissionIsMutable();
        pagePermission.add(index, builderForValue.build());
        onChanged();
      } else {
        pagePermissionBuilder.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * page permission of the user
     * </pre>
     *
     * <code>repeated .glory_api.PagePermission page_permission = 2;</code>
     */
    public Builder addAllPagePermission(
        java.lang.Iterable<? extends com.zhijiejiaoyu.glory_api.user.PagePermission> values) {
      if (pagePermissionBuilder == null) {
        ensurePagePermissionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, pagePermission);
        onChanged();
      } else {
        pagePermissionBuilder.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * page permission of the user
     * </pre>
     *
     * <code>repeated .glory_api.PagePermission page_permission = 2;</code>
     */
    public Builder clearPagePermission() {
      if (pagePermissionBuilder == null) {
        pagePermission = java.util.Collections.emptyList();
        bitField0 = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        pagePermissionBuilder.clear();
      }
      return this;
    }
    /**
     * <pre>
     * page permission of the user
     * </pre>
     *
     * <code>repeated .glory_api.PagePermission page_permission = 2;</code>
     */
    public Builder removePagePermission(int index) {
      if (pagePermissionBuilder == null) {
        ensurePagePermissionIsMutable();
        pagePermission.remove(index);
        onChanged();
      } else {
        pagePermissionBuilder.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * page permission of the user
     * </pre>
     *
     * <code>repeated .glory_api.PagePermission page_permission = 2;</code>
     */
    public com.zhijiejiaoyu.glory_api.user.PagePermission.Builder getPagePermissionBuilder(
        int index) {
      return getPagePermissionFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * page permission of the user
     * </pre>
     *
     * <code>repeated .glory_api.PagePermission page_permission = 2;</code>
     */
    public com.zhijiejiaoyu.glory_api.user.PagePermissionOrBuilder getPagePermissionOrBuilder(
        int index) {
      if (pagePermissionBuilder == null) {
        return pagePermission.get(index);  } else {
        return pagePermissionBuilder.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * page permission of the user
     * </pre>
     *
     * <code>repeated .glory_api.PagePermission page_permission = 2;</code>
     */
    public java.util.List<? extends com.zhijiejiaoyu.glory_api.user.PagePermissionOrBuilder> 
         getPagePermissionOrBuilderList() {
      if (pagePermissionBuilder != null) {
        return pagePermissionBuilder.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(pagePermission);
      }
    }
    /**
     * <pre>
     * page permission of the user
     * </pre>
     *
     * <code>repeated .glory_api.PagePermission page_permission = 2;</code>
     */
    public com.zhijiejiaoyu.glory_api.user.PagePermission.Builder addPagePermissionBuilder() {
      return getPagePermissionFieldBuilder().addBuilder(
          com.zhijiejiaoyu.glory_api.user.PagePermission.getDefaultInstance());
    }
    /**
     * <pre>
     * page permission of the user
     * </pre>
     *
     * <code>repeated .glory_api.PagePermission page_permission = 2;</code>
     */
    public com.zhijiejiaoyu.glory_api.user.PagePermission.Builder addPagePermissionBuilder(
        int index) {
      return getPagePermissionFieldBuilder().addBuilder(
          index, com.zhijiejiaoyu.glory_api.user.PagePermission.getDefaultInstance());
    }
    /**
     * <pre>
     * page permission of the user
     * </pre>
     *
     * <code>repeated .glory_api.PagePermission page_permission = 2;</code>
     */
    public java.util.List<com.zhijiejiaoyu.glory_api.user.PagePermission.Builder> 
         getPagePermissionBuilderList() {
      return getPagePermissionFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.zhijiejiaoyu.glory_api.user.PagePermission, com.zhijiejiaoyu.glory_api.user.PagePermission.Builder, com.zhijiejiaoyu.glory_api.user.PagePermissionOrBuilder> 
        getPagePermissionFieldBuilder() {
      if (pagePermissionBuilder == null) {
        pagePermissionBuilder = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.zhijiejiaoyu.glory_api.user.PagePermission, com.zhijiejiaoyu.glory_api.user.PagePermission.Builder, com.zhijiejiaoyu.glory_api.user.PagePermissionOrBuilder>(
                pagePermission_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        pagePermission = null;
      }
      return pagePermissionBuilder;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:glory_api.GetUserPagePermissionResponse)
  }

  // @@protoc_insertion_point(class_scope:glory_api.GetUserPagePermissionResponse)
  private static final com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse();
  }

  public static com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetUserPagePermissionResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetUserPagePermissionResponse>() {
    @java.lang.Override
    public GetUserPagePermissionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetUserPagePermissionResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetUserPagePermissionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetUserPagePermissionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.zhijiejiaoyu.glory_api.user.GetUserPagePermissionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

