// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task/teacher_task.proto

package com.zhijiejiaoyu.glory_api.task;

public interface ClassTaskSubmitCountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:glory_api.ClassTaskSubmitCount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string type = 2;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>repeated float data = 3;</code>
   * @return A list containing the data.
   */
  java.util.List<java.lang.Float> getDataList();
  /**
   * <code>repeated float data = 3;</code>
   * @return The count of data.
   */
  int getDataCount();
  /**
   * <code>repeated float data = 3;</code>
   * @param index The index of the element to return.
   * @return The data at the given index.
   */
  float getData(int index);
}
