// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task/teacher_task.proto

package com.zhijiejiaoyu.glory_api.task;

/**
 * Protobuf type {@code glory_api.CountLaggingStudentListResponse}
 */
public final class CountLaggingStudentListResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:glory_api.CountLaggingStudentListResponse)
    CountLaggingStudentListResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CountLaggingStudentListResponse.newBuilder() to construct.
  private CountLaggingStudentListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CountLaggingStudentListResponse() {
    laggingList = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CountLaggingStudentListResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CountLaggingStudentListResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0 = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.zhijiejiaoyu.base.BaseResponse.Builder subBuilder = null;
            if (baseResp != null) {
              subBuilder = baseResp .toBuilder();
            }
            baseResp = input.readMessage(com.zhijiejiaoyu.base.BaseResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(baseResp );
              baseResp = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            if (!((mutable_bitField0 & 0x00000001) != 0)) {
              laggingList = new java.util.ArrayList<com.zhijiejiaoyu.glory_api.task.StudentPassCount>();
              mutable_bitField0_ |= 0x00000001;
            }
            laggingList .add(
                input.readMessage(com.zhijiejiaoyu.glory_api.task.StudentPassCount.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0 & 0x00000001) != 0)) {
        laggingList = java.util.Collections.unmodifiableList(laggingList );
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zhijiejiaoyu.glory_api.task.TeacherTaskOuterClass.internal_static_glory_api_CountLaggingStudentListResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zhijiejiaoyu.glory_api.task.TeacherTaskOuterClass.internal_static_glory_api_CountLaggingStudentListResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse.class, com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse.Builder.class);
  }

  public static final int BASE_RESP_FIELD_NUMBER = 1;
  private com.zhijiejiaoyu.base.BaseResponse baseResp ;
  /**
   * <code>.base.BaseResponse base_resp = 1;</code>
   * @return Whether the baseResp field is set.
   */
  @java.lang.Override
  public boolean hasBaseResp() {
    return baseResp != null;
  }
  /**
   * <code>.base.BaseResponse base_resp = 1;</code>
   * @return The baseResp.
   */
  @java.lang.Override
  public com.zhijiejiaoyu.base.BaseResponse getBaseResp() {
    return baseResp == null ? com.zhijiejiaoyu.base.BaseResponse.getDefaultInstance() : baseResp ;
  }
  /**
   * <code>.base.BaseResponse base_resp = 1;</code>
   */
  @java.lang.Override
  public com.zhijiejiaoyu.base.BaseResponseOrBuilder getBaseRespOrBuilder() {
    return getBaseResp();
  }

  public static final int LAGGING_LIST_FIELD_NUMBER = 3;
  private java.util.List<com.zhijiejiaoyu.glory_api.task.StudentPassCount> laggingList ;
  /**
   * <pre>
   * 学习积极分子排行榜
   * </pre>
   *
   * <code>repeated .glory_api.StudentPassCount lagging_list = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.zhijiejiaoyu.glory_api.task.StudentPassCount> getLaggingListList() {
    return laggingList ;
  }
  /**
   * <pre>
   * 学习积极分子排行榜
   * </pre>
   *
   * <code>repeated .glory_api.StudentPassCount lagging_list = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.zhijiejiaoyu.glory_api.task.StudentPassCountOrBuilder> 
      getLaggingListOrBuilderList() {
    return laggingList ;
  }
  /**
   * <pre>
   * 学习积极分子排行榜
   * </pre>
   *
   * <code>repeated .glory_api.StudentPassCount lagging_list = 3;</code>
   */
  @java.lang.Override
  public int getLaggingListCount() {
    return laggingList .size();
  }
  /**
   * <pre>
   * 学习积极分子排行榜
   * </pre>
   *
   * <code>repeated .glory_api.StudentPassCount lagging_list = 3;</code>
   */
  @java.lang.Override
  public com.zhijiejiaoyu.glory_api.task.StudentPassCount getLaggingList(int index) {
    return laggingList .get(index);
  }
  /**
   * <pre>
   * 学习积极分子排行榜
   * </pre>
   *
   * <code>repeated .glory_api.StudentPassCount lagging_list = 3;</code>
   */
  @java.lang.Override
  public com.zhijiejiaoyu.glory_api.task.StudentPassCountOrBuilder getLaggingListOrBuilder(
      int index) {
    return laggingList .get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (baseResp != null) {
      output.writeMessage(1, getBaseResp());
    }
    for (int i = 0; i < laggingList .size(); i++) {
      output.writeMessage(3, laggingList .get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (baseResp != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBaseResp());
    }
    for (int i = 0; i < laggingList .size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, laggingList .get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse)) {
      return super.equals(obj);
    }
    com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse other = (com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse) obj;

    if (hasBaseResp() != other.hasBaseResp()) return false;
    if (hasBaseResp()) {
      if (!getBaseResp()
          .equals(other.getBaseResp())) return false;
    }
    if (!getLaggingListList()
        .equals(other.getLaggingListList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBaseResp()) {
      hash = (37 * hash) + BASE_RESP_FIELD_NUMBER;
      hash = (53 * hash) + getBaseResp().hashCode();
    }
    if (getLaggingListCount() > 0) {
      hash = (37 * hash) + LAGGING_LIST_FIELD_NUMBER;
      hash = (53 * hash) + getLaggingListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code glory_api.CountLaggingStudentListResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:glory_api.CountLaggingStudentListResponse)
      com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhijiejiaoyu.glory_api.task.TeacherTaskOuterClass.internal_static_glory_api_CountLaggingStudentListResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhijiejiaoyu.glory_api.task.TeacherTaskOuterClass.internal_static_glory_api_CountLaggingStudentListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse.class, com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse.Builder.class);
    }

    // Construct using com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getLaggingListFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (baseRespBuilder == null) {
        baseResp = null;
      } else {
        baseResp = null;
        baseRespBuilder = null;
      }
      if (laggingListBuilder == null) {
        laggingList = java.util.Collections.emptyList();
        bitField0 = (bitField0 & ~0x00000001);
      } else {
        laggingListBuilder .clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zhijiejiaoyu.glory_api.task.TeacherTaskOuterClass.internal_static_glory_api_CountLaggingStudentListResponse_descriptor;
    }

    @java.lang.Override
    public com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse getDefaultInstanceForType() {
      return com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse build() {
      com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse buildPartial() {
      com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse result = new com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse(this);
      int from_bitField0 = bitField0 ;
      if (baseRespBuilder == null) {
        result.baseResp = baseResp ;
      } else {
        result.baseResp = baseRespBuilder .build();
      }
      if (laggingListBuilder == null) {
        if (((bitField0 & 0x00000001) != 0)) {
          laggingList = java.util.Collections.unmodifiableList(laggingList );
          bitField0 = (bitField0 & ~0x00000001);
        }
        result.laggingList = laggingList ;
      } else {
        result.laggingList = laggingListBuilder .build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse) {
        return mergeFrom((com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse other) {
      if (other == com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse.getDefaultInstance()) return this;
      if (other.hasBaseResp()) {
        mergeBaseResp(other.getBaseResp());
      }
      if (laggingListBuilder == null) {
        if (!other.laggingList .isEmpty()) {
          if (laggingList .isEmpty()) {
            laggingList = other.laggingList ;
            bitField0 = (bitField0 & ~0x00000001);
          } else {
            ensureLaggingListIsMutable();
            laggingList .addAll(other.laggingList );
          }
          onChanged();
        }
      } else {
        if (!other.laggingList .isEmpty()) {
          if (laggingListBuilder .isEmpty()) {
            laggingListBuilder .dispose();
            laggingListBuilder = null;
            laggingList = other.laggingList ;
            bitField0 = (bitField0 & ~0x00000001);
            laggingListBuilder = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getLaggingListFieldBuilder() : null;
          } else {
            laggingListBuilder .addAllMessages(other.laggingList );
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0 ;

    private com.zhijiejiaoyu.base.BaseResponse baseResp ;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.zhijiejiaoyu.base.BaseResponse, com.zhijiejiaoyu.base.BaseResponse.Builder, com.zhijiejiaoyu.base.BaseResponseOrBuilder> baseRespBuilder ;
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     * @return Whether the baseResp field is set.
     */
    public boolean hasBaseResp() {
      return baseRespBuilder != null || baseResp != null;
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     * @return The baseResp.
     */
    public com.zhijiejiaoyu.base.BaseResponse getBaseResp() {
      if (baseRespBuilder == null) {
        return baseResp == null ? com.zhijiejiaoyu.base.BaseResponse.getDefaultInstance() : baseResp ;
      } else {
        return baseRespBuilder .getMessage();
      }
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    public Builder setBaseResp(com.zhijiejiaoyu.base.BaseResponse value) {
      if (baseRespBuilder == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        baseResp = value;
        onChanged();
      } else {
        baseRespBuilder .setMessage(value);
      }

      return this;
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    public Builder setBaseResp(
        com.zhijiejiaoyu.base.BaseResponse.Builder builderForValue) {
      if (baseRespBuilder == null) {
        baseResp = builderForValue.build();
        onChanged();
      } else {
        baseRespBuilder .setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    public Builder mergeBaseResp(com.zhijiejiaoyu.base.BaseResponse value) {
      if (baseRespBuilder == null) {
        if (baseResp != null) {
          baseResp =
            com.zhijiejiaoyu.base.BaseResponse.newBuilder(baseResp ).mergeFrom(value).buildPartial();
        } else {
          baseResp = value;
        }
        onChanged();
      } else {
        baseRespBuilder .mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    public Builder clearBaseResp() {
      if (baseRespBuilder == null) {
        baseResp = null;
        onChanged();
      } else {
        baseResp = null;
        baseRespBuilder = null;
      }

      return this;
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    public com.zhijiejiaoyu.base.BaseResponse.Builder getBaseRespBuilder() {
      
      onChanged();
      return getBaseRespFieldBuilder().getBuilder();
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    public com.zhijiejiaoyu.base.BaseResponseOrBuilder getBaseRespOrBuilder() {
      if (baseRespBuilder != null) {
        return baseRespBuilder .getMessageOrBuilder();
      } else {
        return baseResp == null ?
            com.zhijiejiaoyu.base.BaseResponse.getDefaultInstance() : baseResp ;
      }
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.zhijiejiaoyu.base.BaseResponse, com.zhijiejiaoyu.base.BaseResponse.Builder, com.zhijiejiaoyu.base.BaseResponseOrBuilder> 
        getBaseRespFieldBuilder() {
      if (baseRespBuilder == null) {
        baseRespBuilder = new com.google.protobuf.SingleFieldBuilderV3<
            com.zhijiejiaoyu.base.BaseResponse, com.zhijiejiaoyu.base.BaseResponse.Builder, com.zhijiejiaoyu.base.BaseResponseOrBuilder>(
                getBaseResp(),
                getParentForChildren(),
                isClean());
        baseResp = null;
      }
      return baseRespBuilder ;
    }

    private java.util.List<com.zhijiejiaoyu.glory_api.task.StudentPassCount> laggingList =
      java.util.Collections.emptyList();
    private void ensureLaggingListIsMutable() {
      if (!((bitField0 & 0x00000001) != 0)) {
        laggingList = new java.util.ArrayList<com.zhijiejiaoyu.glory_api.task.StudentPassCount>(laggingList );
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.zhijiejiaoyu.glory_api.task.StudentPassCount, com.zhijiejiaoyu.glory_api.task.StudentPassCount.Builder, com.zhijiejiaoyu.glory_api.task.StudentPassCountOrBuilder> laggingListBuilder ;

    /**
     * <pre>
     * 学习积极分子排行榜
     * </pre>
     *
     * <code>repeated .glory_api.StudentPassCount lagging_list = 3;</code>
     */
    public java.util.List<com.zhijiejiaoyu.glory_api.task.StudentPassCount> getLaggingListList() {
      if (laggingListBuilder == null) {
        return java.util.Collections.unmodifiableList(laggingList );
      } else {
        return laggingListBuilder .getMessageList();
      }
    }
    /**
     * <pre>
     * 学习积极分子排行榜
     * </pre>
     *
     * <code>repeated .glory_api.StudentPassCount lagging_list = 3;</code>
     */
    public int getLaggingListCount() {
      if (laggingListBuilder == null) {
        return laggingList .size();
      } else {
        return laggingListBuilder .getCount();
      }
    }
    /**
     * <pre>
     * 学习积极分子排行榜
     * </pre>
     *
     * <code>repeated .glory_api.StudentPassCount lagging_list = 3;</code>
     */
    public com.zhijiejiaoyu.glory_api.task.StudentPassCount getLaggingList(int index) {
      if (laggingListBuilder == null) {
        return laggingList .get(index);
      } else {
        return laggingListBuilder .getMessage(index);
      }
    }
    /**
     * <pre>
     * 学习积极分子排行榜
     * </pre>
     *
     * <code>repeated .glory_api.StudentPassCount lagging_list = 3;</code>
     */
    public Builder setLaggingList(
        int index, com.zhijiejiaoyu.glory_api.task.StudentPassCount value) {
      if (laggingListBuilder == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLaggingListIsMutable();
        laggingList .set(index, value);
        onChanged();
      } else {
        laggingListBuilder .setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 学习积极分子排行榜
     * </pre>
     *
     * <code>repeated .glory_api.StudentPassCount lagging_list = 3;</code>
     */
    public Builder setLaggingList(
        int index, com.zhijiejiaoyu.glory_api.task.StudentPassCount.Builder builderForValue) {
      if (laggingListBuilder == null) {
        ensureLaggingListIsMutable();
        laggingList .set(index, builderForValue.build());
        onChanged();
      } else {
        laggingListBuilder .setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 学习积极分子排行榜
     * </pre>
     *
     * <code>repeated .glory_api.StudentPassCount lagging_list = 3;</code>
     */
    public Builder addLaggingList(com.zhijiejiaoyu.glory_api.task.StudentPassCount value) {
      if (laggingListBuilder == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLaggingListIsMutable();
        laggingList .add(value);
        onChanged();
      } else {
        laggingListBuilder .addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 学习积极分子排行榜
     * </pre>
     *
     * <code>repeated .glory_api.StudentPassCount lagging_list = 3;</code>
     */
    public Builder addLaggingList(
        int index, com.zhijiejiaoyu.glory_api.task.StudentPassCount value) {
      if (laggingListBuilder == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLaggingListIsMutable();
        laggingList .add(index, value);
        onChanged();
      } else {
        laggingListBuilder .addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 学习积极分子排行榜
     * </pre>
     *
     * <code>repeated .glory_api.StudentPassCount lagging_list = 3;</code>
     */
    public Builder addLaggingList(
        com.zhijiejiaoyu.glory_api.task.StudentPassCount.Builder builderForValue) {
      if (laggingListBuilder == null) {
        ensureLaggingListIsMutable();
        laggingList .add(builderForValue.build());
        onChanged();
      } else {
        laggingListBuilder .addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 学习积极分子排行榜
     * </pre>
     *
     * <code>repeated .glory_api.StudentPassCount lagging_list = 3;</code>
     */
    public Builder addLaggingList(
        int index, com.zhijiejiaoyu.glory_api.task.StudentPassCount.Builder builderForValue) {
      if (laggingListBuilder == null) {
        ensureLaggingListIsMutable();
        laggingList .add(index, builderForValue.build());
        onChanged();
      } else {
        laggingListBuilder .addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 学习积极分子排行榜
     * </pre>
     *
     * <code>repeated .glory_api.StudentPassCount lagging_list = 3;</code>
     */
    public Builder addAllLaggingList(
        java.lang.Iterable<? extends com.zhijiejiaoyu.glory_api.task.StudentPassCount> values) {
      if (laggingListBuilder == null) {
        ensureLaggingListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, laggingList );
        onChanged();
      } else {
        laggingListBuilder .addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 学习积极分子排行榜
     * </pre>
     *
     * <code>repeated .glory_api.StudentPassCount lagging_list = 3;</code>
     */
    public Builder clearLaggingList() {
      if (laggingListBuilder == null) {
        laggingList = java.util.Collections.emptyList();
        bitField0 = (bitField0 & ~0x00000001);
        onChanged();
      } else {
        laggingListBuilder .clear();
      }
      return this;
    }
    /**
     * <pre>
     * 学习积极分子排行榜
     * </pre>
     *
     * <code>repeated .glory_api.StudentPassCount lagging_list = 3;</code>
     */
    public Builder removeLaggingList(int index) {
      if (laggingListBuilder == null) {
        ensureLaggingListIsMutable();
        laggingList .remove(index);
        onChanged();
      } else {
        laggingListBuilder .remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 学习积极分子排行榜
     * </pre>
     *
     * <code>repeated .glory_api.StudentPassCount lagging_list = 3;</code>
     */
    public com.zhijiejiaoyu.glory_api.task.StudentPassCount.Builder getLaggingListBuilder(
        int index) {
      return getLaggingListFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 学习积极分子排行榜
     * </pre>
     *
     * <code>repeated .glory_api.StudentPassCount lagging_list = 3;</code>
     */
    public com.zhijiejiaoyu.glory_api.task.StudentPassCountOrBuilder getLaggingListOrBuilder(
        int index) {
      if (laggingListBuilder == null) {
        return laggingList .get(index);  } else {
        return laggingListBuilder .getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 学习积极分子排行榜
     * </pre>
     *
     * <code>repeated .glory_api.StudentPassCount lagging_list = 3;</code>
     */
    public java.util.List<? extends com.zhijiejiaoyu.glory_api.task.StudentPassCountOrBuilder> 
         getLaggingListOrBuilderList() {
      if (laggingListBuilder != null) {
        return laggingListBuilder .getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(laggingList );
      }
    }
    /**
     * <pre>
     * 学习积极分子排行榜
     * </pre>
     *
     * <code>repeated .glory_api.StudentPassCount lagging_list = 3;</code>
     */
    public com.zhijiejiaoyu.glory_api.task.StudentPassCount.Builder addLaggingListBuilder() {
      return getLaggingListFieldBuilder().addBuilder(
          com.zhijiejiaoyu.glory_api.task.StudentPassCount.getDefaultInstance());
    }
    /**
     * <pre>
     * 学习积极分子排行榜
     * </pre>
     *
     * <code>repeated .glory_api.StudentPassCount lagging_list = 3;</code>
     */
    public com.zhijiejiaoyu.glory_api.task.StudentPassCount.Builder addLaggingListBuilder(
        int index) {
      return getLaggingListFieldBuilder().addBuilder(
          index, com.zhijiejiaoyu.glory_api.task.StudentPassCount.getDefaultInstance());
    }
    /**
     * <pre>
     * 学习积极分子排行榜
     * </pre>
     *
     * <code>repeated .glory_api.StudentPassCount lagging_list = 3;</code>
     */
    public java.util.List<com.zhijiejiaoyu.glory_api.task.StudentPassCount.Builder> 
         getLaggingListBuilderList() {
      return getLaggingListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.zhijiejiaoyu.glory_api.task.StudentPassCount, com.zhijiejiaoyu.glory_api.task.StudentPassCount.Builder, com.zhijiejiaoyu.glory_api.task.StudentPassCountOrBuilder> 
        getLaggingListFieldBuilder() {
      if (laggingListBuilder == null) {
        laggingListBuilder = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.zhijiejiaoyu.glory_api.task.StudentPassCount, com.zhijiejiaoyu.glory_api.task.StudentPassCount.Builder, com.zhijiejiaoyu.glory_api.task.StudentPassCountOrBuilder>(
                laggingList ,
                ((bitField0 & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        laggingList = null;
      }
      return laggingListBuilder ;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:glory_api.CountLaggingStudentListResponse)
  }

  // @@protoc_insertion_point(class_scope:glory_api.CountLaggingStudentListResponse)
  private static final com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse();
  }

  public static com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CountLaggingStudentListResponse>
      PARSER = new com.google.protobuf.AbstractParser<CountLaggingStudentListResponse>() {
    @java.lang.Override
    public CountLaggingStudentListResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CountLaggingStudentListResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CountLaggingStudentListResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CountLaggingStudentListResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.zhijiejiaoyu.glory_api.task.CountLaggingStudentListResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

