// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shop/activity.proto

package com.zhijiejiaoyu.glory_api.shop;

/**
 * Protobuf type {@code glory_api.ActivityProduct}
 */
public final class ActivityProduct extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:glory_api.ActivityProduct)
    ActivityProductOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ActivityProduct.newBuilder() to construct.
  private ActivityProduct(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ActivityProduct() {
    preferentialValue = "";
    productName = "";
    sku = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ActivityProduct();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ActivityProduct(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0 = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            productId = input.readInt64();
            break;
          }
          case 16: {

            skuId = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            preferentialValue = s;
            break;
          }
          case 32: {

            stockTotal = input.readInt64();
            break;
          }
          case 40: {

            purchaseLimit = input.readInt64();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            productName = s;
            break;
          }
          case 58: {
            if (!((mutable_bitField0 & 0x00000001) != 0)) {
              sku = new java.util.ArrayList<com.zhijiejiaoyu.glory_api.shop.Sku>();
              mutable_bitField0_ |= 0x00000001;
            }
            sku .add(
                input.readMessage(com.zhijiejiaoyu.glory_api.shop.Sku.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0 & 0x00000001) != 0)) {
        sku = java.util.Collections.unmodifiableList(sku );
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zhijiejiaoyu.glory_api.shop.Activity.internal_static_glory_api_ActivityProduct_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zhijiejiaoyu.glory_api.shop.Activity.internal_static_glory_api_ActivityProduct_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zhijiejiaoyu.glory_api.shop.ActivityProduct.class, com.zhijiejiaoyu.glory_api.shop.ActivityProduct.Builder.class);
  }

  public static final int PRODUCT_ID_FIELD_NUMBER = 1;
  private long productId ;
  /**
   * <code>int64 product_id = 1;</code>
   * @return The productId.
   */
  @java.lang.Override
  public long getProductId() {
    return productId ;
  }

  public static final int SKU_ID_FIELD_NUMBER = 2;
  private long skuId ;
  /**
   * <code>int64 sku_id = 2;</code>
   * @return The skuId.
   */
  @java.lang.Override
  public long getSkuId() {
    return skuId ;
  }

  public static final int PREFERENTIAL_VALUE_FIELD_NUMBER = 3;
  private volatile java.lang.Object preferentialValue ;
  /**
   * <code>string preferential_value = 3;</code>
   * @return The preferentialValue.
   */
  @java.lang.Override
  public java.lang.String getPreferentialValue() {
    java.lang.Object ref = preferentialValue ;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      preferentialValue = s;
      return s;
    }
  }
  /**
   * <code>string preferential_value = 3;</code>
   * @return The bytes for preferentialValue.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPreferentialValueBytes() {
    java.lang.Object ref = preferentialValue ;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      preferentialValue = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STOCK_TOTAL_FIELD_NUMBER = 4;
  private long stockTotal ;
  /**
   * <code>int64 stock_total = 4;</code>
   * @return The stockTotal.
   */
  @java.lang.Override
  public long getStockTotal() {
    return stockTotal ;
  }

  public static final int PURCHASE_LIMIT_FIELD_NUMBER = 5;
  private long purchaseLimit ;
  /**
   * <code>int64 purchase_limit = 5;</code>
   * @return The purchaseLimit.
   */
  @java.lang.Override
  public long getPurchaseLimit() {
    return purchaseLimit ;
  }

  public static final int PRODUCT_NAME_FIELD_NUMBER = 6;
  private volatile java.lang.Object productName ;
  /**
   * <code>string product_name = 6;</code>
   * @return The productName.
   */
  @java.lang.Override
  public java.lang.String getProductName() {
    java.lang.Object ref = productName ;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productName = s;
      return s;
    }
  }
  /**
   * <code>string product_name = 6;</code>
   * @return The bytes for productName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductNameBytes() {
    java.lang.Object ref = productName ;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productName = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SKU_FIELD_NUMBER = 7;
  private java.util.List<com.zhijiejiaoyu.glory_api.shop.Sku> sku ;
  /**
   * <code>repeated .glory_api.Sku sku = 7;</code>
   */
  @java.lang.Override
  public java.util.List<com.zhijiejiaoyu.glory_api.shop.Sku> getSkuList() {
    return sku ;
  }
  /**
   * <code>repeated .glory_api.Sku sku = 7;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.zhijiejiaoyu.glory_api.shop.SkuOrBuilder> 
      getSkuOrBuilderList() {
    return sku ;
  }
  /**
   * <code>repeated .glory_api.Sku sku = 7;</code>
   */
  @java.lang.Override
  public int getSkuCount() {
    return sku .size();
  }
  /**
   * <code>repeated .glory_api.Sku sku = 7;</code>
   */
  @java.lang.Override
  public com.zhijiejiaoyu.glory_api.shop.Sku getSku(int index) {
    return sku .get(index);
  }
  /**
   * <code>repeated .glory_api.Sku sku = 7;</code>
   */
  @java.lang.Override
  public com.zhijiejiaoyu.glory_api.shop.SkuOrBuilder getSkuOrBuilder(
      int index) {
    return sku .get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (productId != 0L) {
      output.writeInt64(1, productId );
    }
    if (skuId != 0L) {
      output.writeInt64(2, skuId );
    }
    if (!getPreferentialValueBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, preferentialValue );
    }
    if (stockTotal != 0L) {
      output.writeInt64(4, stockTotal );
    }
    if (purchaseLimit != 0L) {
      output.writeInt64(5, purchaseLimit );
    }
    if (!getProductNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, productName );
    }
    for (int i = 0; i < sku .size(); i++) {
      output.writeMessage(7, sku .get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (productId != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, productId );
    }
    if (skuId != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, skuId );
    }
    if (!getPreferentialValueBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, preferentialValue );
    }
    if (stockTotal != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, stockTotal );
    }
    if (purchaseLimit != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, purchaseLimit );
    }
    if (!getProductNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, productName );
    }
    for (int i = 0; i < sku .size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, sku .get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zhijiejiaoyu.glory_api.shop.ActivityProduct)) {
      return super.equals(obj);
    }
    com.zhijiejiaoyu.glory_api.shop.ActivityProduct other = (com.zhijiejiaoyu.glory_api.shop.ActivityProduct) obj;

    if (getProductId()
        != other.getProductId()) return false;
    if (getSkuId()
        != other.getSkuId()) return false;
    if (!getPreferentialValue()
        .equals(other.getPreferentialValue())) return false;
    if (getStockTotal()
        != other.getStockTotal()) return false;
    if (getPurchaseLimit()
        != other.getPurchaseLimit()) return false;
    if (!getProductName()
        .equals(other.getProductName())) return false;
    if (!getSkuList()
        .equals(other.getSkuList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PRODUCT_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getProductId());
    hash = (37 * hash) + SKU_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSkuId());
    hash = (37 * hash) + PREFERENTIAL_VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getPreferentialValue().hashCode();
    hash = (37 * hash) + STOCK_TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStockTotal());
    hash = (37 * hash) + PURCHASE_LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPurchaseLimit());
    hash = (37 * hash) + PRODUCT_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getProductName().hashCode();
    if (getSkuCount() > 0) {
      hash = (37 * hash) + SKU_FIELD_NUMBER;
      hash = (53 * hash) + getSkuList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zhijiejiaoyu.glory_api.shop.ActivityProduct parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhijiejiaoyu.glory_api.shop.ActivityProduct parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.shop.ActivityProduct parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhijiejiaoyu.glory_api.shop.ActivityProduct parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.shop.ActivityProduct parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhijiejiaoyu.glory_api.shop.ActivityProduct parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.shop.ActivityProduct parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zhijiejiaoyu.glory_api.shop.ActivityProduct parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.shop.ActivityProduct parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zhijiejiaoyu.glory_api.shop.ActivityProduct parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.shop.ActivityProduct parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zhijiejiaoyu.glory_api.shop.ActivityProduct parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zhijiejiaoyu.glory_api.shop.ActivityProduct prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code glory_api.ActivityProduct}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:glory_api.ActivityProduct)
      com.zhijiejiaoyu.glory_api.shop.ActivityProductOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhijiejiaoyu.glory_api.shop.Activity.internal_static_glory_api_ActivityProduct_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhijiejiaoyu.glory_api.shop.Activity.internal_static_glory_api_ActivityProduct_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhijiejiaoyu.glory_api.shop.ActivityProduct.class, com.zhijiejiaoyu.glory_api.shop.ActivityProduct.Builder.class);
    }

    // Construct using com.zhijiejiaoyu.glory_api.shop.ActivityProduct.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSkuFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      productId = 0L;

      skuId = 0L;

      preferentialValue = "";

      stockTotal = 0L;

      purchaseLimit = 0L;

      productName = "";

      if (skuBuilder == null) {
        sku = java.util.Collections.emptyList();
        bitField0 = (bitField0 & ~0x00000001);
      } else {
        skuBuilder .clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zhijiejiaoyu.glory_api.shop.Activity.internal_static_glory_api_ActivityProduct_descriptor;
    }

    @java.lang.Override
    public com.zhijiejiaoyu.glory_api.shop.ActivityProduct getDefaultInstanceForType() {
      return com.zhijiejiaoyu.glory_api.shop.ActivityProduct.getDefaultInstance();
    }

    @java.lang.Override
    public com.zhijiejiaoyu.glory_api.shop.ActivityProduct build() {
      com.zhijiejiaoyu.glory_api.shop.ActivityProduct result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.zhijiejiaoyu.glory_api.shop.ActivityProduct buildPartial() {
      com.zhijiejiaoyu.glory_api.shop.ActivityProduct result = new com.zhijiejiaoyu.glory_api.shop.ActivityProduct(this);
      int from_bitField0 = bitField0 ;
      result.productId = productId ;
      result.skuId = skuId ;
      result.preferentialValue = preferentialValue ;
      result.stockTotal = stockTotal ;
      result.purchaseLimit = purchaseLimit ;
      result.productName = productName ;
      if (skuBuilder == null) {
        if (((bitField0 & 0x00000001) != 0)) {
          sku = java.util.Collections.unmodifiableList(sku );
          bitField0 = (bitField0 & ~0x00000001);
        }
        result.sku = sku ;
      } else {
        result.sku = skuBuilder .build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zhijiejiaoyu.glory_api.shop.ActivityProduct) {
        return mergeFrom((com.zhijiejiaoyu.glory_api.shop.ActivityProduct)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zhijiejiaoyu.glory_api.shop.ActivityProduct other) {
      if (other == com.zhijiejiaoyu.glory_api.shop.ActivityProduct.getDefaultInstance()) return this;
      if (other.getProductId() != 0L) {
        setProductId(other.getProductId());
      }
      if (other.getSkuId() != 0L) {
        setSkuId(other.getSkuId());
      }
      if (!other.getPreferentialValue().isEmpty()) {
        preferentialValue = other.preferentialValue ;
        onChanged();
      }
      if (other.getStockTotal() != 0L) {
        setStockTotal(other.getStockTotal());
      }
      if (other.getPurchaseLimit() != 0L) {
        setPurchaseLimit(other.getPurchaseLimit());
      }
      if (!other.getProductName().isEmpty()) {
        productName = other.productName ;
        onChanged();
      }
      if (skuBuilder == null) {
        if (!other.sku .isEmpty()) {
          if (sku .isEmpty()) {
            sku = other.sku ;
            bitField0 = (bitField0 & ~0x00000001);
          } else {
            ensureSkuIsMutable();
            sku .addAll(other.sku );
          }
          onChanged();
        }
      } else {
        if (!other.sku .isEmpty()) {
          if (skuBuilder .isEmpty()) {
            skuBuilder .dispose();
            skuBuilder = null;
            sku = other.sku ;
            bitField0 = (bitField0 & ~0x00000001);
            skuBuilder = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSkuFieldBuilder() : null;
          } else {
            skuBuilder .addAllMessages(other.sku );
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.zhijiejiaoyu.glory_api.shop.ActivityProduct parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.zhijiejiaoyu.glory_api.shop.ActivityProduct) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0 ;

    private long productId ;
    /**
     * <code>int64 product_id = 1;</code>
     * @return The productId.
     */
    @java.lang.Override
    public long getProductId() {
      return productId ;
    }
    /**
     * <code>int64 product_id = 1;</code>
     * @param value The productId to set.
     * @return This builder for chaining.
     */
    public Builder setProductId(long value) {
      
      productId = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 product_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductId() {
      
      productId = 0L;
      onChanged();
      return this;
    }

    private long skuId ;
    /**
     * <code>int64 sku_id = 2;</code>
     * @return The skuId.
     */
    @java.lang.Override
    public long getSkuId() {
      return skuId ;
    }
    /**
     * <code>int64 sku_id = 2;</code>
     * @param value The skuId to set.
     * @return This builder for chaining.
     */
    public Builder setSkuId(long value) {
      
      skuId = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 sku_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSkuId() {
      
      skuId = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object preferentialValue = "";
    /**
     * <code>string preferential_value = 3;</code>
     * @return The preferentialValue.
     */
    public java.lang.String getPreferentialValue() {
      java.lang.Object ref = preferentialValue ;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        preferentialValue = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string preferential_value = 3;</code>
     * @return The bytes for preferentialValue.
     */
    public com.google.protobuf.ByteString
        getPreferentialValueBytes() {
      java.lang.Object ref = preferentialValue ;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        preferentialValue = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string preferential_value = 3;</code>
     * @param value The preferentialValue to set.
     * @return This builder for chaining.
     */
    public Builder setPreferentialValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      preferentialValue = value;
      onChanged();
      return this;
    }
    /**
     * <code>string preferential_value = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPreferentialValue() {
      
      preferentialValue = getDefaultInstance().getPreferentialValue();
      onChanged();
      return this;
    }
    /**
     * <code>string preferential_value = 3;</code>
     * @param value The bytes for preferentialValue to set.
     * @return This builder for chaining.
     */
    public Builder setPreferentialValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      preferentialValue = value;
      onChanged();
      return this;
    }

    private long stockTotal ;
    /**
     * <code>int64 stock_total = 4;</code>
     * @return The stockTotal.
     */
    @java.lang.Override
    public long getStockTotal() {
      return stockTotal ;
    }
    /**
     * <code>int64 stock_total = 4;</code>
     * @param value The stockTotal to set.
     * @return This builder for chaining.
     */
    public Builder setStockTotal(long value) {
      
      stockTotal = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 stock_total = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStockTotal() {
      
      stockTotal = 0L;
      onChanged();
      return this;
    }

    private long purchaseLimit ;
    /**
     * <code>int64 purchase_limit = 5;</code>
     * @return The purchaseLimit.
     */
    @java.lang.Override
    public long getPurchaseLimit() {
      return purchaseLimit ;
    }
    /**
     * <code>int64 purchase_limit = 5;</code>
     * @param value The purchaseLimit to set.
     * @return This builder for chaining.
     */
    public Builder setPurchaseLimit(long value) {
      
      purchaseLimit = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 purchase_limit = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPurchaseLimit() {
      
      purchaseLimit = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object productName = "";
    /**
     * <code>string product_name = 6;</code>
     * @return The productName.
     */
    public java.lang.String getProductName() {
      java.lang.Object ref = productName ;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productName = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string product_name = 6;</code>
     * @return The bytes for productName.
     */
    public com.google.protobuf.ByteString
        getProductNameBytes() {
      java.lang.Object ref = productName ;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productName = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string product_name = 6;</code>
     * @param value The productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      productName = value;
      onChanged();
      return this;
    }
    /**
     * <code>string product_name = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductName() {
      
      productName = getDefaultInstance().getProductName();
      onChanged();
      return this;
    }
    /**
     * <code>string product_name = 6;</code>
     * @param value The bytes for productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      productName = value;
      onChanged();
      return this;
    }

    private java.util.List<com.zhijiejiaoyu.glory_api.shop.Sku> sku =
      java.util.Collections.emptyList();
    private void ensureSkuIsMutable() {
      if (!((bitField0 & 0x00000001) != 0)) {
        sku = new java.util.ArrayList<com.zhijiejiaoyu.glory_api.shop.Sku>(sku );
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.zhijiejiaoyu.glory_api.shop.Sku, com.zhijiejiaoyu.glory_api.shop.Sku.Builder, com.zhijiejiaoyu.glory_api.shop.SkuOrBuilder> skuBuilder ;

    /**
     * <code>repeated .glory_api.Sku sku = 7;</code>
     */
    public java.util.List<com.zhijiejiaoyu.glory_api.shop.Sku> getSkuList() {
      if (skuBuilder == null) {
        return java.util.Collections.unmodifiableList(sku );
      } else {
        return skuBuilder .getMessageList();
      }
    }
    /**
     * <code>repeated .glory_api.Sku sku = 7;</code>
     */
    public int getSkuCount() {
      if (skuBuilder == null) {
        return sku .size();
      } else {
        return skuBuilder .getCount();
      }
    }
    /**
     * <code>repeated .glory_api.Sku sku = 7;</code>
     */
    public com.zhijiejiaoyu.glory_api.shop.Sku getSku(int index) {
      if (skuBuilder == null) {
        return sku .get(index);
      } else {
        return skuBuilder .getMessage(index);
      }
    }
    /**
     * <code>repeated .glory_api.Sku sku = 7;</code>
     */
    public Builder setSku(
        int index, com.zhijiejiaoyu.glory_api.shop.Sku value) {
      if (skuBuilder == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSkuIsMutable();
        sku .set(index, value);
        onChanged();
      } else {
        skuBuilder .setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.Sku sku = 7;</code>
     */
    public Builder setSku(
        int index, com.zhijiejiaoyu.glory_api.shop.Sku.Builder builderForValue) {
      if (skuBuilder == null) {
        ensureSkuIsMutable();
        sku .set(index, builderForValue.build());
        onChanged();
      } else {
        skuBuilder .setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.Sku sku = 7;</code>
     */
    public Builder addSku(com.zhijiejiaoyu.glory_api.shop.Sku value) {
      if (skuBuilder == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSkuIsMutable();
        sku .add(value);
        onChanged();
      } else {
        skuBuilder .addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.Sku sku = 7;</code>
     */
    public Builder addSku(
        int index, com.zhijiejiaoyu.glory_api.shop.Sku value) {
      if (skuBuilder == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSkuIsMutable();
        sku .add(index, value);
        onChanged();
      } else {
        skuBuilder .addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.Sku sku = 7;</code>
     */
    public Builder addSku(
        com.zhijiejiaoyu.glory_api.shop.Sku.Builder builderForValue) {
      if (skuBuilder == null) {
        ensureSkuIsMutable();
        sku .add(builderForValue.build());
        onChanged();
      } else {
        skuBuilder .addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.Sku sku = 7;</code>
     */
    public Builder addSku(
        int index, com.zhijiejiaoyu.glory_api.shop.Sku.Builder builderForValue) {
      if (skuBuilder == null) {
        ensureSkuIsMutable();
        sku .add(index, builderForValue.build());
        onChanged();
      } else {
        skuBuilder .addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.Sku sku = 7;</code>
     */
    public Builder addAllSku(
        java.lang.Iterable<? extends com.zhijiejiaoyu.glory_api.shop.Sku> values) {
      if (skuBuilder == null) {
        ensureSkuIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sku );
        onChanged();
      } else {
        skuBuilder .addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.Sku sku = 7;</code>
     */
    public Builder clearSku() {
      if (skuBuilder == null) {
        sku = java.util.Collections.emptyList();
        bitField0 = (bitField0 & ~0x00000001);
        onChanged();
      } else {
        skuBuilder .clear();
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.Sku sku = 7;</code>
     */
    public Builder removeSku(int index) {
      if (skuBuilder == null) {
        ensureSkuIsMutable();
        sku .remove(index);
        onChanged();
      } else {
        skuBuilder .remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.Sku sku = 7;</code>
     */
    public com.zhijiejiaoyu.glory_api.shop.Sku.Builder getSkuBuilder(
        int index) {
      return getSkuFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .glory_api.Sku sku = 7;</code>
     */
    public com.zhijiejiaoyu.glory_api.shop.SkuOrBuilder getSkuOrBuilder(
        int index) {
      if (skuBuilder == null) {
        return sku .get(index);  } else {
        return skuBuilder .getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .glory_api.Sku sku = 7;</code>
     */
    public java.util.List<? extends com.zhijiejiaoyu.glory_api.shop.SkuOrBuilder> 
         getSkuOrBuilderList() {
      if (skuBuilder != null) {
        return skuBuilder .getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(sku );
      }
    }
    /**
     * <code>repeated .glory_api.Sku sku = 7;</code>
     */
    public com.zhijiejiaoyu.glory_api.shop.Sku.Builder addSkuBuilder() {
      return getSkuFieldBuilder().addBuilder(
          com.zhijiejiaoyu.glory_api.shop.Sku.getDefaultInstance());
    }
    /**
     * <code>repeated .glory_api.Sku sku = 7;</code>
     */
    public com.zhijiejiaoyu.glory_api.shop.Sku.Builder addSkuBuilder(
        int index) {
      return getSkuFieldBuilder().addBuilder(
          index, com.zhijiejiaoyu.glory_api.shop.Sku.getDefaultInstance());
    }
    /**
     * <code>repeated .glory_api.Sku sku = 7;</code>
     */
    public java.util.List<com.zhijiejiaoyu.glory_api.shop.Sku.Builder> 
         getSkuBuilderList() {
      return getSkuFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.zhijiejiaoyu.glory_api.shop.Sku, com.zhijiejiaoyu.glory_api.shop.Sku.Builder, com.zhijiejiaoyu.glory_api.shop.SkuOrBuilder> 
        getSkuFieldBuilder() {
      if (skuBuilder == null) {
        skuBuilder = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.zhijiejiaoyu.glory_api.shop.Sku, com.zhijiejiaoyu.glory_api.shop.Sku.Builder, com.zhijiejiaoyu.glory_api.shop.SkuOrBuilder>(
                sku ,
                ((bitField0 & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        sku = null;
      }
      return skuBuilder ;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:glory_api.ActivityProduct)
  }

  // @@protoc_insertion_point(class_scope:glory_api.ActivityProduct)
  private static final com.zhijiejiaoyu.glory_api.shop.ActivityProduct DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zhijiejiaoyu.glory_api.shop.ActivityProduct();
  }

  public static com.zhijiejiaoyu.glory_api.shop.ActivityProduct getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ActivityProduct>
      PARSER = new com.google.protobuf.AbstractParser<ActivityProduct>() {
    @java.lang.Override
    public ActivityProduct parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ActivityProduct(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ActivityProduct> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ActivityProduct> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.zhijiejiaoyu.glory_api.shop.ActivityProduct getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

