// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shop/shop.proto

package com.zhijiejiaoyu.glory_api.shop;

public interface GetShopResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:glory_api.GetShopResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.base.BaseResponse base_resp = 1;</code>
   * @return Whether the baseResp field is set.
   */
  boolean hasBaseResp();
  /**
   * <code>.base.BaseResponse base_resp = 1;</code>
   * @return The baseResp.
   */
  com.zhijiejiaoyu.base.BaseResponse getBaseResp();
  /**
   * <code>.base.BaseResponse base_resp = 1;</code>
   */
  com.zhijiejiaoyu.base.BaseResponseOrBuilder getBaseRespOrBuilder();

  /**
   * <code>.glory_api.ShopWithAuthor shop_detail = 2;</code>
   * @return Whether the shopDetail field is set.
   */
  boolean hasShopDetail();
  /**
   * <code>.glory_api.ShopWithAuthor shop_detail = 2;</code>
   * @return The shopDetail.
   */
  com.zhijiejiaoyu.glory_api.shop.ShopWithAuthor getShopDetail();
  /**
   * <code>.glory_api.ShopWithAuthor shop_detail = 2;</code>
   */
  com.zhijiejiaoyu.glory_api.shop.ShopWithAuthorOrBuilder getShopDetailOrBuilder();
}
