// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shop/shop.proto

package com.zhijiejiaoyu.glory_api.shop;

public interface ListShopRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:glory_api.ListShopRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.base.BaseRequest base_request = 1;</code>
   * @return Whether the baseRequest field is set.
   */
  boolean hasBaseRequest();
  /**
   * <code>.base.BaseRequest base_request = 1;</code>
   * @return The baseRequest.
   */
  com.zhijiejiaoyu.base.BaseRequest getBaseRequest();
  /**
   * <code>.base.BaseRequest base_request = 1;</code>
   */
  com.zhijiejiaoyu.base.BaseRequestOrBuilder getBaseRequestOrBuilder();

  /**
   * <code>int64 shop_id = 2;</code>
   * @return The shopId.
   */
  long getShopId();

  /**
   * <code>int64 seller_id = 4;</code>
   * @return The sellerId.
   */
  long getSellerId();

  /**
   * <code>string shop_name = 5;</code>
   * @return The shopName.
   */
  java.lang.String getShopName();
  /**
   * <code>string shop_name = 5;</code>
   * @return The bytes for shopName.
   */
  com.google.protobuf.ByteString
      getShopNameBytes();

  /**
   * <code>string shop_type = 6;</code>
   * @return The shopType.
   */
  java.lang.String getShopType();
  /**
   * <code>string shop_type = 6;</code>
   * @return The bytes for shopType.
   */
  com.google.protobuf.ByteString
      getShopTypeBytes();

  /**
   * <code>string province = 7;</code>
   * @return The province.
   */
  java.lang.String getProvince();
  /**
   * <code>string province = 7;</code>
   * @return The bytes for province.
   */
  com.google.protobuf.ByteString
      getProvinceBytes();

  /**
   * <code>string city = 8;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>string city = 8;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>string district = 9;</code>
   * @return The district.
   */
  java.lang.String getDistrict();
  /**
   * <code>string district = 9;</code>
   * @return The bytes for district.
   */
  com.google.protobuf.ByteString
      getDistrictBytes();

  /**
   * <code>string address = 10;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 10;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string post = 11;</code>
   * @return The post.
   */
  java.lang.String getPost();
  /**
   * <code>string post = 11;</code>
   * @return The bytes for post.
   */
  com.google.protobuf.ByteString
      getPostBytes();

  /**
   * <code>string company_name = 12;</code>
   * @return The companyName.
   */
  java.lang.String getCompanyName();
  /**
   * <code>string company_name = 12;</code>
   * @return The bytes for companyName.
   */
  com.google.protobuf.ByteString
      getCompanyNameBytes();

  /**
   * <code>string owner_name = 13;</code>
   * @return The ownerName.
   */
  java.lang.String getOwnerName();
  /**
   * <code>string owner_name = 13;</code>
   * @return The bytes for ownerName.
   */
  com.google.protobuf.ByteString
      getOwnerNameBytes();

  /**
   * <code>.base.PaginationRequest pagination = 100;</code>
   * @return Whether the pagination field is set.
   */
  boolean hasPagination();
  /**
   * <code>.base.PaginationRequest pagination = 100;</code>
   * @return The pagination.
   */
  com.zhijiejiaoyu.base.PaginationRequest getPagination();
  /**
   * <code>.base.PaginationRequest pagination = 100;</code>
   */
  com.zhijiejiaoyu.base.PaginationRequestOrBuilder getPaginationOrBuilder();
}
