// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shop/order.proto

package com.zhijiejiaoyu.glory_api.shop;

/**
 * <pre>
 *商品信息
 * </pre>
 *
 * Protobuf type {@code glory_api.ProductInfo}
 */
public final class ProductInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:glory_api.ProductInfo)
    ProductInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProductInfo.newBuilder() to construct.
  private ProductInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProductInfo() {
    productName = "";
    serviceInfo = "";
    discountInfo = "";
    images = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProductInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProductInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0 = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            productId = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            productName = s;
            break;
          }
          case 26: {
            com.zhijiejiaoyu.glory_api.shop.Sku.Builder subBuilder = null;
            if (sku != null) {
              subBuilder = sku.toBuilder();
            }
            sku = input.readMessage(com.zhijiejiaoyu.glory_api.shop.Sku.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(sku);
              sku = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            serviceInfo = s;
            break;
          }
          case 41: {

            unitPrice = input.readDouble();
            break;
          }
          case 48: {

            quantity = input.readInt32();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            discountInfo = s;
            break;
          }
          case 66: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              images = new java.util.ArrayList<com.zhijiejiaoyu.glory_api.shop.Images>();
              mutable_bitField0_ |= 0x00000001;
            }
            images.add(
                input.readMessage(com.zhijiejiaoyu.glory_api.shop.Images.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        images = java.util.Collections.unmodifiableList(images);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zhijiejiaoyu.glory_api.shop.OrderOuterClass.internal_static_glory_api_ProductInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zhijiejiaoyu.glory_api.shop.OrderOuterClass.internal_static_glory_api_ProductInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zhijiejiaoyu.glory_api.shop.ProductInfo.class, com.zhijiejiaoyu.glory_api.shop.ProductInfo.Builder.class);
  }

  public static final int PRODUCT_ID_FIELD_NUMBER = 1;
  private long productId;
  /**
   * <code>int64 product_id = 1;</code>
   * @return The productId.
   */
  @java.lang.Override
  public long getProductId() {
    return productId;
  }

  public static final int PRODUCT_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object productName;
  /**
   * <code>string product_name = 2;</code>
   * @return The productName.
   */
  @java.lang.Override
  public java.lang.String getProductName() {
    java.lang.Object ref = productName;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productName = s;
      return s;
    }
  }
  /**
   * <code>string product_name = 2;</code>
   * @return The bytes for productName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProductNameBytes() {
    java.lang.Object ref = productName;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productName = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SKU_FIELD_NUMBER = 3;
  private com.zhijiejiaoyu.glory_api.shop.Sku sku;
  /**
   * <code>.glory_api.Sku sku = 3;</code>
   * @return Whether the sku field is set.
   */
  @java.lang.Override
  public boolean hasSku() {
    return sku != null;
  }
  /**
   * <code>.glory_api.Sku sku = 3;</code>
   * @return The sku.
   */
  @java.lang.Override
  public com.zhijiejiaoyu.glory_api.shop.Sku getSku() {
    return sku == null ? com.zhijiejiaoyu.glory_api.shop.Sku.getDefaultInstance() : sku;
  }
  /**
   * <code>.glory_api.Sku sku = 3;</code>
   */
  @java.lang.Override
  public com.zhijiejiaoyu.glory_api.shop.SkuOrBuilder getSkuOrBuilder() {
    return getSku();
  }

  public static final int SERVICE_INFO_FIELD_NUMBER = 4;
  private volatile java.lang.Object serviceInfo;
  /**
   * <pre>
   *售后信息
   * </pre>
   *
   * <code>string service_info = 4;</code>
   * @return The serviceInfo.
   */
  @java.lang.Override
  public java.lang.String getServiceInfo() {
    java.lang.Object ref = serviceInfo;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serviceInfo = s;
      return s;
    }
  }
  /**
   * <pre>
   *售后信息
   * </pre>
   *
   * <code>string service_info = 4;</code>
   * @return The bytes for serviceInfo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServiceInfoBytes() {
    java.lang.Object ref = serviceInfo;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serviceInfo = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UNIT_PRICE_FIELD_NUMBER = 5;
  private double unitPrice;
  /**
   * <pre>
   *单价
   * </pre>
   *
   * <code>double unit_price = 5;</code>
   * @return The unitPrice.
   */
  @java.lang.Override
  public double getUnitPrice() {
    return unitPrice;
  }

  public static final int QUANTITY_FIELD_NUMBER = 6;
  private int quantity;
  /**
   * <pre>
   *数量
   * </pre>
   *
   * <code>int32 quantity = 6;</code>
   * @return The quantity.
   */
  @java.lang.Override
  public int getQuantity() {
    return quantity;
  }

  public static final int DISCOUNT_INFO_FIELD_NUMBER = 7;
  private volatile java.lang.Object discountInfo;
  /**
   * <pre>
   *优惠信息
   * </pre>
   *
   * <code>string discount_info = 7;</code>
   * @return The discountInfo.
   */
  @java.lang.Override
  public java.lang.String getDiscountInfo() {
    java.lang.Object ref = discountInfo;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      discountInfo = s;
      return s;
    }
  }
  /**
   * <pre>
   *优惠信息
   * </pre>
   *
   * <code>string discount_info = 7;</code>
   * @return The bytes for discountInfo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDiscountInfoBytes() {
    java.lang.Object ref = discountInfo;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      discountInfo = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMAGES_FIELD_NUMBER = 8;
  private java.util.List<com.zhijiejiaoyu.glory_api.shop.Images> images;
  /**
   * <pre>
   *商品图片
   * </pre>
   *
   * <code>repeated .glory_api.Images images = 8;</code>
   */
  @java.lang.Override
  public java.util.List<com.zhijiejiaoyu.glory_api.shop.Images> getImagesList() {
    return images;
  }
  /**
   * <pre>
   *商品图片
   * </pre>
   *
   * <code>repeated .glory_api.Images images = 8;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.zhijiejiaoyu.glory_api.shop.ImagesOrBuilder> 
      getImagesOrBuilderList() {
    return images;
  }
  /**
   * <pre>
   *商品图片
   * </pre>
   *
   * <code>repeated .glory_api.Images images = 8;</code>
   */
  @java.lang.Override
  public int getImagesCount() {
    return images.size();
  }
  /**
   * <pre>
   *商品图片
   * </pre>
   *
   * <code>repeated .glory_api.Images images = 8;</code>
   */
  @java.lang.Override
  public com.zhijiejiaoyu.glory_api.shop.Images getImages(int index) {
    return images.get(index);
  }
  /**
   * <pre>
   *商品图片
   * </pre>
   *
   * <code>repeated .glory_api.Images images = 8;</code>
   */
  @java.lang.Override
  public com.zhijiejiaoyu.glory_api.shop.ImagesOrBuilder getImagesOrBuilder(
      int index) {
    return images.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (productId != 0L) {
      output.writeInt64(1, productId);
    }
    if (!getProductNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, productName);
    }
    if (sku != null) {
      output.writeMessage(3, getSku());
    }
    if (!getServiceInfoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, serviceInfo);
    }
    if (unitPrice != 0D) {
      output.writeDouble(5, unitPrice);
    }
    if (quantity != 0) {
      output.writeInt32(6, quantity);
    }
    if (!getDiscountInfoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, discountInfo);
    }
    for (int i = 0; i < images.size(); i++) {
      output.writeMessage(8, images.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (productId != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, productId);
    }
    if (!getProductNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, productName);
    }
    if (sku != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getSku());
    }
    if (!getServiceInfoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, serviceInfo);
    }
    if (unitPrice != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, unitPrice);
    }
    if (quantity != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, quantity);
    }
    if (!getDiscountInfoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, discountInfo);
    }
    for (int i = 0; i < images.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, images.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zhijiejiaoyu.glory_api.shop.ProductInfo)) {
      return super.equals(obj);
    }
    com.zhijiejiaoyu.glory_api.shop.ProductInfo other = (com.zhijiejiaoyu.glory_api.shop.ProductInfo) obj;

    if (getProductId()
        != other.getProductId()) return false;
    if (!getProductName()
        .equals(other.getProductName())) return false;
    if (hasSku() != other.hasSku()) return false;
    if (hasSku()) {
      if (!getSku()
          .equals(other.getSku())) return false;
    }
    if (!getServiceInfo()
        .equals(other.getServiceInfo())) return false;
    if (java.lang.Double.doubleToLongBits(getUnitPrice())
        != java.lang.Double.doubleToLongBits(
            other.getUnitPrice())) return false;
    if (getQuantity()
        != other.getQuantity()) return false;
    if (!getDiscountInfo()
        .equals(other.getDiscountInfo())) return false;
    if (!getImagesList()
        .equals(other.getImagesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PRODUCT_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getProductId());
    hash = (37 * hash) + PRODUCT_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getProductName().hashCode();
    if (hasSku()) {
      hash = (37 * hash) + SKU_FIELD_NUMBER;
      hash = (53 * hash) + getSku().hashCode();
    }
    hash = (37 * hash) + SERVICE_INFO_FIELD_NUMBER;
    hash = (53 * hash) + getServiceInfo().hashCode();
    hash = (37 * hash) + UNIT_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getUnitPrice()));
    hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + getQuantity();
    hash = (37 * hash) + DISCOUNT_INFO_FIELD_NUMBER;
    hash = (53 * hash) + getDiscountInfo().hashCode();
    if (getImagesCount() > 0) {
      hash = (37 * hash) + IMAGES_FIELD_NUMBER;
      hash = (53 * hash) + getImagesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zhijiejiaoyu.glory_api.shop.ProductInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhijiejiaoyu.glory_api.shop.ProductInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.shop.ProductInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhijiejiaoyu.glory_api.shop.ProductInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.shop.ProductInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhijiejiaoyu.glory_api.shop.ProductInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.shop.ProductInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zhijiejiaoyu.glory_api.shop.ProductInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.shop.ProductInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zhijiejiaoyu.glory_api.shop.ProductInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.shop.ProductInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zhijiejiaoyu.glory_api.shop.ProductInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zhijiejiaoyu.glory_api.shop.ProductInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *商品信息
   * </pre>
   *
   * Protobuf type {@code glory_api.ProductInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:glory_api.ProductInfo)
      com.zhijiejiaoyu.glory_api.shop.ProductInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhijiejiaoyu.glory_api.shop.OrderOuterClass.internal_static_glory_api_ProductInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhijiejiaoyu.glory_api.shop.OrderOuterClass.internal_static_glory_api_ProductInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhijiejiaoyu.glory_api.shop.ProductInfo.class, com.zhijiejiaoyu.glory_api.shop.ProductInfo.Builder.class);
    }

    // Construct using com.zhijiejiaoyu.glory_api.shop.ProductInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getImagesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      productId = 0L;

      productName = "";

      if (skuBuilder == null) {
        sku = null;
      } else {
        sku = null;
        skuBuilder = null;
      }
      serviceInfo = "";

      unitPrice = 0D;

      quantity = 0;

      discountInfo = "";

      if (imagesBuilder == null) {
        images = java.util.Collections.emptyList();
        bitField0 = (bitField0_ & ~0x00000001);
      } else {
        imagesBuilder.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zhijiejiaoyu.glory_api.shop.OrderOuterClass.internal_static_glory_api_ProductInfo_descriptor;
    }

    @java.lang.Override
    public com.zhijiejiaoyu.glory_api.shop.ProductInfo getDefaultInstanceForType() {
      return com.zhijiejiaoyu.glory_api.shop.ProductInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.zhijiejiaoyu.glory_api.shop.ProductInfo build() {
      com.zhijiejiaoyu.glory_api.shop.ProductInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.zhijiejiaoyu.glory_api.shop.ProductInfo buildPartial() {
      com.zhijiejiaoyu.glory_api.shop.ProductInfo result = new com.zhijiejiaoyu.glory_api.shop.ProductInfo(this);
      int from_bitField0 = bitField0;
      result.productId = productId;
      result.productName = productName;
      if (skuBuilder == null) {
        result.sku = sku;
      } else {
        result.sku = skuBuilder.build();
      }
      result.serviceInfo = serviceInfo;
      result.unitPrice = unitPrice;
      result.quantity = quantity;
      result.discountInfo = discountInfo;
      if (imagesBuilder == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          images = java.util.Collections.unmodifiableList(images);
          bitField0 = (bitField0_ & ~0x00000001);
        }
        result.images = images;
      } else {
        result.images = imagesBuilder.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zhijiejiaoyu.glory_api.shop.ProductInfo) {
        return mergeFrom((com.zhijiejiaoyu.glory_api.shop.ProductInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zhijiejiaoyu.glory_api.shop.ProductInfo other) {
      if (other == com.zhijiejiaoyu.glory_api.shop.ProductInfo.getDefaultInstance()) return this;
      if (other.getProductId() != 0L) {
        setProductId(other.getProductId());
      }
      if (!other.getProductName().isEmpty()) {
        productName = other.productName;
        onChanged();
      }
      if (other.hasSku()) {
        mergeSku(other.getSku());
      }
      if (!other.getServiceInfo().isEmpty()) {
        serviceInfo = other.serviceInfo;
        onChanged();
      }
      if (other.getUnitPrice() != 0D) {
        setUnitPrice(other.getUnitPrice());
      }
      if (other.getQuantity() != 0) {
        setQuantity(other.getQuantity());
      }
      if (!other.getDiscountInfo().isEmpty()) {
        discountInfo = other.discountInfo;
        onChanged();
      }
      if (imagesBuilder == null) {
        if (!other.images.isEmpty()) {
          if (images.isEmpty()) {
            images = other.images;
            bitField0 = (bitField0_ & ~0x00000001);
          } else {
            ensureImagesIsMutable();
            images.addAll(other.images);
          }
          onChanged();
        }
      } else {
        if (!other.images.isEmpty()) {
          if (imagesBuilder.isEmpty()) {
            imagesBuilder.dispose();
            imagesBuilder = null;
            images = other.images;
            bitField0 = (bitField0_ & ~0x00000001);
            imagesBuilder = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getImagesFieldBuilder() : null;
          } else {
            imagesBuilder.addAllMessages(other.images);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.zhijiejiaoyu.glory_api.shop.ProductInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.zhijiejiaoyu.glory_api.shop.ProductInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0;

    private long productId_ ;
    /**
     * <code>int64 product_id = 1;</code>
     * @return The productId.
     */
    @java.lang.Override
    public long getProductId() {
      return productId;
    }
    /**
     * <code>int64 product_id = 1;</code>
     * @param value The productId to set.
     * @return This builder for chaining.
     */
    public Builder setProductId(long value) {
      
      productId = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 product_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductId() {
      
      productId = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object productName = "";
    /**
     * <code>string product_name = 2;</code>
     * @return The productName.
     */
    public java.lang.String getProductName() {
      java.lang.Object ref = productName;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productName = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string product_name = 2;</code>
     * @return The bytes for productName.
     */
    public com.google.protobuf.ByteString
        getProductNameBytes() {
      java.lang.Object ref = productName;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productName = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string product_name = 2;</code>
     * @param value The productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      productName = value;
      onChanged();
      return this;
    }
    /**
     * <code>string product_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductName() {
      
      productName = getDefaultInstance().getProductName();
      onChanged();
      return this;
    }
    /**
     * <code>string product_name = 2;</code>
     * @param value The bytes for productName to set.
     * @return This builder for chaining.
     */
    public Builder setProductNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      productName = value;
      onChanged();
      return this;
    }

    private com.zhijiejiaoyu.glory_api.shop.Sku sku;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.zhijiejiaoyu.glory_api.shop.Sku, com.zhijiejiaoyu.glory_api.shop.Sku.Builder, com.zhijiejiaoyu.glory_api.shop.SkuOrBuilder> skuBuilder;
    /**
     * <code>.glory_api.Sku sku = 3;</code>
     * @return Whether the sku field is set.
     */
    public boolean hasSku() {
      return skuBuilder != null || sku != null;
    }
    /**
     * <code>.glory_api.Sku sku = 3;</code>
     * @return The sku.
     */
    public com.zhijiejiaoyu.glory_api.shop.Sku getSku() {
      if (skuBuilder == null) {
        return sku == null ? com.zhijiejiaoyu.glory_api.shop.Sku.getDefaultInstance() : sku;
      } else {
        return skuBuilder.getMessage();
      }
    }
    /**
     * <code>.glory_api.Sku sku = 3;</code>
     */
    public Builder setSku(com.zhijiejiaoyu.glory_api.shop.Sku value) {
      if (skuBuilder == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sku = value;
        onChanged();
      } else {
        skuBuilder.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.glory_api.Sku sku = 3;</code>
     */
    public Builder setSku(
        com.zhijiejiaoyu.glory_api.shop.Sku.Builder builderForValue) {
      if (skuBuilder == null) {
        sku = builderForValue.build();
        onChanged();
      } else {
        skuBuilder.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.glory_api.Sku sku = 3;</code>
     */
    public Builder mergeSku(com.zhijiejiaoyu.glory_api.shop.Sku value) {
      if (skuBuilder == null) {
        if (sku != null) {
          sku =
            com.zhijiejiaoyu.glory_api.shop.Sku.newBuilder(sku).mergeFrom(value).buildPartial();
        } else {
          sku = value;
        }
        onChanged();
      } else {
        skuBuilder.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.glory_api.Sku sku = 3;</code>
     */
    public Builder clearSku() {
      if (skuBuilder == null) {
        sku = null;
        onChanged();
      } else {
        sku = null;
        skuBuilder = null;
      }

      return this;
    }
    /**
     * <code>.glory_api.Sku sku = 3;</code>
     */
    public com.zhijiejiaoyu.glory_api.shop.Sku.Builder getSkuBuilder() {
      
      onChanged();
      return getSkuFieldBuilder().getBuilder();
    }
    /**
     * <code>.glory_api.Sku sku = 3;</code>
     */
    public com.zhijiejiaoyu.glory_api.shop.SkuOrBuilder getSkuOrBuilder() {
      if (skuBuilder != null) {
        return skuBuilder.getMessageOrBuilder();
      } else {
        return sku == null ?
            com.zhijiejiaoyu.glory_api.shop.Sku.getDefaultInstance() : sku;
      }
    }
    /**
     * <code>.glory_api.Sku sku = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.zhijiejiaoyu.glory_api.shop.Sku, com.zhijiejiaoyu.glory_api.shop.Sku.Builder, com.zhijiejiaoyu.glory_api.shop.SkuOrBuilder> 
        getSkuFieldBuilder() {
      if (skuBuilder == null) {
        skuBuilder = new com.google.protobuf.SingleFieldBuilderV3<
            com.zhijiejiaoyu.glory_api.shop.Sku, com.zhijiejiaoyu.glory_api.shop.Sku.Builder, com.zhijiejiaoyu.glory_api.shop.SkuOrBuilder>(
                getSku(),
                getParentForChildren(),
                isClean());
        sku = null;
      }
      return skuBuilder;
    }

    private java.lang.Object serviceInfo = "";
    /**
     * <pre>
     *售后信息
     * </pre>
     *
     * <code>string service_info = 4;</code>
     * @return The serviceInfo.
     */
    public java.lang.String getServiceInfo() {
      java.lang.Object ref = serviceInfo;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceInfo = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *售后信息
     * </pre>
     *
     * <code>string service_info = 4;</code>
     * @return The bytes for serviceInfo.
     */
    public com.google.protobuf.ByteString
        getServiceInfoBytes() {
      java.lang.Object ref = serviceInfo;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceInfo = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *售后信息
     * </pre>
     *
     * <code>string service_info = 4;</code>
     * @param value The serviceInfo to set.
     * @return This builder for chaining.
     */
    public Builder setServiceInfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serviceInfo = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *售后信息
     * </pre>
     *
     * <code>string service_info = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearServiceInfo() {
      
      serviceInfo = getDefaultInstance().getServiceInfo();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *售后信息
     * </pre>
     *
     * <code>string service_info = 4;</code>
     * @param value The bytes for serviceInfo to set.
     * @return This builder for chaining.
     */
    public Builder setServiceInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serviceInfo = value;
      onChanged();
      return this;
    }

    private double unitPrice_ ;
    /**
     * <pre>
     *单价
     * </pre>
     *
     * <code>double unit_price = 5;</code>
     * @return The unitPrice.
     */
    @java.lang.Override
    public double getUnitPrice() {
      return unitPrice;
    }
    /**
     * <pre>
     *单价
     * </pre>
     *
     * <code>double unit_price = 5;</code>
     * @param value The unitPrice to set.
     * @return This builder for chaining.
     */
    public Builder setUnitPrice(double value) {
      
      unitPrice = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *单价
     * </pre>
     *
     * <code>double unit_price = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnitPrice() {
      
      unitPrice = 0D;
      onChanged();
      return this;
    }

    private int quantity_ ;
    /**
     * <pre>
     *数量
     * </pre>
     *
     * <code>int32 quantity = 6;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public int getQuantity() {
      return quantity;
    }
    /**
     * <pre>
     *数量
     * </pre>
     *
     * <code>int32 quantity = 6;</code>
     * @param value The quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantity(int value) {
      
      quantity = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *数量
     * </pre>
     *
     * <code>int32 quantity = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantity() {
      
      quantity = 0;
      onChanged();
      return this;
    }

    private java.lang.Object discountInfo = "";
    /**
     * <pre>
     *优惠信息
     * </pre>
     *
     * <code>string discount_info = 7;</code>
     * @return The discountInfo.
     */
    public java.lang.String getDiscountInfo() {
      java.lang.Object ref = discountInfo;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        discountInfo = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *优惠信息
     * </pre>
     *
     * <code>string discount_info = 7;</code>
     * @return The bytes for discountInfo.
     */
    public com.google.protobuf.ByteString
        getDiscountInfoBytes() {
      java.lang.Object ref = discountInfo;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        discountInfo = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *优惠信息
     * </pre>
     *
     * <code>string discount_info = 7;</code>
     * @param value The discountInfo to set.
     * @return This builder for chaining.
     */
    public Builder setDiscountInfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      discountInfo = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *优惠信息
     * </pre>
     *
     * <code>string discount_info = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearDiscountInfo() {
      
      discountInfo = getDefaultInstance().getDiscountInfo();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *优惠信息
     * </pre>
     *
     * <code>string discount_info = 7;</code>
     * @param value The bytes for discountInfo to set.
     * @return This builder for chaining.
     */
    public Builder setDiscountInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      discountInfo = value;
      onChanged();
      return this;
    }

    private java.util.List<com.zhijiejiaoyu.glory_api.shop.Images> images =
      java.util.Collections.emptyList();
    private void ensureImagesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        images = new java.util.ArrayList<com.zhijiejiaoyu.glory_api.shop.Images>(images);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.zhijiejiaoyu.glory_api.shop.Images, com.zhijiejiaoyu.glory_api.shop.Images.Builder, com.zhijiejiaoyu.glory_api.shop.ImagesOrBuilder> imagesBuilder;

    /**
     * <pre>
     *商品图片
     * </pre>
     *
     * <code>repeated .glory_api.Images images = 8;</code>
     */
    public java.util.List<com.zhijiejiaoyu.glory_api.shop.Images> getImagesList() {
      if (imagesBuilder == null) {
        return java.util.Collections.unmodifiableList(images);
      } else {
        return imagesBuilder.getMessageList();
      }
    }
    /**
     * <pre>
     *商品图片
     * </pre>
     *
     * <code>repeated .glory_api.Images images = 8;</code>
     */
    public int getImagesCount() {
      if (imagesBuilder == null) {
        return images.size();
      } else {
        return imagesBuilder.getCount();
      }
    }
    /**
     * <pre>
     *商品图片
     * </pre>
     *
     * <code>repeated .glory_api.Images images = 8;</code>
     */
    public com.zhijiejiaoyu.glory_api.shop.Images getImages(int index) {
      if (imagesBuilder == null) {
        return images.get(index);
      } else {
        return imagesBuilder.getMessage(index);
      }
    }
    /**
     * <pre>
     *商品图片
     * </pre>
     *
     * <code>repeated .glory_api.Images images = 8;</code>
     */
    public Builder setImages(
        int index, com.zhijiejiaoyu.glory_api.shop.Images value) {
      if (imagesBuilder == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImagesIsMutable();
        images.set(index, value);
        onChanged();
      } else {
        imagesBuilder.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *商品图片
     * </pre>
     *
     * <code>repeated .glory_api.Images images = 8;</code>
     */
    public Builder setImages(
        int index, com.zhijiejiaoyu.glory_api.shop.Images.Builder builderForValue) {
      if (imagesBuilder == null) {
        ensureImagesIsMutable();
        images.set(index, builderForValue.build());
        onChanged();
      } else {
        imagesBuilder.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *商品图片
     * </pre>
     *
     * <code>repeated .glory_api.Images images = 8;</code>
     */
    public Builder addImages(com.zhijiejiaoyu.glory_api.shop.Images value) {
      if (imagesBuilder == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImagesIsMutable();
        images.add(value);
        onChanged();
      } else {
        imagesBuilder.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *商品图片
     * </pre>
     *
     * <code>repeated .glory_api.Images images = 8;</code>
     */
    public Builder addImages(
        int index, com.zhijiejiaoyu.glory_api.shop.Images value) {
      if (imagesBuilder == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImagesIsMutable();
        images.add(index, value);
        onChanged();
      } else {
        imagesBuilder.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *商品图片
     * </pre>
     *
     * <code>repeated .glory_api.Images images = 8;</code>
     */
    public Builder addImages(
        com.zhijiejiaoyu.glory_api.shop.Images.Builder builderForValue) {
      if (imagesBuilder == null) {
        ensureImagesIsMutable();
        images.add(builderForValue.build());
        onChanged();
      } else {
        imagesBuilder.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *商品图片
     * </pre>
     *
     * <code>repeated .glory_api.Images images = 8;</code>
     */
    public Builder addImages(
        int index, com.zhijiejiaoyu.glory_api.shop.Images.Builder builderForValue) {
      if (imagesBuilder == null) {
        ensureImagesIsMutable();
        images.add(index, builderForValue.build());
        onChanged();
      } else {
        imagesBuilder.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *商品图片
     * </pre>
     *
     * <code>repeated .glory_api.Images images = 8;</code>
     */
    public Builder addAllImages(
        java.lang.Iterable<? extends com.zhijiejiaoyu.glory_api.shop.Images> values) {
      if (imagesBuilder == null) {
        ensureImagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, images);
        onChanged();
      } else {
        imagesBuilder.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *商品图片
     * </pre>
     *
     * <code>repeated .glory_api.Images images = 8;</code>
     */
    public Builder clearImages() {
      if (imagesBuilder == null) {
        images = java.util.Collections.emptyList();
        bitField0 = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        imagesBuilder.clear();
      }
      return this;
    }
    /**
     * <pre>
     *商品图片
     * </pre>
     *
     * <code>repeated .glory_api.Images images = 8;</code>
     */
    public Builder removeImages(int index) {
      if (imagesBuilder == null) {
        ensureImagesIsMutable();
        images.remove(index);
        onChanged();
      } else {
        imagesBuilder.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *商品图片
     * </pre>
     *
     * <code>repeated .glory_api.Images images = 8;</code>
     */
    public com.zhijiejiaoyu.glory_api.shop.Images.Builder getImagesBuilder(
        int index) {
      return getImagesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *商品图片
     * </pre>
     *
     * <code>repeated .glory_api.Images images = 8;</code>
     */
    public com.zhijiejiaoyu.glory_api.shop.ImagesOrBuilder getImagesOrBuilder(
        int index) {
      if (imagesBuilder == null) {
        return images.get(index);  } else {
        return imagesBuilder.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *商品图片
     * </pre>
     *
     * <code>repeated .glory_api.Images images = 8;</code>
     */
    public java.util.List<? extends com.zhijiejiaoyu.glory_api.shop.ImagesOrBuilder> 
         getImagesOrBuilderList() {
      if (imagesBuilder != null) {
        return imagesBuilder.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(images);
      }
    }
    /**
     * <pre>
     *商品图片
     * </pre>
     *
     * <code>repeated .glory_api.Images images = 8;</code>
     */
    public com.zhijiejiaoyu.glory_api.shop.Images.Builder addImagesBuilder() {
      return getImagesFieldBuilder().addBuilder(
          com.zhijiejiaoyu.glory_api.shop.Images.getDefaultInstance());
    }
    /**
     * <pre>
     *商品图片
     * </pre>
     *
     * <code>repeated .glory_api.Images images = 8;</code>
     */
    public com.zhijiejiaoyu.glory_api.shop.Images.Builder addImagesBuilder(
        int index) {
      return getImagesFieldBuilder().addBuilder(
          index, com.zhijiejiaoyu.glory_api.shop.Images.getDefaultInstance());
    }
    /**
     * <pre>
     *商品图片
     * </pre>
     *
     * <code>repeated .glory_api.Images images = 8;</code>
     */
    public java.util.List<com.zhijiejiaoyu.glory_api.shop.Images.Builder> 
         getImagesBuilderList() {
      return getImagesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.zhijiejiaoyu.glory_api.shop.Images, com.zhijiejiaoyu.glory_api.shop.Images.Builder, com.zhijiejiaoyu.glory_api.shop.ImagesOrBuilder> 
        getImagesFieldBuilder() {
      if (imagesBuilder == null) {
        imagesBuilder = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.zhijiejiaoyu.glory_api.shop.Images, com.zhijiejiaoyu.glory_api.shop.Images.Builder, com.zhijiejiaoyu.glory_api.shop.ImagesOrBuilder>(
                images_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        images = null;
      }
      return imagesBuilder;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:glory_api.ProductInfo)
  }

  // @@protoc_insertion_point(class_scope:glory_api.ProductInfo)
  private static final com.zhijiejiaoyu.glory_api.shop.ProductInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zhijiejiaoyu.glory_api.shop.ProductInfo();
  }

  public static com.zhijiejiaoyu.glory_api.shop.ProductInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProductInfo>
      PARSER = new com.google.protobuf.AbstractParser<ProductInfo>() {
    @java.lang.Override
    public ProductInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProductInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProductInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProductInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.zhijiejiaoyu.glory_api.shop.ProductInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

