// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live/live_evaluate.proto

package com.zhijiejiaoyu.glory_api.live;

public interface FeedbackOrBuilder extends
    // @@protoc_insertion_point(interface_extends:glory_api.Feedback)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string enjoyment = 1;</code>
   * @return The enjoyment.
   */
  java.lang.String getEnjoyment();
  /**
   * <code>string enjoyment = 1;</code>
   * @return The bytes for enjoyment.
   */
  com.google.protobuf.ByteString
      getEnjoymentBytes();

  /**
   * <code>string logic = 2;</code>
   * @return The logic.
   */
  java.lang.String getLogic();
  /**
   * <code>string logic = 2;</code>
   * @return The bytes for logic.
   */
  com.google.protobuf.ByteString
      getLogicBytes();

  /**
   * <code>string innovative = 3;</code>
   * @return The innovative.
   */
  java.lang.String getInnovative();
  /**
   * <code>string innovative = 3;</code>
   * @return The bytes for innovative.
   */
  com.google.protobuf.ByteString
      getInnovativeBytes();

  /**
   * <code>repeated .glory_api.ProductProfession product_profession = 4;</code>
   */
  java.util.List<com.zhijiejiaoyu.glory_api.live.ProductProfession> 
      getProductProfessionList();
  /**
   * <code>repeated .glory_api.ProductProfession product_profession = 4;</code>
   */
  com.zhijiejiaoyu.glory_api.live.ProductProfession getProductProfession(int index);
  /**
   * <code>repeated .glory_api.ProductProfession product_profession = 4;</code>
   */
  int getProductProfessionCount();
  /**
   * <code>repeated .glory_api.ProductProfession product_profession = 4;</code>
   */
  java.util.List<? extends com.zhijiejiaoyu.glory_api.live.ProductProfessionOrBuilder> 
      getProductProfessionOrBuilderList();
  /**
   * <code>repeated .glory_api.ProductProfession product_profession = 4;</code>
   */
  com.zhijiejiaoyu.glory_api.live.ProductProfessionOrBuilder getProductProfessionOrBuilder(
      int index);
}
