// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live/live_board.proto

package com.zhijiejiaoyu.glory_api.live;

/**
 * Protobuf type {@code glory_api.GetAggregationLiveUrlResponse}
 */
public final class GetAggregationLiveUrlResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:glory_api.GetAggregationLiveUrlResponse)
    GetAggregationLiveUrlResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetAggregationLiveUrlResponse.newBuilder() to construct.
  private GetAggregationLiveUrlResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetAggregationLiveUrlResponse() {
    liveUrl = "";
    casterId = "";
    roomIds = emptyLongList();
    liveUrls = com.google.protobuf.LazyStringArrayList.EMPTY;
    liveUsers = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetAggregationLiveUrlResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetAggregationLiveUrlResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0 = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.zhijiejiaoyu.base.BaseResponse.Builder subBuilder = null;
            if (baseResp != null) {
              subBuilder = baseResp .toBuilder();
            }
            baseResp = input.readMessage(com.zhijiejiaoyu.base.BaseResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(baseResp );
              baseResp = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            liveUrl = s;
            break;
          }
          case 24: {

            mixCount = input.readInt64();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            casterId = s;
            break;
          }
          case 40: {

            total = input.readInt64();
            break;
          }
          case 48: {
            if (!((mutable_bitField0 & 0x00000001) != 0)) {
              roomIds = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            roomIds .addLong(input.readInt64());
            break;
          }
          case 50: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0 & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              roomIds = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              roomIds .addLong(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0 & 0x00000002) != 0)) {
              liveUrls = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            liveUrls .add(s);
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0 & 0x00000004) != 0)) {
              liveUsers = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            liveUsers .add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0 & 0x00000001) != 0)) {
        roomIds .makeImmutable(); // C
      }
      if (((mutable_bitField0 & 0x00000002) != 0)) {
        liveUrls = liveUrls .getUnmodifiableView();
      }
      if (((mutable_bitField0 & 0x00000004) != 0)) {
        liveUsers = liveUsers .getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zhijiejiaoyu.glory_api.live.LiveBoard.internal_static_glory_api_GetAggregationLiveUrlResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zhijiejiaoyu.glory_api.live.LiveBoard.internal_static_glory_api_GetAggregationLiveUrlResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse.class, com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse.Builder.class);
  }

  public static final int BASE_RESP_FIELD_NUMBER = 1;
  private com.zhijiejiaoyu.base.BaseResponse baseResp ;
  /**
   * <code>.base.BaseResponse base_resp = 1;</code>
   * @return Whether the baseResp field is set.
   */
  @java.lang.Override
  public boolean hasBaseResp() {
    return baseResp != null;
  }
  /**
   * <code>.base.BaseResponse base_resp = 1;</code>
   * @return The baseResp.
   */
  @java.lang.Override
  public com.zhijiejiaoyu.base.BaseResponse getBaseResp() {
    return baseResp == null ? com.zhijiejiaoyu.base.BaseResponse.getDefaultInstance() : baseResp ;
  }
  /**
   * <code>.base.BaseResponse base_resp = 1;</code>
   */
  @java.lang.Override
  public com.zhijiejiaoyu.base.BaseResponseOrBuilder getBaseRespOrBuilder() {
    return getBaseResp();
  }

  public static final int LIVE_URL_FIELD_NUMBER = 2;
  private volatile java.lang.Object liveUrl ;
  /**
   * <code>string live_url = 2;</code>
   * @return The liveUrl.
   */
  @java.lang.Override
  public java.lang.String getLiveUrl() {
    java.lang.Object ref = liveUrl ;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      liveUrl = s;
      return s;
    }
  }
  /**
   * <code>string live_url = 2;</code>
   * @return The bytes for liveUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLiveUrlBytes() {
    java.lang.Object ref = liveUrl ;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      liveUrl = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MIX_COUNT_FIELD_NUMBER = 3;
  private long mixCount ;
  /**
   * <code>int64 mix_count = 3;</code>
   * @return The mixCount.
   */
  @java.lang.Override
  public long getMixCount() {
    return mixCount ;
  }

  public static final int CASTER_ID_FIELD_NUMBER = 4;
  private volatile java.lang.Object casterId ;
  /**
   * <code>string caster_id = 4;</code>
   * @return The casterId.
   */
  @java.lang.Override
  public java.lang.String getCasterId() {
    java.lang.Object ref = casterId ;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      casterId = s;
      return s;
    }
  }
  /**
   * <code>string caster_id = 4;</code>
   * @return The bytes for casterId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCasterIdBytes() {
    java.lang.Object ref = casterId ;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      casterId = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTAL_FIELD_NUMBER = 5;
  private long total ;
  /**
   * <code>int64 total = 5;</code>
   * @return The total.
   */
  @java.lang.Override
  public long getTotal() {
    return total ;
  }

  public static final int ROOM_IDS_FIELD_NUMBER = 6;
  private com.google.protobuf.Internal.LongList roomIds ;
  /**
   * <code>repeated int64 room_ids = 6;</code>
   * @return A list containing the roomIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getRoomIdsList() {
    return roomIds ;
  }
  /**
   * <code>repeated int64 room_ids = 6;</code>
   * @return The count of roomIds.
   */
  public int getRoomIdsCount() {
    return roomIds .size();
  }
  /**
   * <code>repeated int64 room_ids = 6;</code>
   * @param index The index of the element to return.
   * @return The roomIds at the given index.
   */
  public long getRoomIds(int index) {
    return roomIds .getLong(index);
  }
  private int roomIdsMemoizedSerializedSize = -1;

  public static final int LIVE_URLS_FIELD_NUMBER = 7;
  private com.google.protobuf.LazyStringList liveUrls ;
  /**
   * <code>repeated string live_urls = 7;</code>
   * @return A list containing the liveUrls.
   */
  public com.google.protobuf.ProtocolStringList
      getLiveUrlsList() {
    return liveUrls ;
  }
  /**
   * <code>repeated string live_urls = 7;</code>
   * @return The count of liveUrls.
   */
  public int getLiveUrlsCount() {
    return liveUrls .size();
  }
  /**
   * <code>repeated string live_urls = 7;</code>
   * @param index The index of the element to return.
   * @return The liveUrls at the given index.
   */
  public java.lang.String getLiveUrls(int index) {
    return liveUrls .get(index);
  }
  /**
   * <code>repeated string live_urls = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the liveUrls at the given index.
   */
  public com.google.protobuf.ByteString
      getLiveUrlsBytes(int index) {
    return liveUrls .getByteString(index);
  }

  public static final int LIVE_USERS_FIELD_NUMBER = 8;
  private com.google.protobuf.LazyStringList liveUsers ;
  /**
   * <code>repeated string live_users = 8;</code>
   * @return A list containing the liveUsers.
   */
  public com.google.protobuf.ProtocolStringList
      getLiveUsersList() {
    return liveUsers ;
  }
  /**
   * <code>repeated string live_users = 8;</code>
   * @return The count of liveUsers.
   */
  public int getLiveUsersCount() {
    return liveUsers .size();
  }
  /**
   * <code>repeated string live_users = 8;</code>
   * @param index The index of the element to return.
   * @return The liveUsers at the given index.
   */
  public java.lang.String getLiveUsers(int index) {
    return liveUsers .get(index);
  }
  /**
   * <code>repeated string live_users = 8;</code>
   * @param index The index of the value to return.
   * @return The bytes of the liveUsers at the given index.
   */
  public com.google.protobuf.ByteString
      getLiveUsersBytes(int index) {
    return liveUsers .getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (baseResp != null) {
      output.writeMessage(1, getBaseResp());
    }
    if (!getLiveUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, liveUrl );
    }
    if (mixCount != 0L) {
      output.writeInt64(3, mixCount );
    }
    if (!getCasterIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, casterId );
    }
    if (total != 0L) {
      output.writeInt64(5, total );
    }
    if (getRoomIdsList().size() > 0) {
      output.writeUInt32NoTag(50);
      output.writeUInt32NoTag(roomIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < roomIds .size(); i++) {
      output.writeInt64NoTag(roomIds .getLong(i));
    }
    for (int i = 0; i < liveUrls .size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, liveUrls .getRaw(i));
    }
    for (int i = 0; i < liveUsers .size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, liveUsers .getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (baseResp != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBaseResp());
    }
    if (!getLiveUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, liveUrl );
    }
    if (mixCount != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, mixCount );
    }
    if (!getCasterIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, casterId );
    }
    if (total != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, total );
    }
    {
      int dataSize = 0;
      for (int i = 0; i < roomIds .size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(roomIds .getLong(i));
      }
      size += dataSize;
      if (!getRoomIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      roomIdsMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      for (int i = 0; i < liveUrls .size(); i++) {
        dataSize += computeStringSizeNoTag(liveUrls .getRaw(i));
      }
      size += dataSize;
      size += 1 * getLiveUrlsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < liveUsers .size(); i++) {
        dataSize += computeStringSizeNoTag(liveUsers .getRaw(i));
      }
      size += dataSize;
      size += 1 * getLiveUsersList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse)) {
      return super.equals(obj);
    }
    com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse other = (com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse) obj;

    if (hasBaseResp() != other.hasBaseResp()) return false;
    if (hasBaseResp()) {
      if (!getBaseResp()
          .equals(other.getBaseResp())) return false;
    }
    if (!getLiveUrl()
        .equals(other.getLiveUrl())) return false;
    if (getMixCount()
        != other.getMixCount()) return false;
    if (!getCasterId()
        .equals(other.getCasterId())) return false;
    if (getTotal()
        != other.getTotal()) return false;
    if (!getRoomIdsList()
        .equals(other.getRoomIdsList())) return false;
    if (!getLiveUrlsList()
        .equals(other.getLiveUrlsList())) return false;
    if (!getLiveUsersList()
        .equals(other.getLiveUsersList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBaseResp()) {
      hash = (37 * hash) + BASE_RESP_FIELD_NUMBER;
      hash = (53 * hash) + getBaseResp().hashCode();
    }
    hash = (37 * hash) + LIVE_URL_FIELD_NUMBER;
    hash = (53 * hash) + getLiveUrl().hashCode();
    hash = (37 * hash) + MIX_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMixCount());
    hash = (37 * hash) + CASTER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCasterId().hashCode();
    hash = (37 * hash) + TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotal());
    if (getRoomIdsCount() > 0) {
      hash = (37 * hash) + ROOM_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getRoomIdsList().hashCode();
    }
    if (getLiveUrlsCount() > 0) {
      hash = (37 * hash) + LIVE_URLS_FIELD_NUMBER;
      hash = (53 * hash) + getLiveUrlsList().hashCode();
    }
    if (getLiveUsersCount() > 0) {
      hash = (37 * hash) + LIVE_USERS_FIELD_NUMBER;
      hash = (53 * hash) + getLiveUsersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code glory_api.GetAggregationLiveUrlResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:glory_api.GetAggregationLiveUrlResponse)
      com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhijiejiaoyu.glory_api.live.LiveBoard.internal_static_glory_api_GetAggregationLiveUrlResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhijiejiaoyu.glory_api.live.LiveBoard.internal_static_glory_api_GetAggregationLiveUrlResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse.class, com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse.Builder.class);
    }

    // Construct using com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (baseRespBuilder == null) {
        baseResp = null;
      } else {
        baseResp = null;
        baseRespBuilder = null;
      }
      liveUrl = "";

      mixCount = 0L;

      casterId = "";

      total = 0L;

      roomIds = emptyLongList();
      bitField0 = (bitField0 & ~0x00000001);
      liveUrls = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0 = (bitField0 & ~0x00000002);
      liveUsers = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0 = (bitField0 & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zhijiejiaoyu.glory_api.live.LiveBoard.internal_static_glory_api_GetAggregationLiveUrlResponse_descriptor;
    }

    @java.lang.Override
    public com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse getDefaultInstanceForType() {
      return com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse build() {
      com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse buildPartial() {
      com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse result = new com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse(this);
      int from_bitField0 = bitField0 ;
      if (baseRespBuilder == null) {
        result.baseResp = baseResp ;
      } else {
        result.baseResp = baseRespBuilder .build();
      }
      result.liveUrl = liveUrl ;
      result.mixCount = mixCount ;
      result.casterId = casterId ;
      result.total = total ;
      if (((bitField0 & 0x00000001) != 0)) {
        roomIds .makeImmutable();
        bitField0 = (bitField0 & ~0x00000001);
      }
      result.roomIds = roomIds ;
      if (((bitField0 & 0x00000002) != 0)) {
        liveUrls = liveUrls .getUnmodifiableView();
        bitField0 = (bitField0 & ~0x00000002);
      }
      result.liveUrls = liveUrls ;
      if (((bitField0 & 0x00000004) != 0)) {
        liveUsers = liveUsers .getUnmodifiableView();
        bitField0 = (bitField0 & ~0x00000004);
      }
      result.liveUsers = liveUsers ;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse) {
        return mergeFrom((com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse other) {
      if (other == com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse.getDefaultInstance()) return this;
      if (other.hasBaseResp()) {
        mergeBaseResp(other.getBaseResp());
      }
      if (!other.getLiveUrl().isEmpty()) {
        liveUrl = other.liveUrl ;
        onChanged();
      }
      if (other.getMixCount() != 0L) {
        setMixCount(other.getMixCount());
      }
      if (!other.getCasterId().isEmpty()) {
        casterId = other.casterId ;
        onChanged();
      }
      if (other.getTotal() != 0L) {
        setTotal(other.getTotal());
      }
      if (!other.roomIds .isEmpty()) {
        if (roomIds .isEmpty()) {
          roomIds = other.roomIds ;
          bitField0 = (bitField0 & ~0x00000001);
        } else {
          ensureRoomIdsIsMutable();
          roomIds .addAll(other.roomIds );
        }
        onChanged();
      }
      if (!other.liveUrls .isEmpty()) {
        if (liveUrls .isEmpty()) {
          liveUrls = other.liveUrls ;
          bitField0 = (bitField0 & ~0x00000002);
        } else {
          ensureLiveUrlsIsMutable();
          liveUrls .addAll(other.liveUrls );
        }
        onChanged();
      }
      if (!other.liveUsers .isEmpty()) {
        if (liveUsers .isEmpty()) {
          liveUsers = other.liveUsers ;
          bitField0 = (bitField0 & ~0x00000004);
        } else {
          ensureLiveUsersIsMutable();
          liveUsers .addAll(other.liveUsers );
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0 ;

    private com.zhijiejiaoyu.base.BaseResponse baseResp ;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.zhijiejiaoyu.base.BaseResponse, com.zhijiejiaoyu.base.BaseResponse.Builder, com.zhijiejiaoyu.base.BaseResponseOrBuilder> baseRespBuilder ;
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     * @return Whether the baseResp field is set.
     */
    public boolean hasBaseResp() {
      return baseRespBuilder != null || baseResp != null;
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     * @return The baseResp.
     */
    public com.zhijiejiaoyu.base.BaseResponse getBaseResp() {
      if (baseRespBuilder == null) {
        return baseResp == null ? com.zhijiejiaoyu.base.BaseResponse.getDefaultInstance() : baseResp ;
      } else {
        return baseRespBuilder .getMessage();
      }
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    public Builder setBaseResp(com.zhijiejiaoyu.base.BaseResponse value) {
      if (baseRespBuilder == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        baseResp = value;
        onChanged();
      } else {
        baseRespBuilder .setMessage(value);
      }

      return this;
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    public Builder setBaseResp(
        com.zhijiejiaoyu.base.BaseResponse.Builder builderForValue) {
      if (baseRespBuilder == null) {
        baseResp = builderForValue.build();
        onChanged();
      } else {
        baseRespBuilder .setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    public Builder mergeBaseResp(com.zhijiejiaoyu.base.BaseResponse value) {
      if (baseRespBuilder == null) {
        if (baseResp != null) {
          baseResp =
            com.zhijiejiaoyu.base.BaseResponse.newBuilder(baseResp ).mergeFrom(value).buildPartial();
        } else {
          baseResp = value;
        }
        onChanged();
      } else {
        baseRespBuilder .mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    public Builder clearBaseResp() {
      if (baseRespBuilder == null) {
        baseResp = null;
        onChanged();
      } else {
        baseResp = null;
        baseRespBuilder = null;
      }

      return this;
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    public com.zhijiejiaoyu.base.BaseResponse.Builder getBaseRespBuilder() {
      
      onChanged();
      return getBaseRespFieldBuilder().getBuilder();
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    public com.zhijiejiaoyu.base.BaseResponseOrBuilder getBaseRespOrBuilder() {
      if (baseRespBuilder != null) {
        return baseRespBuilder .getMessageOrBuilder();
      } else {
        return baseResp == null ?
            com.zhijiejiaoyu.base.BaseResponse.getDefaultInstance() : baseResp ;
      }
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.zhijiejiaoyu.base.BaseResponse, com.zhijiejiaoyu.base.BaseResponse.Builder, com.zhijiejiaoyu.base.BaseResponseOrBuilder> 
        getBaseRespFieldBuilder() {
      if (baseRespBuilder == null) {
        baseRespBuilder = new com.google.protobuf.SingleFieldBuilderV3<
            com.zhijiejiaoyu.base.BaseResponse, com.zhijiejiaoyu.base.BaseResponse.Builder, com.zhijiejiaoyu.base.BaseResponseOrBuilder>(
                getBaseResp(),
                getParentForChildren(),
                isClean());
        baseResp = null;
      }
      return baseRespBuilder ;
    }

    private java.lang.Object liveUrl = "";
    /**
     * <code>string live_url = 2;</code>
     * @return The liveUrl.
     */
    public java.lang.String getLiveUrl() {
      java.lang.Object ref = liveUrl ;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        liveUrl = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string live_url = 2;</code>
     * @return The bytes for liveUrl.
     */
    public com.google.protobuf.ByteString
        getLiveUrlBytes() {
      java.lang.Object ref = liveUrl ;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        liveUrl = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string live_url = 2;</code>
     * @param value The liveUrl to set.
     * @return This builder for chaining.
     */
    public Builder setLiveUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      liveUrl = value;
      onChanged();
      return this;
    }
    /**
     * <code>string live_url = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLiveUrl() {
      
      liveUrl = getDefaultInstance().getLiveUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string live_url = 2;</code>
     * @param value The bytes for liveUrl to set.
     * @return This builder for chaining.
     */
    public Builder setLiveUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      liveUrl = value;
      onChanged();
      return this;
    }

    private long mixCount ;
    /**
     * <code>int64 mix_count = 3;</code>
     * @return The mixCount.
     */
    @java.lang.Override
    public long getMixCount() {
      return mixCount ;
    }
    /**
     * <code>int64 mix_count = 3;</code>
     * @param value The mixCount to set.
     * @return This builder for chaining.
     */
    public Builder setMixCount(long value) {
      
      mixCount = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 mix_count = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMixCount() {
      
      mixCount = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object casterId = "";
    /**
     * <code>string caster_id = 4;</code>
     * @return The casterId.
     */
    public java.lang.String getCasterId() {
      java.lang.Object ref = casterId ;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        casterId = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string caster_id = 4;</code>
     * @return The bytes for casterId.
     */
    public com.google.protobuf.ByteString
        getCasterIdBytes() {
      java.lang.Object ref = casterId ;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        casterId = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string caster_id = 4;</code>
     * @param value The casterId to set.
     * @return This builder for chaining.
     */
    public Builder setCasterId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      casterId = value;
      onChanged();
      return this;
    }
    /**
     * <code>string caster_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCasterId() {
      
      casterId = getDefaultInstance().getCasterId();
      onChanged();
      return this;
    }
    /**
     * <code>string caster_id = 4;</code>
     * @param value The bytes for casterId to set.
     * @return This builder for chaining.
     */
    public Builder setCasterIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      casterId = value;
      onChanged();
      return this;
    }

    private long total ;
    /**
     * <code>int64 total = 5;</code>
     * @return The total.
     */
    @java.lang.Override
    public long getTotal() {
      return total ;
    }
    /**
     * <code>int64 total = 5;</code>
     * @param value The total to set.
     * @return This builder for chaining.
     */
    public Builder setTotal(long value) {
      
      total = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 total = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotal() {
      
      total = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList roomIds = emptyLongList();
    private void ensureRoomIdsIsMutable() {
      if (!((bitField0 & 0x00000001) != 0)) {
        roomIds = mutableCopy(roomIds );
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int64 room_ids = 6;</code>
     * @return A list containing the roomIds.
     */
    public java.util.List<java.lang.Long>
        getRoomIdsList() {
      return ((bitField0 & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(roomIds ) : roomIds ;
    }
    /**
     * <code>repeated int64 room_ids = 6;</code>
     * @return The count of roomIds.
     */
    public int getRoomIdsCount() {
      return roomIds .size();
    }
    /**
     * <code>repeated int64 room_ids = 6;</code>
     * @param index The index of the element to return.
     * @return The roomIds at the given index.
     */
    public long getRoomIds(int index) {
      return roomIds .getLong(index);
    }
    /**
     * <code>repeated int64 room_ids = 6;</code>
     * @param index The index to set the value at.
     * @param value The roomIds to set.
     * @return This builder for chaining.
     */
    public Builder setRoomIds(
        int index, long value) {
      ensureRoomIdsIsMutable();
      roomIds .setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 room_ids = 6;</code>
     * @param value The roomIds to add.
     * @return This builder for chaining.
     */
    public Builder addRoomIds(long value) {
      ensureRoomIdsIsMutable();
      roomIds .addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 room_ids = 6;</code>
     * @param values The roomIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllRoomIds(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureRoomIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, roomIds );
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 room_ids = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoomIds() {
      roomIds = emptyLongList();
      bitField0 = (bitField0 & ~0x00000001);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList liveUrls = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureLiveUrlsIsMutable() {
      if (!((bitField0 & 0x00000002) != 0)) {
        liveUrls = new com.google.protobuf.LazyStringArrayList(liveUrls );
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string live_urls = 7;</code>
     * @return A list containing the liveUrls.
     */
    public com.google.protobuf.ProtocolStringList
        getLiveUrlsList() {
      return liveUrls .getUnmodifiableView();
    }
    /**
     * <code>repeated string live_urls = 7;</code>
     * @return The count of liveUrls.
     */
    public int getLiveUrlsCount() {
      return liveUrls .size();
    }
    /**
     * <code>repeated string live_urls = 7;</code>
     * @param index The index of the element to return.
     * @return The liveUrls at the given index.
     */
    public java.lang.String getLiveUrls(int index) {
      return liveUrls .get(index);
    }
    /**
     * <code>repeated string live_urls = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the liveUrls at the given index.
     */
    public com.google.protobuf.ByteString
        getLiveUrlsBytes(int index) {
      return liveUrls .getByteString(index);
    }
    /**
     * <code>repeated string live_urls = 7;</code>
     * @param index The index to set the value at.
     * @param value The liveUrls to set.
     * @return This builder for chaining.
     */
    public Builder setLiveUrls(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureLiveUrlsIsMutable();
      liveUrls .set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string live_urls = 7;</code>
     * @param value The liveUrls to add.
     * @return This builder for chaining.
     */
    public Builder addLiveUrls(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureLiveUrlsIsMutable();
      liveUrls .add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string live_urls = 7;</code>
     * @param values The liveUrls to add.
     * @return This builder for chaining.
     */
    public Builder addAllLiveUrls(
        java.lang.Iterable<java.lang.String> values) {
      ensureLiveUrlsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, liveUrls );
      onChanged();
      return this;
    }
    /**
     * <code>repeated string live_urls = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearLiveUrls() {
      liveUrls = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0 = (bitField0 & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string live_urls = 7;</code>
     * @param value The bytes of the liveUrls to add.
     * @return This builder for chaining.
     */
    public Builder addLiveUrlsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureLiveUrlsIsMutable();
      liveUrls .add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList liveUsers = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureLiveUsersIsMutable() {
      if (!((bitField0 & 0x00000004) != 0)) {
        liveUsers = new com.google.protobuf.LazyStringArrayList(liveUsers );
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated string live_users = 8;</code>
     * @return A list containing the liveUsers.
     */
    public com.google.protobuf.ProtocolStringList
        getLiveUsersList() {
      return liveUsers .getUnmodifiableView();
    }
    /**
     * <code>repeated string live_users = 8;</code>
     * @return The count of liveUsers.
     */
    public int getLiveUsersCount() {
      return liveUsers .size();
    }
    /**
     * <code>repeated string live_users = 8;</code>
     * @param index The index of the element to return.
     * @return The liveUsers at the given index.
     */
    public java.lang.String getLiveUsers(int index) {
      return liveUsers .get(index);
    }
    /**
     * <code>repeated string live_users = 8;</code>
     * @param index The index of the value to return.
     * @return The bytes of the liveUsers at the given index.
     */
    public com.google.protobuf.ByteString
        getLiveUsersBytes(int index) {
      return liveUsers .getByteString(index);
    }
    /**
     * <code>repeated string live_users = 8;</code>
     * @param index The index to set the value at.
     * @param value The liveUsers to set.
     * @return This builder for chaining.
     */
    public Builder setLiveUsers(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureLiveUsersIsMutable();
      liveUsers .set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string live_users = 8;</code>
     * @param value The liveUsers to add.
     * @return This builder for chaining.
     */
    public Builder addLiveUsers(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureLiveUsersIsMutable();
      liveUsers .add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string live_users = 8;</code>
     * @param values The liveUsers to add.
     * @return This builder for chaining.
     */
    public Builder addAllLiveUsers(
        java.lang.Iterable<java.lang.String> values) {
      ensureLiveUsersIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, liveUsers );
      onChanged();
      return this;
    }
    /**
     * <code>repeated string live_users = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearLiveUsers() {
      liveUsers = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0 = (bitField0 & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string live_users = 8;</code>
     * @param value The bytes of the liveUsers to add.
     * @return This builder for chaining.
     */
    public Builder addLiveUsersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureLiveUsersIsMutable();
      liveUsers .add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:glory_api.GetAggregationLiveUrlResponse)
  }

  // @@protoc_insertion_point(class_scope:glory_api.GetAggregationLiveUrlResponse)
  private static final com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse();
  }

  public static com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAggregationLiveUrlResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetAggregationLiveUrlResponse>() {
    @java.lang.Override
    public GetAggregationLiveUrlResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetAggregationLiveUrlResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetAggregationLiveUrlResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAggregationLiveUrlResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.zhijiejiaoyu.glory_api.live.GetAggregationLiveUrlResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

