// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live/live_control.proto

package com.zhijiejiaoyu.glory_api.live;

public interface ListLiveControlResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:glory_api.ListLiveControlResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.base.BaseResponse base_resp = 1;</code>
   * @return Whether the baseResp field is set.
   */
  boolean hasBaseResp();
  /**
   * <code>.base.BaseResponse base_resp = 1;</code>
   * @return The baseResp.
   */
  com.zhijiejiaoyu.base.BaseResponse getBaseResp();
  /**
   * <code>.base.BaseResponse base_resp = 1;</code>
   */
  com.zhijiejiaoyu.base.BaseResponseOrBuilder getBaseRespOrBuilder();

  /**
   * <code>repeated .glory_api.LiveControl live_control_list = 2;</code>
   */
  java.util.List<com.zhijiejiaoyu.glory_api.live.LiveControl> 
      getLiveControlListList();
  /**
   * <code>repeated .glory_api.LiveControl live_control_list = 2;</code>
   */
  com.zhijiejiaoyu.glory_api.live.LiveControl getLiveControlList(int index);
  /**
   * <code>repeated .glory_api.LiveControl live_control_list = 2;</code>
   */
  int getLiveControlListCount();
  /**
   * <code>repeated .glory_api.LiveControl live_control_list = 2;</code>
   */
  java.util.List<? extends com.zhijiejiaoyu.glory_api.live.LiveControlOrBuilder> 
      getLiveControlListOrBuilderList();
  /**
   * <code>repeated .glory_api.LiveControl live_control_list = 2;</code>
   */
  com.zhijiejiaoyu.glory_api.live.LiveControlOrBuilder getLiveControlListOrBuilder(
      int index);
}
