// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live/live_plan.proto

package com.zhijiejiaoyu.glory_api.live;

public final class LivePlanOuterClass {
  private LivePlanOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_LivePlan_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_LivePlan_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_CreateLivePlanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_CreateLivePlanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_CreateLivePlanResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_CreateLivePlanResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_PlanProduct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_PlanProduct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_GetLivePlanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_GetLivePlanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_GetLivePlanResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_GetLivePlanResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_UpdateLivePlanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_UpdateLivePlanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_UpdateLivePlanResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_UpdateLivePlanResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_ListLivePlanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_ListLivePlanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_ListLivePlanResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_ListLivePlanResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_DeleteLivePlanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_DeleteLivePlanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_DeleteLivePlanResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_DeleteLivePlanResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_LivePlanProduct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_LivePlanProduct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_CreateLivePlanProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_CreateLivePlanProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_CreateLivePlanProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_CreateLivePlanProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_UpdateLivePlanProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_UpdateLivePlanProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_UpdateLivePlanProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_UpdateLivePlanProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_ListLivePlanProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_ListLivePlanProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_ListLivePlanProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_ListLivePlanProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_DeleteLivePlanProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_DeleteLivePlanProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_DeleteLivePlanProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_DeleteLivePlanProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_LoadLivePlanProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_LoadLivePlanProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_LoadLivePlanProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_LoadLivePlanProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_CreateLiveProductStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_CreateLiveProductStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_CreateLiveProductStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_CreateLiveProductStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_CreateLiveProductStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_CreateLiveProductStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_UpdateLiveProductStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_UpdateLiveProductStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_UpdateLiveProductStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_UpdateLiveProductStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_LiveProductStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_LiveProductStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_ListLiveProductStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_ListLiveProductStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_ListLiveProductStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_ListLiveProductStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_DeleteLiveProductStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_DeleteLiveProductStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_DeleteLiveProductStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_DeleteLiveProductStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_GetLivingProductStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_GetLivingProductStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_LiveingProductStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_LiveingProductStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_GetLivingProductStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_GetLivingProductStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_LiveRecordRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_LiveRecordRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_LiveRecordResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_LiveRecordResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_UpdateLiveProductIntroductStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_UpdateLiveProductIntroductStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_UpdateLiveProductIntroductStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_UpdateLiveProductIntroductStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_PreheatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_PreheatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_PreheatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_PreheatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_PublicPriceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_PublicPriceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_glory_api_PublicPriceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_glory_api_PublicPriceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024live/live_plan.proto\022\tglory_api\032\nbase." +
      "proto\"\225\001\n\010LivePlan\022\024\n\014live_plan_id\030\001 \001(\003" +
      "\022\026\n\016live_plan_name\030\002 \001(\t\022\023\n\013description\030" +
      "\003 \001(\t\022\017\n\007shop_id\030\004 \001(\003\0225\n\021live_plan_prod" +
      "uct\030\005 \003(\0132\032.glory_api.LivePlanProduct\"h\n" +
      "\025CreateLivePlanRequest\022\'\n\014base_request\030\001" +
      " \001(\0132\021.base.BaseRequest\022&\n\tlive_plan\030\002 \001" +
      "(\0132\023.glory_api.LivePlan\"U\n\026CreateLivePla" +
      "nResponse\022%\n\tbase_resp\030\001 \001(\0132\022.base.Base" +
      "Response\022\024\n\014live_plan_id\030\002 \001(\003\"\311\001\n\013PlanP" +
      "roduct\022\023\n\013product_url\030\001 \001(\t\022\024\n\014product_n" +
      "ame\030\002 \001(\t\022\020\n\010currency\030\003 \001(\t\022\022\n\nsale_pric" +
      "e\030\004 \001(\001\022\031\n\021product_remaining\030\005 \001(\003\022\022\n\npr" +
      "oduct_id\030\006 \001(\003\022\035\n\025product_selling_point\030" +
      "\007 \001(\t\022\033\n\023product_description\030\010 \001(\t\"S\n\022Ge" +
      "tLivePlanRequest\022\'\n\014base_request\030\001 \001(\0132\021" +
      ".base.BaseRequest\022\024\n\014live_plan_id\030\002 \001(\003\"" +
      "\227\001\n\023GetLivePlanResponse\022%\n\tbase_resp\030\001 \001" +
      "(\0132\022.base.BaseResponse\022&\n\tlive_plan\030\002 \001(" +
      "\0132\023.glory_api.LivePlan\0221\n\021live_plan_prod" +
      "uct\030\003 \003(\0132\026.glory_api.PlanProduct\"h\n\025Upd" +
      "ateLivePlanRequest\022\'\n\014base_request\030\001 \001(\013" +
      "2\021.base.BaseRequest\022&\n\tlive_plan\030\002 \001(\0132\023" +
      ".glory_api.LivePlan\"?\n\026UpdateLivePlanRes" +
      "ponse\022%\n\tbase_resp\030\001 \001(\0132\022.base.BaseResp" +
      "onse\"|\n\023ListLivePlanRequest\022\'\n\014base_requ" +
      "est\030\001 \001(\0132\021.base.BaseRequest\022\017\n\007shop_id\030" +
      "\002 \001(\003\022+\n\npagination\030d \001(\0132\027.base.Paginat" +
      "ionRequest\"\223\001\n\024ListLivePlanResponse\022%\n\tb" +
      "ase_resp\030\001 \001(\0132\022.base.BaseResponse\022&\n\tli" +
      "ve_plan\030\002 \003(\0132\023.glory_api.LivePlan\022,\n\npa" +
      "gination\030d \001(\0132\030.base.PaginationResponse" +
      "\"V\n\025DeleteLivePlanRequest\022\'\n\014base_reques" +
      "t\030\001 \001(\0132\021.base.BaseRequest\022\024\n\014live_plan_" +
      "id\030\002 \001(\003\"?\n\026DeleteLivePlanResponse\022%\n\tba" +
      "se_resp\030\001 \001(\0132\022.base.BaseResponse\"\225\001\n\017Li" +
      "vePlanProduct\022\034\n\024live_plan_product_id\030\001 " +
      "\001(\003\022\024\n\014live_plan_id\030\002 \001(\003\022\022\n\nproduct_id\030" +
      "\003 \001(\003\022\035\n\025product_selling_point\030\004 \001(\t\022\033\n\023" +
      "product_description\030\005 \001(\t\"~\n\034CreateLiveP" +
      "lanProductRequest\022\'\n\014base_request\030\001 \001(\0132" +
      "\021.base.BaseRequest\0225\n\021live_plan_product\030" +
      "\002 \001(\0132\032.glory_api.LivePlanProduct\"d\n\035Cre" +
      "ateLivePlanProductResponse\022%\n\tbase_resp\030" +
      "\001 \001(\0132\022.base.BaseResponse\022\034\n\024live_plan_p" +
      "roduct_id\030\002 \001(\003\"\241\001\n\034UpdateLivePlanProduc" +
      "tRequest\022\'\n\014base_request\030\001 \001(\0132\021.base.Ba" +
      "seRequest\022\034\n\024live_plan_product_id\030\002 \001(\003\022" +
      "\035\n\025product_selling_point\030\003 \001(\t\022\033\n\023produc" +
      "t_description\030\004 \001(\t\"F\n\035UpdateLivePlanPro" +
      "ductResponse\022%\n\tbase_resp\030\001 \001(\0132\022.base.B" +
      "aseResponse\"\210\001\n\032ListLivePlanProductReque" +
      "st\022\'\n\014base_request\030\001 \001(\0132\021.base.BaseRequ" +
      "est\022\024\n\014live_plan_id\030\002 \001(\003\022+\n\npagination\030" +
      "d \001(\0132\027.base.PaginationRequest\"\251\001\n\033ListL" +
      "ivePlanProductResponse\022%\n\tbase_resp\030\001 \001(" +
      "\0132\022.base.BaseResponse\0225\n\021live_plan_produ" +
      "ct\030\002 \003(\0132\032.glory_api.LivePlanProduct\022,\n\n" +
      "pagination\030d \001(\0132\030.base.PaginationRespon" +
      "se\"e\n\034DeleteLivePlanProductRequest\022\'\n\014ba" +
      "se_request\030\001 \001(\0132\021.base.BaseRequest\022\034\n\024l" +
      "ive_plan_product_id\030\002 \001(\003\"F\n\035DeleteLiveP" +
      "lanProductResponse\022%\n\tbase_resp\030\001 \001(\0132\022." +
      "base.BaseResponse\"\200\001\n\032LoadLivePlanProduc" +
      "tRequest\022\'\n\014base_request\030\001 \001(\0132\021.base.Ba" +
      "seRequest\022\017\n\007shop_id\030\002 \001(\003\022\024\n\014live_plan_" +
      "id\030\003 \001(\003\022\022\n\nis_playing\030\004 \001(\010\"D\n\033LoadLive" +
      "PlanProductResponse\022%\n\tbase_resp\030\001 \001(\0132\022" +
      ".base.BaseResponse\"i\n\027CreateLiveProductS" +
      "tatus\022\022\n\nproduct_id\030\001 \001(\003\022\035\n\025product_sel" +
      "ling_point\030\002 \001(\t\022\033\n\023product_description\030" +
      "\003 \001(\t\"\233\001\n\036CreateLiveProductStatusRequest" +
      "\022\'\n\014base_request\030\001 \001(\0132\021.base.BaseReques" +
      "t\022\017\n\007shop_id\030\002 \001(\003\022?\n\023live_product_statu" +
      "s\030\003 \003(\0132\".glory_api.CreateLiveProductSta" +
      "tus\"H\n\037CreateLiveProductStatusResponse\022%" +
      "\n\tbase_resp\030\001 \001(\0132\022.base.BaseResponse\"\265\001" +
      "\n\036UpdateLiveProductStatusRequest\022\'\n\014base" +
      "_request\030\001 \001(\0132\021.base.BaseRequest\022\036\n\026liv" +
      "e_product_status_id\030\002 \003(\003\022\016\n\006status\030\003 \001(" +
      "\t\022\035\n\025product_selling_point\030\004 \001(\t\022\033\n\023prod" +
      "uct_description\030\005 \001(\t\"H\n\037UpdateLiveProdu" +
      "ctStatusResponse\022%\n\tbase_resp\030\001 \001(\0132\022.ba" +
      "se.BaseResponse\"\262\003\n\021LiveProductStatus\022\036\n" +
      "\026live_product_status_id\030\001 \001(\003\022\022\n\nproduct" +
      "_id\030\002 \001(\003\022\016\n\006status\030\003 \001(\t\022\017\n\007shop_id\030\004 \001" +
      "(\003\022\017\n\007room_id\030\005 \001(\003\022\035\n\025product_selling_p" +
      "oint\030\006 \001(\t\022\033\n\023product_description\030\007 \001(\t\022" +
      "\024\n\014is_introduct\030\010 \001(\010\022\r\n\005state\030\t \001(\t\022\023\n\013" +
      "product_url\030\n \001(\t\022\024\n\014product_name\030\013 \001(\t\022" +
      "\025\n\rproduct_price\030\014 \001(\001\022 \n\030product_remain" +
      "ing_amount\030\r \001(\003\022\033\n\023product_sold_amount\030" +
      "\016 \001(\003\022\033\n\023product_deal_amount\030\017 \001(\001\022\027\n\017ac" +
      "tivity_status\030\020 \001(\t\022\037\n\027product_reference" +
      "_price\030\021 \001(\001\"\225\001\n\034ListLiveProductStatusRe" +
      "quest\022\'\n\014base_request\030\001 \001(\0132\021.base.BaseR" +
      "equest\022\017\n\007shop_id\030\002 \001(\003\022\016\n\006status\030\003 \001(\t\022" +
      "+\n\npagination\030d \001(\0132\027.base.PaginationReq" +
      "uest\"\257\001\n\035ListLiveProductStatusResponse\022%" +
      "\n\tbase_resp\030\001 \001(\0132\022.base.BaseResponse\0229\n" +
      "\023live_product_status\030\002 \003(\0132\034.glory_api.L" +
      "iveProductStatus\022,\n\npagination\030d \001(\0132\030.b" +
      "ase.PaginationResponse\"i\n\036DeleteLiveProd" +
      "uctStatusRequest\022\'\n\014base_request\030\001 \001(\0132\021" +
      ".base.BaseRequest\022\036\n\026live_product_status" +
      "_id\030\002 \001(\003\"H\n\037DeleteLiveProductStatusResp" +
      "onse\022%\n\tbase_resp\030\001 \001(\0132\022.base.BaseRespo" +
      "nse\"Y\n\035GetLivingProductStatusRequest\022\'\n\014" +
      "base_request\030\001 \001(\0132\021.base.BaseRequest\022\017\n" +
      "\007shop_id\030\002 \001(\003\"\314\001\n\024LiveingProductStatus\022" +
      "\022\n\nproduct_id\030\002 \001(\003\022\024\n\014product_name\030\003 \001(" +
      "\t\022\025\n\rproduct_price\030\004 \001(\001\022\025\n\rproduct_coun" +
      "t\030\005 \001(\005\022\027\n\017live_room_order\030\006 \001(\005\022\021\n\tplay" +
      "ed_at\030\007 \001(\t\022\033\n\023product_description\030\010 \001(\t" +
      "\022\023\n\013product_url\030\t \001(\t\"\210\001\n\036GetLivingProdu" +
      "ctStatusResponse\022%\n\tbase_resp\030\001 \001(\0132\022.ba" +
      "se.BaseResponse\022?\n\026liveing_product_statu" +
      "s\030\002 \001(\0132\037.glory_api.LiveingProductStatus" +
      "\"s\n\021LiveRecordRequest\022\'\n\014base_request\030\001 " +
      "\001(\0132\021.base.BaseRequest\022\016\n\006action\030\002 \001(\t\022\020" +
      "\n\010app_name\030\003 \001(\t\022\023\n\013stream_name\030\004 \001(\t\";\n" +
      "\022LiveRecordResponse\022%\n\tbase_resp\030\001 \001(\0132\022" +
      ".base.BaseResponse\"\223\001\n\'UpdateLiveProduct" +
      "IntroductStatusRequest\022\'\n\014base_request\030\001" +
      " \001(\0132\021.base.BaseRequest\022\017\n\007shop_id\030\002 \001(\003" +
      "\022\036\n\026live_product_status_id\030\003 \001(\003\022\016\n\006acti" +
      "on\030\004 \001(\t\"Q\n(UpdateLiveProductIntroductSt" +
      "atusResponse\022%\n\tbase_resp\030\001 \001(\0132\022.base.B" +
      "aseResponse\"f\n\016PreheatRequest\022\'\n\014base_re" +
      "quest\030\001 \001(\0132\021.base.BaseRequest\022\022\n\nproduc" +
      "t_id\030\002 \001(\003\022\027\n\017reference_price\030\003 \001(\001\"8\n\017P" +
      "reheatResponse\022%\n\tbase_resp\030\001 \001(\0132\022.base" +
      ".BaseResponse\"Q\n\022PublicPriceRequest\022\'\n\014b" +
      "ase_request\030\001 \001(\0132\021.base.BaseRequest\022\022\n\n" +
      "product_id\030\002 \001(\003\"<\n\023PublicPriceResponse\022" +
      "%\n\tbase_resp\030\001 \001(\0132\022.base.BaseResponseB#" +
      "\n\037com.zhijiejiaoyu.glory_api.liveP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.zhijiejiaoyu.base.Base.getDescriptor(),
        });
    internal_static_glory_api_LivePlan_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_glory_api_LivePlan_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_LivePlan_descriptor,
        new java.lang.String[] { "LivePlanId", "LivePlanName", "Description", "ShopId", "LivePlanProduct", });
    internal_static_glory_api_CreateLivePlanRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_glory_api_CreateLivePlanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_CreateLivePlanRequest_descriptor,
        new java.lang.String[] { "BaseRequest", "LivePlan", });
    internal_static_glory_api_CreateLivePlanResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_glory_api_CreateLivePlanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_CreateLivePlanResponse_descriptor,
        new java.lang.String[] { "BaseResp", "LivePlanId", });
    internal_static_glory_api_PlanProduct_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_glory_api_PlanProduct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_PlanProduct_descriptor,
        new java.lang.String[] { "ProductUrl", "ProductName", "Currency", "SalePrice", "ProductRemaining", "ProductId", "ProductSellingPoint", "ProductDescription", });
    internal_static_glory_api_GetLivePlanRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_glory_api_GetLivePlanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_GetLivePlanRequest_descriptor,
        new java.lang.String[] { "BaseRequest", "LivePlanId", });
    internal_static_glory_api_GetLivePlanResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_glory_api_GetLivePlanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_GetLivePlanResponse_descriptor,
        new java.lang.String[] { "BaseResp", "LivePlan", "LivePlanProduct", });
    internal_static_glory_api_UpdateLivePlanRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_glory_api_UpdateLivePlanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_UpdateLivePlanRequest_descriptor,
        new java.lang.String[] { "BaseRequest", "LivePlan", });
    internal_static_glory_api_UpdateLivePlanResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_glory_api_UpdateLivePlanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_UpdateLivePlanResponse_descriptor,
        new java.lang.String[] { "BaseResp", });
    internal_static_glory_api_ListLivePlanRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_glory_api_ListLivePlanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_ListLivePlanRequest_descriptor,
        new java.lang.String[] { "BaseRequest", "ShopId", "Pagination", });
    internal_static_glory_api_ListLivePlanResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_glory_api_ListLivePlanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_ListLivePlanResponse_descriptor,
        new java.lang.String[] { "BaseResp", "LivePlan", "Pagination", });
    internal_static_glory_api_DeleteLivePlanRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_glory_api_DeleteLivePlanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_DeleteLivePlanRequest_descriptor,
        new java.lang.String[] { "BaseRequest", "LivePlanId", });
    internal_static_glory_api_DeleteLivePlanResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_glory_api_DeleteLivePlanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_DeleteLivePlanResponse_descriptor,
        new java.lang.String[] { "BaseResp", });
    internal_static_glory_api_LivePlanProduct_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_glory_api_LivePlanProduct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_LivePlanProduct_descriptor,
        new java.lang.String[] { "LivePlanProductId", "LivePlanId", "ProductId", "ProductSellingPoint", "ProductDescription", });
    internal_static_glory_api_CreateLivePlanProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_glory_api_CreateLivePlanProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_CreateLivePlanProductRequest_descriptor,
        new java.lang.String[] { "BaseRequest", "LivePlanProduct", });
    internal_static_glory_api_CreateLivePlanProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_glory_api_CreateLivePlanProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_CreateLivePlanProductResponse_descriptor,
        new java.lang.String[] { "BaseResp", "LivePlanProductId", });
    internal_static_glory_api_UpdateLivePlanProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_glory_api_UpdateLivePlanProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_UpdateLivePlanProductRequest_descriptor,
        new java.lang.String[] { "BaseRequest", "LivePlanProductId", "ProductSellingPoint", "ProductDescription", });
    internal_static_glory_api_UpdateLivePlanProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_glory_api_UpdateLivePlanProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_UpdateLivePlanProductResponse_descriptor,
        new java.lang.String[] { "BaseResp", });
    internal_static_glory_api_ListLivePlanProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_glory_api_ListLivePlanProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_ListLivePlanProductRequest_descriptor,
        new java.lang.String[] { "BaseRequest", "LivePlanId", "Pagination", });
    internal_static_glory_api_ListLivePlanProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_glory_api_ListLivePlanProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_ListLivePlanProductResponse_descriptor,
        new java.lang.String[] { "BaseResp", "LivePlanProduct", "Pagination", });
    internal_static_glory_api_DeleteLivePlanProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_glory_api_DeleteLivePlanProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_DeleteLivePlanProductRequest_descriptor,
        new java.lang.String[] { "BaseRequest", "LivePlanProductId", });
    internal_static_glory_api_DeleteLivePlanProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_glory_api_DeleteLivePlanProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_DeleteLivePlanProductResponse_descriptor,
        new java.lang.String[] { "BaseResp", });
    internal_static_glory_api_LoadLivePlanProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_glory_api_LoadLivePlanProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_LoadLivePlanProductRequest_descriptor,
        new java.lang.String[] { "BaseRequest", "ShopId", "LivePlanId", "IsPlaying", });
    internal_static_glory_api_LoadLivePlanProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_glory_api_LoadLivePlanProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_LoadLivePlanProductResponse_descriptor,
        new java.lang.String[] { "BaseResp", });
    internal_static_glory_api_CreateLiveProductStatus_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_glory_api_CreateLiveProductStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_CreateLiveProductStatus_descriptor,
        new java.lang.String[] { "ProductId", "ProductSellingPoint", "ProductDescription", });
    internal_static_glory_api_CreateLiveProductStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_glory_api_CreateLiveProductStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_CreateLiveProductStatusRequest_descriptor,
        new java.lang.String[] { "BaseRequest", "ShopId", "LiveProductStatus", });
    internal_static_glory_api_CreateLiveProductStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_glory_api_CreateLiveProductStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_CreateLiveProductStatusResponse_descriptor,
        new java.lang.String[] { "BaseResp", });
    internal_static_glory_api_UpdateLiveProductStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_glory_api_UpdateLiveProductStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_UpdateLiveProductStatusRequest_descriptor,
        new java.lang.String[] { "BaseRequest", "LiveProductStatusId", "Status", "ProductSellingPoint", "ProductDescription", });
    internal_static_glory_api_UpdateLiveProductStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_glory_api_UpdateLiveProductStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_UpdateLiveProductStatusResponse_descriptor,
        new java.lang.String[] { "BaseResp", });
    internal_static_glory_api_LiveProductStatus_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_glory_api_LiveProductStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_LiveProductStatus_descriptor,
        new java.lang.String[] { "LiveProductStatusId", "ProductId", "Status", "ShopId", "RoomId", "ProductSellingPoint", "ProductDescription", "IsIntroduct", "State", "ProductUrl", "ProductName", "ProductPrice", "ProductRemainingAmount", "ProductSoldAmount", "ProductDealAmount", "ActivityStatus", "ProductReferencePrice", });
    internal_static_glory_api_ListLiveProductStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_glory_api_ListLiveProductStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_ListLiveProductStatusRequest_descriptor,
        new java.lang.String[] { "BaseRequest", "ShopId", "Status", "Pagination", });
    internal_static_glory_api_ListLiveProductStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_glory_api_ListLiveProductStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_ListLiveProductStatusResponse_descriptor,
        new java.lang.String[] { "BaseResp", "LiveProductStatus", "Pagination", });
    internal_static_glory_api_DeleteLiveProductStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_glory_api_DeleteLiveProductStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_DeleteLiveProductStatusRequest_descriptor,
        new java.lang.String[] { "BaseRequest", "LiveProductStatusId", });
    internal_static_glory_api_DeleteLiveProductStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_glory_api_DeleteLiveProductStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_DeleteLiveProductStatusResponse_descriptor,
        new java.lang.String[] { "BaseResp", });
    internal_static_glory_api_GetLivingProductStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_glory_api_GetLivingProductStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_GetLivingProductStatusRequest_descriptor,
        new java.lang.String[] { "BaseRequest", "ShopId", });
    internal_static_glory_api_LiveingProductStatus_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_glory_api_LiveingProductStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_LiveingProductStatus_descriptor,
        new java.lang.String[] { "ProductId", "ProductName", "ProductPrice", "ProductCount", "LiveRoomOrder", "PlayedAt", "ProductDescription", "ProductUrl", });
    internal_static_glory_api_GetLivingProductStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_glory_api_GetLivingProductStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_GetLivingProductStatusResponse_descriptor,
        new java.lang.String[] { "BaseResp", "LiveingProductStatus", });
    internal_static_glory_api_LiveRecordRequest_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_glory_api_LiveRecordRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_LiveRecordRequest_descriptor,
        new java.lang.String[] { "BaseRequest", "Action", "AppName", "StreamName", });
    internal_static_glory_api_LiveRecordResponse_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_glory_api_LiveRecordResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_LiveRecordResponse_descriptor,
        new java.lang.String[] { "BaseResp", });
    internal_static_glory_api_UpdateLiveProductIntroductStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_glory_api_UpdateLiveProductIntroductStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_UpdateLiveProductIntroductStatusRequest_descriptor,
        new java.lang.String[] { "BaseRequest", "ShopId", "LiveProductStatusId", "Action", });
    internal_static_glory_api_UpdateLiveProductIntroductStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_glory_api_UpdateLiveProductIntroductStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_UpdateLiveProductIntroductStatusResponse_descriptor,
        new java.lang.String[] { "BaseResp", });
    internal_static_glory_api_PreheatRequest_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_glory_api_PreheatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_PreheatRequest_descriptor,
        new java.lang.String[] { "BaseRequest", "ProductId", "ReferencePrice", });
    internal_static_glory_api_PreheatResponse_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_glory_api_PreheatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_PreheatResponse_descriptor,
        new java.lang.String[] { "BaseResp", });
    internal_static_glory_api_PublicPriceRequest_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_glory_api_PublicPriceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_PublicPriceRequest_descriptor,
        new java.lang.String[] { "BaseRequest", "ProductId", });
    internal_static_glory_api_PublicPriceResponse_descriptor =
      getDescriptor().getMessageTypes().get(43);
    internal_static_glory_api_PublicPriceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_glory_api_PublicPriceResponse_descriptor,
        new java.lang.String[] { "BaseResp", });
    com.zhijiejiaoyu.base.Base.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
