// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live/live_quick_evaluate.proto

package com.zhijiejiaoyu.glory_api.live;

public interface QuickEvaluationDetailKeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:glory_api.QuickEvaluationDetailKey)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string desc = 3;</code>
   * @return The desc.
   */
  java.lang.String getDesc();
  /**
   * <code>string desc = 3;</code>
   * @return The bytes for desc.
   */
  com.google.protobuf.ByteString
      getDescBytes();

  /**
   * <code>bool result = 4;</code>
   * @return The result.
   */
  boolean getResult();

  /**
   * <code>repeated .glory_api.QuickEvaluationDetail detail = 5;</code>
   */
  java.util.List<com.zhijiejiaoyu.glory_api.live.QuickEvaluationDetail> 
      getDetailList();
  /**
   * <code>repeated .glory_api.QuickEvaluationDetail detail = 5;</code>
   */
  com.zhijiejiaoyu.glory_api.live.QuickEvaluationDetail getDetail(int index);
  /**
   * <code>repeated .glory_api.QuickEvaluationDetail detail = 5;</code>
   */
  int getDetailCount();
  /**
   * <code>repeated .glory_api.QuickEvaluationDetail detail = 5;</code>
   */
  java.util.List<? extends com.zhijiejiaoyu.glory_api.live.QuickEvaluationDetailOrBuilder> 
      getDetailOrBuilderList();
  /**
   * <code>repeated .glory_api.QuickEvaluationDetail detail = 5;</code>
   */
  com.zhijiejiaoyu.glory_api.live.QuickEvaluationDetailOrBuilder getDetailOrBuilder(
      int index);
}
