// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_article/article.proto

package com.zhijiejiaoyu.glory_api.short_video;

public interface ChatMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:glory_api.ChatMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string content = 1;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 1;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>string role = 2;</code>
   * @return The role.
   */
  java.lang.String getRole();
  /**
   * <code>string role = 2;</code>
   * @return The bytes for role.
   */
  com.google.protobuf.ByteString
      getRoleBytes();
}
