// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_article/article.proto

package com.zhijiejiaoyu.glory_api.short_video;

/**
 * Protobuf type {@code glory_api.GetArticleCreationTenant}
 */
public final class GetArticleCreationTenant extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:glory_api.GetArticleCreationTenant)
    GetArticleCreationTenantOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetArticleCreationTenant.newBuilder() to construct.
  private GetArticleCreationTenant(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetArticleCreationTenant() {
    name = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetArticleCreationTenant();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetArticleCreationTenant(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name = s;
            break;
          }
          case 16: {

            studentCount = input.readInt64();
            break;
          }
          case 24: {

            courseCount = input.readInt64();
            break;
          }
          case 32: {

            dayCourseCount = input.readInt64();
            break;
          }
          case 40: {

            evaluationCount = input.readInt64();
            break;
          }
          case 48: {

            evaluationDayCount = input.readInt64();
            break;
          }
          case 56: {

            assistantCount = input.readInt64();
            break;
          }
          case 64: {

            assistantDayCount = input.readInt64();
            break;
          }
          case 72: {

            total = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zhijiejiaoyu.glory_api.short_video.Article.internal_static_glory_api_GetArticleCreationTenant_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zhijiejiaoyu.glory_api.short_video.Article.internal_static_glory_api_GetArticleCreationTenant_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant.class, com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name ;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name ;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name ;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STUDENT_COUNT_FIELD_NUMBER = 2;
  private long studentCount ;
  /**
   * <code>int64 student_count = 2;</code>
   * @return The studentCount.
   */
  @java.lang.Override
  public long getStudentCount() {
    return studentCount ;
  }

  public static final int COURSE_COUNT_FIELD_NUMBER = 3;
  private long courseCount ;
  /**
   * <code>int64 course_count = 3;</code>
   * @return The courseCount.
   */
  @java.lang.Override
  public long getCourseCount() {
    return courseCount ;
  }

  public static final int DAY_COURSE_COUNT_FIELD_NUMBER = 4;
  private long dayCourseCount ;
  /**
   * <code>int64 day_course_count = 4;</code>
   * @return The dayCourseCount.
   */
  @java.lang.Override
  public long getDayCourseCount() {
    return dayCourseCount ;
  }

  public static final int EVALUATION_COUNT_FIELD_NUMBER = 5;
  private long evaluationCount ;
  /**
   * <code>int64 evaluation_count = 5;</code>
   * @return The evaluationCount.
   */
  @java.lang.Override
  public long getEvaluationCount() {
    return evaluationCount ;
  }

  public static final int EVALUATION_DAY_COUNT_FIELD_NUMBER = 6;
  private long evaluationDayCount ;
  /**
   * <code>int64 evaluation_day_count = 6;</code>
   * @return The evaluationDayCount.
   */
  @java.lang.Override
  public long getEvaluationDayCount() {
    return evaluationDayCount ;
  }

  public static final int ASSISTANT_COUNT_FIELD_NUMBER = 7;
  private long assistantCount ;
  /**
   * <code>int64 assistant_count = 7;</code>
   * @return The assistantCount.
   */
  @java.lang.Override
  public long getAssistantCount() {
    return assistantCount ;
  }

  public static final int ASSISTANT_DAY_COUNT_FIELD_NUMBER = 8;
  private long assistantDayCount ;
  /**
   * <code>int64 assistant_day_count = 8;</code>
   * @return The assistantDayCount.
   */
  @java.lang.Override
  public long getAssistantDayCount() {
    return assistantDayCount ;
  }

  public static final int TOTAL_FIELD_NUMBER = 9;
  private long total ;
  /**
   * <code>int64 total = 9;</code>
   * @return The total.
   */
  @java.lang.Override
  public long getTotal() {
    return total ;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name );
    }
    if (studentCount != 0L) {
      output.writeInt64(2, studentCount );
    }
    if (courseCount != 0L) {
      output.writeInt64(3, courseCount );
    }
    if (dayCourseCount != 0L) {
      output.writeInt64(4, dayCourseCount );
    }
    if (evaluationCount != 0L) {
      output.writeInt64(5, evaluationCount );
    }
    if (evaluationDayCount != 0L) {
      output.writeInt64(6, evaluationDayCount );
    }
    if (assistantCount != 0L) {
      output.writeInt64(7, assistantCount );
    }
    if (assistantDayCount != 0L) {
      output.writeInt64(8, assistantDayCount );
    }
    if (total != 0L) {
      output.writeInt64(9, total );
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name );
    }
    if (studentCount != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, studentCount );
    }
    if (courseCount != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, courseCount );
    }
    if (dayCourseCount != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, dayCourseCount );
    }
    if (evaluationCount != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, evaluationCount );
    }
    if (evaluationDayCount != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, evaluationDayCount );
    }
    if (assistantCount != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, assistantCount );
    }
    if (assistantDayCount != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, assistantDayCount );
    }
    if (total != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, total );
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant)) {
      return super.equals(obj);
    }
    com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant other = (com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (getStudentCount()
        != other.getStudentCount()) return false;
    if (getCourseCount()
        != other.getCourseCount()) return false;
    if (getDayCourseCount()
        != other.getDayCourseCount()) return false;
    if (getEvaluationCount()
        != other.getEvaluationCount()) return false;
    if (getEvaluationDayCount()
        != other.getEvaluationDayCount()) return false;
    if (getAssistantCount()
        != other.getAssistantCount()) return false;
    if (getAssistantDayCount()
        != other.getAssistantDayCount()) return false;
    if (getTotal()
        != other.getTotal()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + STUDENT_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStudentCount());
    hash = (37 * hash) + COURSE_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCourseCount());
    hash = (37 * hash) + DAY_COURSE_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDayCourseCount());
    hash = (37 * hash) + EVALUATION_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEvaluationCount());
    hash = (37 * hash) + EVALUATION_DAY_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEvaluationDayCount());
    hash = (37 * hash) + ASSISTANT_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAssistantCount());
    hash = (37 * hash) + ASSISTANT_DAY_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAssistantDayCount());
    hash = (37 * hash) + TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotal());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code glory_api.GetArticleCreationTenant}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:glory_api.GetArticleCreationTenant)
      com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenantOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhijiejiaoyu.glory_api.short_video.Article.internal_static_glory_api_GetArticleCreationTenant_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhijiejiaoyu.glory_api.short_video.Article.internal_static_glory_api_GetArticleCreationTenant_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant.class, com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant.Builder.class);
    }

    // Construct using com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name = "";

      studentCount = 0L;

      courseCount = 0L;

      dayCourseCount = 0L;

      evaluationCount = 0L;

      evaluationDayCount = 0L;

      assistantCount = 0L;

      assistantDayCount = 0L;

      total = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zhijiejiaoyu.glory_api.short_video.Article.internal_static_glory_api_GetArticleCreationTenant_descriptor;
    }

    @java.lang.Override
    public com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant getDefaultInstanceForType() {
      return com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant.getDefaultInstance();
    }

    @java.lang.Override
    public com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant build() {
      com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant buildPartial() {
      com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant result = new com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant(this);
      result.name = name ;
      result.studentCount = studentCount ;
      result.courseCount = courseCount ;
      result.dayCourseCount = dayCourseCount ;
      result.evaluationCount = evaluationCount ;
      result.evaluationDayCount = evaluationDayCount ;
      result.assistantCount = assistantCount ;
      result.assistantDayCount = assistantDayCount ;
      result.total = total ;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant) {
        return mergeFrom((com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant other) {
      if (other == com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name = other.name ;
        onChanged();
      }
      if (other.getStudentCount() != 0L) {
        setStudentCount(other.getStudentCount());
      }
      if (other.getCourseCount() != 0L) {
        setCourseCount(other.getCourseCount());
      }
      if (other.getDayCourseCount() != 0L) {
        setDayCourseCount(other.getDayCourseCount());
      }
      if (other.getEvaluationCount() != 0L) {
        setEvaluationCount(other.getEvaluationCount());
      }
      if (other.getEvaluationDayCount() != 0L) {
        setEvaluationDayCount(other.getEvaluationDayCount());
      }
      if (other.getAssistantCount() != 0L) {
        setAssistantCount(other.getAssistantCount());
      }
      if (other.getAssistantDayCount() != 0L) {
        setAssistantDayCount(other.getAssistantDayCount());
      }
      if (other.getTotal() != 0L) {
        setTotal(other.getTotal());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object name = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name ;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name ;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name = value;
      onChanged();
      return this;
    }

    private long studentCount ;
    /**
     * <code>int64 student_count = 2;</code>
     * @return The studentCount.
     */
    @java.lang.Override
    public long getStudentCount() {
      return studentCount ;
    }
    /**
     * <code>int64 student_count = 2;</code>
     * @param value The studentCount to set.
     * @return This builder for chaining.
     */
    public Builder setStudentCount(long value) {
      
      studentCount = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 student_count = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStudentCount() {
      
      studentCount = 0L;
      onChanged();
      return this;
    }

    private long courseCount ;
    /**
     * <code>int64 course_count = 3;</code>
     * @return The courseCount.
     */
    @java.lang.Override
    public long getCourseCount() {
      return courseCount ;
    }
    /**
     * <code>int64 course_count = 3;</code>
     * @param value The courseCount to set.
     * @return This builder for chaining.
     */
    public Builder setCourseCount(long value) {
      
      courseCount = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 course_count = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCourseCount() {
      
      courseCount = 0L;
      onChanged();
      return this;
    }

    private long dayCourseCount ;
    /**
     * <code>int64 day_course_count = 4;</code>
     * @return The dayCourseCount.
     */
    @java.lang.Override
    public long getDayCourseCount() {
      return dayCourseCount ;
    }
    /**
     * <code>int64 day_course_count = 4;</code>
     * @param value The dayCourseCount to set.
     * @return This builder for chaining.
     */
    public Builder setDayCourseCount(long value) {
      
      dayCourseCount = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 day_course_count = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDayCourseCount() {
      
      dayCourseCount = 0L;
      onChanged();
      return this;
    }

    private long evaluationCount ;
    /**
     * <code>int64 evaluation_count = 5;</code>
     * @return The evaluationCount.
     */
    @java.lang.Override
    public long getEvaluationCount() {
      return evaluationCount ;
    }
    /**
     * <code>int64 evaluation_count = 5;</code>
     * @param value The evaluationCount to set.
     * @return This builder for chaining.
     */
    public Builder setEvaluationCount(long value) {
      
      evaluationCount = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 evaluation_count = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEvaluationCount() {
      
      evaluationCount = 0L;
      onChanged();
      return this;
    }

    private long evaluationDayCount ;
    /**
     * <code>int64 evaluation_day_count = 6;</code>
     * @return The evaluationDayCount.
     */
    @java.lang.Override
    public long getEvaluationDayCount() {
      return evaluationDayCount ;
    }
    /**
     * <code>int64 evaluation_day_count = 6;</code>
     * @param value The evaluationDayCount to set.
     * @return This builder for chaining.
     */
    public Builder setEvaluationDayCount(long value) {
      
      evaluationDayCount = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 evaluation_day_count = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearEvaluationDayCount() {
      
      evaluationDayCount = 0L;
      onChanged();
      return this;
    }

    private long assistantCount ;
    /**
     * <code>int64 assistant_count = 7;</code>
     * @return The assistantCount.
     */
    @java.lang.Override
    public long getAssistantCount() {
      return assistantCount ;
    }
    /**
     * <code>int64 assistant_count = 7;</code>
     * @param value The assistantCount to set.
     * @return This builder for chaining.
     */
    public Builder setAssistantCount(long value) {
      
      assistantCount = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 assistant_count = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearAssistantCount() {
      
      assistantCount = 0L;
      onChanged();
      return this;
    }

    private long assistantDayCount ;
    /**
     * <code>int64 assistant_day_count = 8;</code>
     * @return The assistantDayCount.
     */
    @java.lang.Override
    public long getAssistantDayCount() {
      return assistantDayCount ;
    }
    /**
     * <code>int64 assistant_day_count = 8;</code>
     * @param value The assistantDayCount to set.
     * @return This builder for chaining.
     */
    public Builder setAssistantDayCount(long value) {
      
      assistantDayCount = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 assistant_day_count = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearAssistantDayCount() {
      
      assistantDayCount = 0L;
      onChanged();
      return this;
    }

    private long total ;
    /**
     * <code>int64 total = 9;</code>
     * @return The total.
     */
    @java.lang.Override
    public long getTotal() {
      return total ;
    }
    /**
     * <code>int64 total = 9;</code>
     * @param value The total to set.
     * @return This builder for chaining.
     */
    public Builder setTotal(long value) {
      
      total = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 total = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotal() {
      
      total = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:glory_api.GetArticleCreationTenant)
  }

  // @@protoc_insertion_point(class_scope:glory_api.GetArticleCreationTenant)
  private static final com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant();
  }

  public static com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetArticleCreationTenant>
      PARSER = new com.google.protobuf.AbstractParser<GetArticleCreationTenant>() {
    @java.lang.Override
    public GetArticleCreationTenant parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetArticleCreationTenant(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetArticleCreationTenant> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetArticleCreationTenant> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.zhijiejiaoyu.glory_api.short_video.GetArticleCreationTenant getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

