// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_article/article.proto

package com.zhijiejiaoyu.glory_api.short_video;

/**
 * Protobuf type {@code glory_api.ListDigitalCodeResponse}
 */
public final class ListDigitalCodeResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:glory_api.ListDigitalCodeResponse)
    ListDigitalCodeResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListDigitalCodeResponse.newBuilder() to construct.
  private ListDigitalCodeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListDigitalCodeResponse() {
    r2D = java.util.Collections.emptyList();
    r3D = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListDigitalCodeResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListDigitalCodeResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0 = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.zhijiejiaoyu.base.BaseResponse.Builder subBuilder = null;
            if (baseResp != null) {
              subBuilder = baseResp .toBuilder();
            }
            baseResp = input.readMessage(com.zhijiejiaoyu.base.BaseResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(baseResp );
              baseResp = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0 & 0x00000001) != 0)) {
              r2D = new java.util.ArrayList<com.zhijiejiaoyu.glory_api.short_video.DigitalCode>();
              mutable_bitField0_ |= 0x00000001;
            }
            r2D .add(
                input.readMessage(com.zhijiejiaoyu.glory_api.short_video.DigitalCode.parser(), extensionRegistry));
            break;
          }
          case 26: {
            if (!((mutable_bitField0 & 0x00000002) != 0)) {
              r3D = new java.util.ArrayList<com.zhijiejiaoyu.glory_api.short_video.DigitalCode>();
              mutable_bitField0_ |= 0x00000002;
            }
            r3D .add(
                input.readMessage(com.zhijiejiaoyu.glory_api.short_video.DigitalCode.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0 & 0x00000001) != 0)) {
        r2D = java.util.Collections.unmodifiableList(r2D );
      }
      if (((mutable_bitField0 & 0x00000002) != 0)) {
        r3D = java.util.Collections.unmodifiableList(r3D );
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.zhijiejiaoyu.glory_api.short_video.Article.internal_static_glory_api_ListDigitalCodeResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.zhijiejiaoyu.glory_api.short_video.Article.internal_static_glory_api_ListDigitalCodeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse.class, com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse.Builder.class);
  }

  public static final int BASE_RESP_FIELD_NUMBER = 1;
  private com.zhijiejiaoyu.base.BaseResponse baseResp ;
  /**
   * <code>.base.BaseResponse base_resp = 1;</code>
   * @return Whether the baseResp field is set.
   */
  @java.lang.Override
  public boolean hasBaseResp() {
    return baseResp != null;
  }
  /**
   * <code>.base.BaseResponse base_resp = 1;</code>
   * @return The baseResp.
   */
  @java.lang.Override
  public com.zhijiejiaoyu.base.BaseResponse getBaseResp() {
    return baseResp == null ? com.zhijiejiaoyu.base.BaseResponse.getDefaultInstance() : baseResp ;
  }
  /**
   * <code>.base.BaseResponse base_resp = 1;</code>
   */
  @java.lang.Override
  public com.zhijiejiaoyu.base.BaseResponseOrBuilder getBaseRespOrBuilder() {
    return getBaseResp();
  }

  public static final int R2D_FIELD_NUMBER = 2;
  private java.util.List<com.zhijiejiaoyu.glory_api.short_video.DigitalCode> r2D ;
  /**
   * <code>repeated .glory_api.DigitalCode r2d = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.zhijiejiaoyu.glory_api.short_video.DigitalCode> getR2DList() {
    return r2D ;
  }
  /**
   * <code>repeated .glory_api.DigitalCode r2d = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.zhijiejiaoyu.glory_api.short_video.DigitalCodeOrBuilder> 
      getR2DOrBuilderList() {
    return r2D ;
  }
  /**
   * <code>repeated .glory_api.DigitalCode r2d = 2;</code>
   */
  @java.lang.Override
  public int getR2DCount() {
    return r2D .size();
  }
  /**
   * <code>repeated .glory_api.DigitalCode r2d = 2;</code>
   */
  @java.lang.Override
  public com.zhijiejiaoyu.glory_api.short_video.DigitalCode getR2D(int index) {
    return r2D .get(index);
  }
  /**
   * <code>repeated .glory_api.DigitalCode r2d = 2;</code>
   */
  @java.lang.Override
  public com.zhijiejiaoyu.glory_api.short_video.DigitalCodeOrBuilder getR2DOrBuilder(
      int index) {
    return r2D .get(index);
  }

  public static final int R3D_FIELD_NUMBER = 3;
  private java.util.List<com.zhijiejiaoyu.glory_api.short_video.DigitalCode> r3D ;
  /**
   * <code>repeated .glory_api.DigitalCode r3d = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.zhijiejiaoyu.glory_api.short_video.DigitalCode> getR3DList() {
    return r3D ;
  }
  /**
   * <code>repeated .glory_api.DigitalCode r3d = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.zhijiejiaoyu.glory_api.short_video.DigitalCodeOrBuilder> 
      getR3DOrBuilderList() {
    return r3D ;
  }
  /**
   * <code>repeated .glory_api.DigitalCode r3d = 3;</code>
   */
  @java.lang.Override
  public int getR3DCount() {
    return r3D .size();
  }
  /**
   * <code>repeated .glory_api.DigitalCode r3d = 3;</code>
   */
  @java.lang.Override
  public com.zhijiejiaoyu.glory_api.short_video.DigitalCode getR3D(int index) {
    return r3D .get(index);
  }
  /**
   * <code>repeated .glory_api.DigitalCode r3d = 3;</code>
   */
  @java.lang.Override
  public com.zhijiejiaoyu.glory_api.short_video.DigitalCodeOrBuilder getR3DOrBuilder(
      int index) {
    return r3D .get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (baseResp != null) {
      output.writeMessage(1, getBaseResp());
    }
    for (int i = 0; i < r2D .size(); i++) {
      output.writeMessage(2, r2D .get(i));
    }
    for (int i = 0; i < r3D .size(); i++) {
      output.writeMessage(3, r3D .get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (baseResp != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBaseResp());
    }
    for (int i = 0; i < r2D .size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, r2D .get(i));
    }
    for (int i = 0; i < r3D .size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, r3D .get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse)) {
      return super.equals(obj);
    }
    com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse other = (com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse) obj;

    if (hasBaseResp() != other.hasBaseResp()) return false;
    if (hasBaseResp()) {
      if (!getBaseResp()
          .equals(other.getBaseResp())) return false;
    }
    if (!getR2DList()
        .equals(other.getR2DList())) return false;
    if (!getR3DList()
        .equals(other.getR3DList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBaseResp()) {
      hash = (37 * hash) + BASE_RESP_FIELD_NUMBER;
      hash = (53 * hash) + getBaseResp().hashCode();
    }
    if (getR2DCount() > 0) {
      hash = (37 * hash) + R2D_FIELD_NUMBER;
      hash = (53 * hash) + getR2DList().hashCode();
    }
    if (getR3DCount() > 0) {
      hash = (37 * hash) + R3D_FIELD_NUMBER;
      hash = (53 * hash) + getR3DList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code glory_api.ListDigitalCodeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:glory_api.ListDigitalCodeResponse)
      com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhijiejiaoyu.glory_api.short_video.Article.internal_static_glory_api_ListDigitalCodeResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhijiejiaoyu.glory_api.short_video.Article.internal_static_glory_api_ListDigitalCodeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse.class, com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse.Builder.class);
    }

    // Construct using com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getR2DFieldBuilder();
        getR3DFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (baseRespBuilder == null) {
        baseResp = null;
      } else {
        baseResp = null;
        baseRespBuilder = null;
      }
      if (r2DBuilder == null) {
        r2D = java.util.Collections.emptyList();
        bitField0 = (bitField0 & ~0x00000001);
      } else {
        r2DBuilder .clear();
      }
      if (r3DBuilder == null) {
        r3D = java.util.Collections.emptyList();
        bitField0 = (bitField0 & ~0x00000002);
      } else {
        r3DBuilder .clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.zhijiejiaoyu.glory_api.short_video.Article.internal_static_glory_api_ListDigitalCodeResponse_descriptor;
    }

    @java.lang.Override
    public com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse getDefaultInstanceForType() {
      return com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse build() {
      com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse buildPartial() {
      com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse result = new com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse(this);
      int from_bitField0 = bitField0 ;
      if (baseRespBuilder == null) {
        result.baseResp = baseResp ;
      } else {
        result.baseResp = baseRespBuilder .build();
      }
      if (r2DBuilder == null) {
        if (((bitField0 & 0x00000001) != 0)) {
          r2D = java.util.Collections.unmodifiableList(r2D );
          bitField0 = (bitField0 & ~0x00000001);
        }
        result.r2D = r2D ;
      } else {
        result.r2D = r2DBuilder .build();
      }
      if (r3DBuilder == null) {
        if (((bitField0 & 0x00000002) != 0)) {
          r3D = java.util.Collections.unmodifiableList(r3D );
          bitField0 = (bitField0 & ~0x00000002);
        }
        result.r3D = r3D ;
      } else {
        result.r3D = r3DBuilder .build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse) {
        return mergeFrom((com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse other) {
      if (other == com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse.getDefaultInstance()) return this;
      if (other.hasBaseResp()) {
        mergeBaseResp(other.getBaseResp());
      }
      if (r2DBuilder == null) {
        if (!other.r2D .isEmpty()) {
          if (r2D .isEmpty()) {
            r2D = other.r2D ;
            bitField0 = (bitField0 & ~0x00000001);
          } else {
            ensureR2DIsMutable();
            r2D .addAll(other.r2D );
          }
          onChanged();
        }
      } else {
        if (!other.r2D .isEmpty()) {
          if (r2DBuilder .isEmpty()) {
            r2DBuilder .dispose();
            r2DBuilder = null;
            r2D = other.r2D ;
            bitField0 = (bitField0 & ~0x00000001);
            r2DBuilder = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getR2DFieldBuilder() : null;
          } else {
            r2DBuilder .addAllMessages(other.r2D );
          }
        }
      }
      if (r3DBuilder == null) {
        if (!other.r3D .isEmpty()) {
          if (r3D .isEmpty()) {
            r3D = other.r3D ;
            bitField0 = (bitField0 & ~0x00000002);
          } else {
            ensureR3DIsMutable();
            r3D .addAll(other.r3D );
          }
          onChanged();
        }
      } else {
        if (!other.r3D .isEmpty()) {
          if (r3DBuilder .isEmpty()) {
            r3DBuilder .dispose();
            r3DBuilder = null;
            r3D = other.r3D ;
            bitField0 = (bitField0 & ~0x00000002);
            r3DBuilder = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getR3DFieldBuilder() : null;
          } else {
            r3DBuilder .addAllMessages(other.r3D );
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0 ;

    private com.zhijiejiaoyu.base.BaseResponse baseResp ;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.zhijiejiaoyu.base.BaseResponse, com.zhijiejiaoyu.base.BaseResponse.Builder, com.zhijiejiaoyu.base.BaseResponseOrBuilder> baseRespBuilder ;
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     * @return Whether the baseResp field is set.
     */
    public boolean hasBaseResp() {
      return baseRespBuilder != null || baseResp != null;
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     * @return The baseResp.
     */
    public com.zhijiejiaoyu.base.BaseResponse getBaseResp() {
      if (baseRespBuilder == null) {
        return baseResp == null ? com.zhijiejiaoyu.base.BaseResponse.getDefaultInstance() : baseResp ;
      } else {
        return baseRespBuilder .getMessage();
      }
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    public Builder setBaseResp(com.zhijiejiaoyu.base.BaseResponse value) {
      if (baseRespBuilder == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        baseResp = value;
        onChanged();
      } else {
        baseRespBuilder .setMessage(value);
      }

      return this;
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    public Builder setBaseResp(
        com.zhijiejiaoyu.base.BaseResponse.Builder builderForValue) {
      if (baseRespBuilder == null) {
        baseResp = builderForValue.build();
        onChanged();
      } else {
        baseRespBuilder .setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    public Builder mergeBaseResp(com.zhijiejiaoyu.base.BaseResponse value) {
      if (baseRespBuilder == null) {
        if (baseResp != null) {
          baseResp =
            com.zhijiejiaoyu.base.BaseResponse.newBuilder(baseResp ).mergeFrom(value).buildPartial();
        } else {
          baseResp = value;
        }
        onChanged();
      } else {
        baseRespBuilder .mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    public Builder clearBaseResp() {
      if (baseRespBuilder == null) {
        baseResp = null;
        onChanged();
      } else {
        baseResp = null;
        baseRespBuilder = null;
      }

      return this;
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    public com.zhijiejiaoyu.base.BaseResponse.Builder getBaseRespBuilder() {
      
      onChanged();
      return getBaseRespFieldBuilder().getBuilder();
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    public com.zhijiejiaoyu.base.BaseResponseOrBuilder getBaseRespOrBuilder() {
      if (baseRespBuilder != null) {
        return baseRespBuilder .getMessageOrBuilder();
      } else {
        return baseResp == null ?
            com.zhijiejiaoyu.base.BaseResponse.getDefaultInstance() : baseResp ;
      }
    }
    /**
     * <code>.base.BaseResponse base_resp = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.zhijiejiaoyu.base.BaseResponse, com.zhijiejiaoyu.base.BaseResponse.Builder, com.zhijiejiaoyu.base.BaseResponseOrBuilder> 
        getBaseRespFieldBuilder() {
      if (baseRespBuilder == null) {
        baseRespBuilder = new com.google.protobuf.SingleFieldBuilderV3<
            com.zhijiejiaoyu.base.BaseResponse, com.zhijiejiaoyu.base.BaseResponse.Builder, com.zhijiejiaoyu.base.BaseResponseOrBuilder>(
                getBaseResp(),
                getParentForChildren(),
                isClean());
        baseResp = null;
      }
      return baseRespBuilder ;
    }

    private java.util.List<com.zhijiejiaoyu.glory_api.short_video.DigitalCode> r2D =
      java.util.Collections.emptyList();
    private void ensureR2DIsMutable() {
      if (!((bitField0 & 0x00000001) != 0)) {
        r2D = new java.util.ArrayList<com.zhijiejiaoyu.glory_api.short_video.DigitalCode>(r2D );
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.zhijiejiaoyu.glory_api.short_video.DigitalCode, com.zhijiejiaoyu.glory_api.short_video.DigitalCode.Builder, com.zhijiejiaoyu.glory_api.short_video.DigitalCodeOrBuilder> r2DBuilder ;

    /**
     * <code>repeated .glory_api.DigitalCode r2d = 2;</code>
     */
    public java.util.List<com.zhijiejiaoyu.glory_api.short_video.DigitalCode> getR2DList() {
      if (r2DBuilder == null) {
        return java.util.Collections.unmodifiableList(r2D );
      } else {
        return r2DBuilder .getMessageList();
      }
    }
    /**
     * <code>repeated .glory_api.DigitalCode r2d = 2;</code>
     */
    public int getR2DCount() {
      if (r2DBuilder == null) {
        return r2D .size();
      } else {
        return r2DBuilder .getCount();
      }
    }
    /**
     * <code>repeated .glory_api.DigitalCode r2d = 2;</code>
     */
    public com.zhijiejiaoyu.glory_api.short_video.DigitalCode getR2D(int index) {
      if (r2DBuilder == null) {
        return r2D .get(index);
      } else {
        return r2DBuilder .getMessage(index);
      }
    }
    /**
     * <code>repeated .glory_api.DigitalCode r2d = 2;</code>
     */
    public Builder setR2D(
        int index, com.zhijiejiaoyu.glory_api.short_video.DigitalCode value) {
      if (r2DBuilder == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureR2DIsMutable();
        r2D .set(index, value);
        onChanged();
      } else {
        r2DBuilder .setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.DigitalCode r2d = 2;</code>
     */
    public Builder setR2D(
        int index, com.zhijiejiaoyu.glory_api.short_video.DigitalCode.Builder builderForValue) {
      if (r2DBuilder == null) {
        ensureR2DIsMutable();
        r2D .set(index, builderForValue.build());
        onChanged();
      } else {
        r2DBuilder .setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.DigitalCode r2d = 2;</code>
     */
    public Builder addR2D(com.zhijiejiaoyu.glory_api.short_video.DigitalCode value) {
      if (r2DBuilder == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureR2DIsMutable();
        r2D .add(value);
        onChanged();
      } else {
        r2DBuilder .addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.DigitalCode r2d = 2;</code>
     */
    public Builder addR2D(
        int index, com.zhijiejiaoyu.glory_api.short_video.DigitalCode value) {
      if (r2DBuilder == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureR2DIsMutable();
        r2D .add(index, value);
        onChanged();
      } else {
        r2DBuilder .addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.DigitalCode r2d = 2;</code>
     */
    public Builder addR2D(
        com.zhijiejiaoyu.glory_api.short_video.DigitalCode.Builder builderForValue) {
      if (r2DBuilder == null) {
        ensureR2DIsMutable();
        r2D .add(builderForValue.build());
        onChanged();
      } else {
        r2DBuilder .addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.DigitalCode r2d = 2;</code>
     */
    public Builder addR2D(
        int index, com.zhijiejiaoyu.glory_api.short_video.DigitalCode.Builder builderForValue) {
      if (r2DBuilder == null) {
        ensureR2DIsMutable();
        r2D .add(index, builderForValue.build());
        onChanged();
      } else {
        r2DBuilder .addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.DigitalCode r2d = 2;</code>
     */
    public Builder addAllR2D(
        java.lang.Iterable<? extends com.zhijiejiaoyu.glory_api.short_video.DigitalCode> values) {
      if (r2DBuilder == null) {
        ensureR2DIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, r2D );
        onChanged();
      } else {
        r2DBuilder .addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.DigitalCode r2d = 2;</code>
     */
    public Builder clearR2D() {
      if (r2DBuilder == null) {
        r2D = java.util.Collections.emptyList();
        bitField0 = (bitField0 & ~0x00000001);
        onChanged();
      } else {
        r2DBuilder .clear();
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.DigitalCode r2d = 2;</code>
     */
    public Builder removeR2D(int index) {
      if (r2DBuilder == null) {
        ensureR2DIsMutable();
        r2D .remove(index);
        onChanged();
      } else {
        r2DBuilder .remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.DigitalCode r2d = 2;</code>
     */
    public com.zhijiejiaoyu.glory_api.short_video.DigitalCode.Builder getR2DBuilder(
        int index) {
      return getR2DFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .glory_api.DigitalCode r2d = 2;</code>
     */
    public com.zhijiejiaoyu.glory_api.short_video.DigitalCodeOrBuilder getR2DOrBuilder(
        int index) {
      if (r2DBuilder == null) {
        return r2D .get(index);  } else {
        return r2DBuilder .getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .glory_api.DigitalCode r2d = 2;</code>
     */
    public java.util.List<? extends com.zhijiejiaoyu.glory_api.short_video.DigitalCodeOrBuilder> 
         getR2DOrBuilderList() {
      if (r2DBuilder != null) {
        return r2DBuilder .getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(r2D );
      }
    }
    /**
     * <code>repeated .glory_api.DigitalCode r2d = 2;</code>
     */
    public com.zhijiejiaoyu.glory_api.short_video.DigitalCode.Builder addR2DBuilder() {
      return getR2DFieldBuilder().addBuilder(
          com.zhijiejiaoyu.glory_api.short_video.DigitalCode.getDefaultInstance());
    }
    /**
     * <code>repeated .glory_api.DigitalCode r2d = 2;</code>
     */
    public com.zhijiejiaoyu.glory_api.short_video.DigitalCode.Builder addR2DBuilder(
        int index) {
      return getR2DFieldBuilder().addBuilder(
          index, com.zhijiejiaoyu.glory_api.short_video.DigitalCode.getDefaultInstance());
    }
    /**
     * <code>repeated .glory_api.DigitalCode r2d = 2;</code>
     */
    public java.util.List<com.zhijiejiaoyu.glory_api.short_video.DigitalCode.Builder> 
         getR2DBuilderList() {
      return getR2DFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.zhijiejiaoyu.glory_api.short_video.DigitalCode, com.zhijiejiaoyu.glory_api.short_video.DigitalCode.Builder, com.zhijiejiaoyu.glory_api.short_video.DigitalCodeOrBuilder> 
        getR2DFieldBuilder() {
      if (r2DBuilder == null) {
        r2DBuilder = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.zhijiejiaoyu.glory_api.short_video.DigitalCode, com.zhijiejiaoyu.glory_api.short_video.DigitalCode.Builder, com.zhijiejiaoyu.glory_api.short_video.DigitalCodeOrBuilder>(
                r2D ,
                ((bitField0 & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        r2D = null;
      }
      return r2DBuilder ;
    }

    private java.util.List<com.zhijiejiaoyu.glory_api.short_video.DigitalCode> r3D =
      java.util.Collections.emptyList();
    private void ensureR3DIsMutable() {
      if (!((bitField0 & 0x00000002) != 0)) {
        r3D = new java.util.ArrayList<com.zhijiejiaoyu.glory_api.short_video.DigitalCode>(r3D );
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.zhijiejiaoyu.glory_api.short_video.DigitalCode, com.zhijiejiaoyu.glory_api.short_video.DigitalCode.Builder, com.zhijiejiaoyu.glory_api.short_video.DigitalCodeOrBuilder> r3DBuilder ;

    /**
     * <code>repeated .glory_api.DigitalCode r3d = 3;</code>
     */
    public java.util.List<com.zhijiejiaoyu.glory_api.short_video.DigitalCode> getR3DList() {
      if (r3DBuilder == null) {
        return java.util.Collections.unmodifiableList(r3D );
      } else {
        return r3DBuilder .getMessageList();
      }
    }
    /**
     * <code>repeated .glory_api.DigitalCode r3d = 3;</code>
     */
    public int getR3DCount() {
      if (r3DBuilder == null) {
        return r3D .size();
      } else {
        return r3DBuilder .getCount();
      }
    }
    /**
     * <code>repeated .glory_api.DigitalCode r3d = 3;</code>
     */
    public com.zhijiejiaoyu.glory_api.short_video.DigitalCode getR3D(int index) {
      if (r3DBuilder == null) {
        return r3D .get(index);
      } else {
        return r3DBuilder .getMessage(index);
      }
    }
    /**
     * <code>repeated .glory_api.DigitalCode r3d = 3;</code>
     */
    public Builder setR3D(
        int index, com.zhijiejiaoyu.glory_api.short_video.DigitalCode value) {
      if (r3DBuilder == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureR3DIsMutable();
        r3D .set(index, value);
        onChanged();
      } else {
        r3DBuilder .setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.DigitalCode r3d = 3;</code>
     */
    public Builder setR3D(
        int index, com.zhijiejiaoyu.glory_api.short_video.DigitalCode.Builder builderForValue) {
      if (r3DBuilder == null) {
        ensureR3DIsMutable();
        r3D .set(index, builderForValue.build());
        onChanged();
      } else {
        r3DBuilder .setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.DigitalCode r3d = 3;</code>
     */
    public Builder addR3D(com.zhijiejiaoyu.glory_api.short_video.DigitalCode value) {
      if (r3DBuilder == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureR3DIsMutable();
        r3D .add(value);
        onChanged();
      } else {
        r3DBuilder .addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.DigitalCode r3d = 3;</code>
     */
    public Builder addR3D(
        int index, com.zhijiejiaoyu.glory_api.short_video.DigitalCode value) {
      if (r3DBuilder == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureR3DIsMutable();
        r3D .add(index, value);
        onChanged();
      } else {
        r3DBuilder .addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.DigitalCode r3d = 3;</code>
     */
    public Builder addR3D(
        com.zhijiejiaoyu.glory_api.short_video.DigitalCode.Builder builderForValue) {
      if (r3DBuilder == null) {
        ensureR3DIsMutable();
        r3D .add(builderForValue.build());
        onChanged();
      } else {
        r3DBuilder .addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.DigitalCode r3d = 3;</code>
     */
    public Builder addR3D(
        int index, com.zhijiejiaoyu.glory_api.short_video.DigitalCode.Builder builderForValue) {
      if (r3DBuilder == null) {
        ensureR3DIsMutable();
        r3D .add(index, builderForValue.build());
        onChanged();
      } else {
        r3DBuilder .addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.DigitalCode r3d = 3;</code>
     */
    public Builder addAllR3D(
        java.lang.Iterable<? extends com.zhijiejiaoyu.glory_api.short_video.DigitalCode> values) {
      if (r3DBuilder == null) {
        ensureR3DIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, r3D );
        onChanged();
      } else {
        r3DBuilder .addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.DigitalCode r3d = 3;</code>
     */
    public Builder clearR3D() {
      if (r3DBuilder == null) {
        r3D = java.util.Collections.emptyList();
        bitField0 = (bitField0 & ~0x00000002);
        onChanged();
      } else {
        r3DBuilder .clear();
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.DigitalCode r3d = 3;</code>
     */
    public Builder removeR3D(int index) {
      if (r3DBuilder == null) {
        ensureR3DIsMutable();
        r3D .remove(index);
        onChanged();
      } else {
        r3DBuilder .remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .glory_api.DigitalCode r3d = 3;</code>
     */
    public com.zhijiejiaoyu.glory_api.short_video.DigitalCode.Builder getR3DBuilder(
        int index) {
      return getR3DFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .glory_api.DigitalCode r3d = 3;</code>
     */
    public com.zhijiejiaoyu.glory_api.short_video.DigitalCodeOrBuilder getR3DOrBuilder(
        int index) {
      if (r3DBuilder == null) {
        return r3D .get(index);  } else {
        return r3DBuilder .getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .glory_api.DigitalCode r3d = 3;</code>
     */
    public java.util.List<? extends com.zhijiejiaoyu.glory_api.short_video.DigitalCodeOrBuilder> 
         getR3DOrBuilderList() {
      if (r3DBuilder != null) {
        return r3DBuilder .getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(r3D );
      }
    }
    /**
     * <code>repeated .glory_api.DigitalCode r3d = 3;</code>
     */
    public com.zhijiejiaoyu.glory_api.short_video.DigitalCode.Builder addR3DBuilder() {
      return getR3DFieldBuilder().addBuilder(
          com.zhijiejiaoyu.glory_api.short_video.DigitalCode.getDefaultInstance());
    }
    /**
     * <code>repeated .glory_api.DigitalCode r3d = 3;</code>
     */
    public com.zhijiejiaoyu.glory_api.short_video.DigitalCode.Builder addR3DBuilder(
        int index) {
      return getR3DFieldBuilder().addBuilder(
          index, com.zhijiejiaoyu.glory_api.short_video.DigitalCode.getDefaultInstance());
    }
    /**
     * <code>repeated .glory_api.DigitalCode r3d = 3;</code>
     */
    public java.util.List<com.zhijiejiaoyu.glory_api.short_video.DigitalCode.Builder> 
         getR3DBuilderList() {
      return getR3DFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.zhijiejiaoyu.glory_api.short_video.DigitalCode, com.zhijiejiaoyu.glory_api.short_video.DigitalCode.Builder, com.zhijiejiaoyu.glory_api.short_video.DigitalCodeOrBuilder> 
        getR3DFieldBuilder() {
      if (r3DBuilder == null) {
        r3DBuilder = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.zhijiejiaoyu.glory_api.short_video.DigitalCode, com.zhijiejiaoyu.glory_api.short_video.DigitalCode.Builder, com.zhijiejiaoyu.glory_api.short_video.DigitalCodeOrBuilder>(
                r3D ,
                ((bitField0 & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        r3D = null;
      }
      return r3DBuilder ;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:glory_api.ListDigitalCodeResponse)
  }

  // @@protoc_insertion_point(class_scope:glory_api.ListDigitalCodeResponse)
  private static final com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse();
  }

  public static com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListDigitalCodeResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListDigitalCodeResponse>() {
    @java.lang.Override
    public ListDigitalCodeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListDigitalCodeResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListDigitalCodeResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListDigitalCodeResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.zhijiejiaoyu.glory_api.short_video.ListDigitalCodeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

