//
//  Generated code. Do not modify.
//  source: glory_api_service.proto
//
// @dart = 2.12

// ignore_for_file: annotate_overrides, camel_case_types, comment_references
// ignore_for_file: constant_identifier_names
// ignore_for_file: deprecated_member_use_from_same_package, library_prefixes
// ignore_for_file: non_constant_identifier_names, prefer_final_fields
// ignore_for_file: unnecessary_import, unnecessary_this, unused_import

import 'dart:async' as $async;
import 'dart:core' as $core;

import 'package:protobuf/protobuf.dart' as $pb;

import 'account/account_operation.pb.dart' as $23;
import 'admin/admin_tenant.pb.dart' as $19;
import 'admin/admin_user.pb.dart' as $20;
import 'admin/config.pb.dart' as $18;
import 'app/app.pb.dart' as $46;
import 'course/cmodule.pb.dart' as $40;
import 'course/course.pb.dart' as $39;
import 'course/edu_scheme.pb.dart' as $45;
import 'course/graph.pb.dart' as $42;
import 'course/job.pb.dart' as $47;
import 'course/material.pb.dart' as $37;
import 'course/module.pb.dart' as $38;
import 'course/nmodule.pb.dart' as $41;
import 'course/teaching_plan.pb.dart' as $44;
import 'course/user_course.pb.dart' as $43;
import 'currency/virtual_currency.pb.dart' as $22;
import 'example/example.pb.dart' as $0;
import 'glory_api_service.pbjson.dart';
import 'live/live_evaluate.pb.dart' as $29;
import 'live/live_plan.pb.dart' as $25;
import 'live/live_room.pb.dart' as $24;
import 'live/live_text.pb.dart' as $28;
import 'live/live_token.pb.dart' as $26;
import 'live/live_user.pb.dart' as $27;
import 'mall/mall_index.pb.dart' as $7;
import 'payment/payment.pb.dart' as $17;
import 'role/role.pb.dart' as $3;
import 'seller/attachment.pb.dart' as $15;
import 'seller/seller.pb.dart' as $16;
import 'shop/activity.pb.dart' as $36;
import 'shop/attribute.pb.dart' as $12;
import 'shop/cart.pb.dart' as $14;
import 'shop/category.pb.dart' as $8;
import 'shop/category_qualification.pb.dart' as $9;
import 'shop/coupon.pb.dart' as $35;
import 'shop/freight_template.pb.dart' as $6;
import 'shop/operation.pb.dart' as $5;
import 'shop/order.pb.dart' as $13;
import 'shop/product.pb.dart' as $10;
import 'shop/shop.pb.dart' as $4;
import 'shop/sku.pb.dart' as $11;
import 'short_video/short_video.pb.dart' as $34;
import 'tenant/tenant.pb.dart' as $30;
import 'tenant/tenant_config.pb.dart' as $33;
import 'tenant/tenant_dept.pb.dart' as $31;
import 'tenant/tenant_user.pb.dart' as $32;
import 'traffic/live_traffic.pb.dart' as $48;
import 'user/address.pb.dart' as $2;
import 'user/user.pb.dart' as $1;
import 'wxpay/wxpay.pb.dart' as $21;

export 'glory_api_service.pb.dart';

abstract class glory_apiServiceBase extends $pb.GeneratedService {
  $async.Future<$0.CreateExampleResponse> createExample($pb.ServerContext ctx, $0.CreateExampleRequest request);
  $async.Future<$0.GetExampleResponse> getExample($pb.ServerContext ctx, $0.GetExampleRequest request);
  $async.Future<$0.UpdateExampleResponse> updateExample($pb.ServerContext ctx, $0.UpdateExampleRequest request);
  $async.Future<$0.ListExampleResponse> listExample($pb.ServerContext ctx, $0.ListExampleRequest request);
  $async.Future<$0.DeleteExampleResponse> deleteExample($pb.ServerContext ctx, $0.DeleteExampleRequest request);
  $async.Future<$1.LoginResponse> login($pb.ServerContext ctx, $1.LoginRequest request);
  $async.Future<$1.LogoutResponse> logout($pb.ServerContext ctx, $1.LogoutRequest request);
  $async.Future<$1.GetVerifyCodeResponse> getVerifyCode($pb.ServerContext ctx, $1.GetVerifyCodeRequest request);
  $async.Future<$1.CheckVerifyCodeResponse> checkVerifyCode($pb.ServerContext ctx, $1.CheckVerifyCodeRequest request);
  $async.Future<$1.GetUserResponse> getUser($pb.ServerContext ctx, $1.GetUserRequest request);
  $async.Future<$1.LoginWithPasswordResponse> loginWithPassword($pb.ServerContext ctx, $1.LoginWithPasswordRequest request);
  $async.Future<$1.UpdatePasswordResponse> updatePassword($pb.ServerContext ctx, $1.UpdatePasswordRequest request);
  $async.Future<$1.UpdateUserResponse> updateUser($pb.ServerContext ctx, $1.UpdateUserRequest request);
  $async.Future<$1.UpdatePhoneResponse> updatePhone($pb.ServerContext ctx, $1.UpdatePhoneRequest request);
  $async.Future<$1.UpdateUserTenantResponse> updateUserTenant($pb.ServerContext ctx, $1.UpdateUserTenantRequest request);
  $async.Future<$1.FollowUserResponse> followUser($pb.ServerContext ctx, $1.FollowUserRequest request);
  $async.Future<$1.ListMyFollowingResponse> listMyFollowing($pb.ServerContext ctx, $1.ListMyFollowingRequest request);
  $async.Future<$1.ListMyFollowerResponse> listMyFollower($pb.ServerContext ctx, $1.ListMyFollowerRequest request);
  $async.Future<$1.ListMyFriendResponse> listMyFriend($pb.ServerContext ctx, $1.ListMyFriendRequest request);
  $async.Future<$1.GetMySocialSummaryResponse> getMySocialSummary($pb.ServerContext ctx, $1.GetMySocialSummaryRequest request);
  $async.Future<$1.GetUserPagePermissionResponse> getUserPagePermission($pb.ServerContext ctx, $1.GetUserPagePermissionRequest request);
  $async.Future<$1.CreateRolePagePermissionResponse> createRolePagePermission($pb.ServerContext ctx, $1.CreateRolePagePermissionRequest request);
  $async.Future<$1.UpdateRolePagePermissionResponse> updateRolePagePermission($pb.ServerContext ctx, $1.UpdateRolePagePermissionRequest request);
  $async.Future<$1.GetRolePagePermissionResponse> getRolePagePermission($pb.ServerContext ctx, $1.GetRolePagePermissionRequest request);
  $async.Future<$2.AddAddressResponse> addAddress($pb.ServerContext ctx, $2.AddAddressRequest request);
  $async.Future<$2.DeleteAddressResponse> deleteAddress($pb.ServerContext ctx, $2.DeleteAddressRequest request);
  $async.Future<$2.UpdateAddressResponse> updateAddress($pb.ServerContext ctx, $2.UpdateAddressRequest request);
  $async.Future<$2.GetAddressResponse> getAddress($pb.ServerContext ctx, $2.GetAddressRequest request);
  $async.Future<$2.ListAddressResponse> listAddress($pb.ServerContext ctx, $2.ListAddressRequest request);
  $async.Future<$1.ListUserByRoleResponse> listUserByRole($pb.ServerContext ctx, $1.ListUserByRoleRequest request);
  $async.Future<$1.ListPermissionResponse> listPermission($pb.ServerContext ctx, $1.ListPermissionRequest request);
  $async.Future<$1.ListRoleResponse> listRole($pb.ServerContext ctx, $1.ListRoleRequest request);
  $async.Future<$1.GiveRolePermissionResponse> giveRolePermission($pb.ServerContext ctx, $1.GiveRolePermissionRequest request);
  $async.Future<$1.RemoveRolePermissionResponse> removeRolePermission($pb.ServerContext ctx, $1.RemoveRolePermissionRequest request);
  $async.Future<$1.CreateRoleResponse> createRole($pb.ServerContext ctx, $1.CreateRoleRequest request);
  $async.Future<$1.DeleteRoleResponse> deleteRole($pb.ServerContext ctx, $1.DeleteRoleRequest request);
  $async.Future<$1.ListResourceResponse> listResource($pb.ServerContext ctx, $1.ListResourceRequest request);
  $async.Future<$1.GetRoleTypeResponse> getRoleType($pb.ServerContext ctx, $1.GetRoleTypeRequest request);
  $async.Future<$3.GetRoleTemplateResponse> getRoleTemplate($pb.ServerContext ctx, $3.GetRoleTemplateRequest request);
  $async.Future<$3.UpdateRoleTemplateResponse> updateRoleTemplate($pb.ServerContext ctx, $3.UpdateRoleTemplateRequest request);
  $async.Future<$4.CreateShopResponse> createShop($pb.ServerContext ctx, $4.CreateShopRequest request);
  $async.Future<$4.GetShopResponse> getShop($pb.ServerContext ctx, $4.GetShopRequest request);
  $async.Future<$4.UpdateShopResponse> updateShop($pb.ServerContext ctx, $4.UpdateShopRequest request);
  $async.Future<$4.ListShopResponse> listShop($pb.ServerContext ctx, $4.ListShopRequest request);
  $async.Future<$4.DeleteShopResponse> deleteShop($pb.ServerContext ctx, $4.DeleteShopRequest request);
  $async.Future<$5.ListOperationMetricsResponse> listOperationMetrics($pb.ServerContext ctx, $5.ListOperationMetricsRequest request);
  $async.Future<$4.GetShopQrcodeResponse> getShopQrcode($pb.ServerContext ctx, $4.GetShopQrcodeRequest request);
  $async.Future<$4.UpdateShopManagerResponse> updateShopManager($pb.ServerContext ctx, $4.UpdateShopManagerRequest request);
  $async.Future<$4.GetShopBusinessDataResponse> getShopBusinessData($pb.ServerContext ctx, $4.GetShopBusinessDataRequest request);
  $async.Future<$4.AddShopAccessResponse> addShopAccess($pb.ServerContext ctx, $4.AddShopAccessRequest request);
  $async.Future<$4.RemoveShopAccessResponse> removeShopAccess($pb.ServerContext ctx, $4.RemoveShopAccessRequest request);
  $async.Future<$4.VerifyFieldResponse> verifyField($pb.ServerContext ctx, $4.VerifyFieldRequest request);
  $async.Future<$4.ListShopAccessResponse> listShopAccess($pb.ServerContext ctx, $4.ListShopAccessRequest request);
  $async.Future<$4.AddShopCategoryResponse> addShopCategory($pb.ServerContext ctx, $4.AddShopCategoryRequest request);
  $async.Future<$4.GetShopCategoryResponse> getShopCategory($pb.ServerContext ctx, $4.GetShopCategoryRequest request);
  $async.Future<$4.RemoveShopCategoryResponse> removeShopCategory($pb.ServerContext ctx, $4.RemoveShopCategoryRequest request);
  $async.Future<$6.CreateTemplateResponse> addFreightTemplate($pb.ServerContext ctx, $6.CreateTemplateRequest request);
  $async.Future<$6.GetTemplateResponse> getFreightTemplate($pb.ServerContext ctx, $6.GetTemplateRequest request);
  $async.Future<$6.UpdateTemplateResponse> updateFreightTemplate($pb.ServerContext ctx, $6.UpdateTemplateRequest request);
  $async.Future<$6.DeleteTemplateResponse> deleteFreightTemplate($pb.ServerContext ctx, $6.DeleteTemplateRequest request);
  $async.Future<$6.ListTemplateResponse> listFreightTemplate($pb.ServerContext ctx, $6.ListTemplateRequest request);
  $async.Future<$4.ListShopQualificationResponse> listQualification($pb.ServerContext ctx, $4.ListShopQualificationRequest request);
  $async.Future<$7.MallIndexResponse> getMallIndex($pb.ServerContext ctx, $7.MallIndexRequest request);
  $async.Future<$8.CreateCategoryResponse> createCategory($pb.ServerContext ctx, $8.CreateCategoryRequest request);
  $async.Future<$8.GetCategoryResponse> getCategory($pb.ServerContext ctx, $8.GetCategoryRequest request);
  $async.Future<$8.UpdateCategoryResponse> updateCategory($pb.ServerContext ctx, $8.UpdateCategoryRequest request);
  $async.Future<$8.ListCategoryResponse> listCategory($pb.ServerContext ctx, $8.ListCategoryRequest request);
  $async.Future<$8.DeleteCategoryResponse> deleteCategory($pb.ServerContext ctx, $8.DeleteCategoryRequest request);
  $async.Future<$9.ListCategoryQualificationResponse> listCategoryQualification($pb.ServerContext ctx, $9.ListCategoryQualificationRequest request);
  $async.Future<$10.CreateProductResponse> createProduct($pb.ServerContext ctx, $10.CreateProductRequest request);
  $async.Future<$10.GetProductResponse> getProduct($pb.ServerContext ctx, $10.GetProductRequest request);
  $async.Future<$10.UpdateProductResponse> updateProduct($pb.ServerContext ctx, $10.UpdateProductRequest request);
  $async.Future<$10.ListProductResponse> listProduct($pb.ServerContext ctx, $10.ListProductRequest request);
  $async.Future<$10.ListProductByProductIDsResponse> listProductByIDs($pb.ServerContext ctx, $10.ListProductByProductIDsRequest request);
  $async.Future<$10.DeleteProductResponse> deleteProduct($pb.ServerContext ctx, $10.DeleteProductRequest request);
  $async.Future<$10.UploadMultiImageResponse> uploadMultiImage($pb.ServerContext ctx, $10.UploadMultiImageRequest request);
  $async.Future<$10.DeleteImageResponse> deleteImageById($pb.ServerContext ctx, $10.DeleteImageRequest request);
  $async.Future<$10.BindAttributeResponse> bindAttribute($pb.ServerContext ctx, $10.BindAttributeRequest request);
  $async.Future<$10.PublishProductResponse> publishProduct($pb.ServerContext ctx, $10.PublishProductRequest request);
  $async.Future<$10.OffSelfProductsResponse> offShelfProductInBatches($pb.ServerContext ctx, $10.OffSelfProductsRequest request);
  $async.Future<$10.DeleteProductsResponse> deleteProductInBatches($pb.ServerContext ctx, $10.DeleteProductsRequest request);
  $async.Future<$10.ChangeProductStateResponse> changeProductsState($pb.ServerContext ctx, $10.ChangeProductStateRequest request);
  $async.Future<$10.SaveImageInfoResponse> saveProductImageInfo($pb.ServerContext ctx, $10.SaveImageInfoRequest request);
  $async.Future<$11.CreateSkuResponse> createSku($pb.ServerContext ctx, $11.CreateSkuRequest request);
  $async.Future<$11.GetSkuResponse> getSku($pb.ServerContext ctx, $11.GetSkuRequest request);
  $async.Future<$11.UpdateSkuResponse> updateSku($pb.ServerContext ctx, $11.UpdateSkuRequest request);
  $async.Future<$11.ListSkuResponse> listSku($pb.ServerContext ctx, $11.ListSkuRequest request);
  $async.Future<$11.DeleteSkuResponse> deleteSku($pb.ServerContext ctx, $11.DeleteSkuRequest request);
  $async.Future<$12.CreateAttributeResponse> createAttribute($pb.ServerContext ctx, $12.CreateAttributeRequest request);
  $async.Future<$12.GetAttributeResponse> getAttribute($pb.ServerContext ctx, $12.GetAttributeRequest request);
  $async.Future<$12.ListAttributeResponse> listAttribute($pb.ServerContext ctx, $12.ListAttributeRequest request);
  $async.Future<$12.DeleteAttributeResponse> deleteAttribute($pb.ServerContext ctx, $12.DeleteAttributeRequest request);
  $async.Future<$12.AddAttributeValueResponse> addAttributeValue($pb.ServerContext ctx, $12.AddAttributeValueRequest request);
  $async.Future<$12.DeleteAttributeValueResponse> deleteAttributeValue($pb.ServerContext ctx, $12.DeleteAttributeValueRequest request);
  $async.Future<$13.CreateOrderResponse> createOrder($pb.ServerContext ctx, $13.CreateOrderRequest request);
  $async.Future<$13.GetOrderResponse> getOrder($pb.ServerContext ctx, $13.GetOrderRequest request);
  $async.Future<$13.UpdateOrderResponse> updateOrder($pb.ServerContext ctx, $13.UpdateOrderRequest request);
  $async.Future<$13.ListOrderResponse> listOrder($pb.ServerContext ctx, $13.ListOrderRequest request);
  $async.Future<$13.DeleteOrderResponse> deleteOrder($pb.ServerContext ctx, $13.DeleteOrderRequest request);
  $async.Future<$13.ShipGoodsResponse> shipGoods($pb.ServerContext ctx, $13.ShipGoodsRequest request);
  $async.Future<$13.ConfirmReceiptGoodsResponse> confirmReceiptGoods($pb.ServerContext ctx, $13.ConfirmReceiptGoodsRequest request);
  $async.Future<$13.CancelOrderResponse> cancelOrder($pb.ServerContext ctx, $13.CancelOrderRequest request);
  $async.Future<$13.ShipGoodsInBatchesResponse> shipGoodsInBatches($pb.ServerContext ctx, $13.ShipGoodsInBatchesRequest request);
  $async.Future<$13.FreeShippingInBatchesResponse> freeShippingInBatches($pb.ServerContext ctx, $13.FreeShippingInBatchesRequest request);
  $async.Future<$4.ListShopSummaryResponse> listShopSummary($pb.ServerContext ctx, $4.ListShopSummaryRequest request);
  $async.Future<$4.ListShopBySellerIDResponse> listShopBySellerID($pb.ServerContext ctx, $4.ListShopBySellerIDRequest request);
  $async.Future<$14.AddCartResponse> createCart($pb.ServerContext ctx, $14.AddCartRequest request);
  $async.Future<$14.GetCartResponse> getCart($pb.ServerContext ctx, $14.GetCartRequest request);
  $async.Future<$14.UpdateCartResponse> updateCart($pb.ServerContext ctx, $14.UpdateCartRequest request);
  $async.Future<$14.DeleteCartResponse> deleteCart($pb.ServerContext ctx, $14.DeleteCartRequest request);
  $async.Future<$15.UploadAttachmentResponse> uploadAttachment($pb.ServerContext ctx, $15.UploadAttachmentRequest request);
  $async.Future<$15.SaveAttachmentResponse> saveAttachment($pb.ServerContext ctx, $15.SaveAttachmentRequest request);
  $async.Future<$15.ListAttachmentResponse> listAttachment($pb.ServerContext ctx, $15.ListAttachmentRequest request);
  $async.Future<$15.DeleteAttachmentResponse> deleteAttachment($pb.ServerContext ctx, $15.DeleteAttachmentRequest request);
  $async.Future<$16.CreateSellerResponse> createSeller($pb.ServerContext ctx, $16.CreateSellerRequest request);
  $async.Future<$17.CreatePaymentResponse> createPayment($pb.ServerContext ctx, $17.CreatePaymentRequest request);
  $async.Future<$17.GetPaymentResponse> getPayment($pb.ServerContext ctx, $17.GetPaymentRequest request);
  $async.Future<$17.UpdatePaymentResponse> updatePayment($pb.ServerContext ctx, $17.UpdatePaymentRequest request);
  $async.Future<$17.DeletePaymentResponse> deletePayment($pb.ServerContext ctx, $17.DeletePaymentRequest request);
  $async.Future<$18.CreateConfigResponse> createConfig($pb.ServerContext ctx, $18.CreateConfigRequest request);
  $async.Future<$18.UpdateConfigResponse> updateConfig($pb.ServerContext ctx, $18.UpdateConfigRequest request);
  $async.Future<$18.DeleteConfigResponse> deleteConfig($pb.ServerContext ctx, $18.DeleteConfigRequest request);
  $async.Future<$18.GetConfigResponse> getConfig($pb.ServerContext ctx, $18.GetConfigRequest request);
  $async.Future<$18.GetSTSResponse> getSTS($pb.ServerContext ctx, $18.GetSTSRequest request);
  $async.Future<$19.ListTenantOrgResponse> listTenantOrg($pb.ServerContext ctx, $19.ListTenantOrgRequest request);
  $async.Future<$20.GetAdminTenantResponse> getAdminTenant($pb.ServerContext ctx, $20.GetAdminTenantRequest request);
  $async.Future<$20.ListAdminUserResponse> listAdminUser($pb.ServerContext ctx, $20.ListAdminUserRequest request);
  $async.Future<$20.CreateAdminUserResponse> createAdminUser($pb.ServerContext ctx, $20.CreateAdminUserRequest request);
  $async.Future<$20.UpdateAdminUserResponse> updateAdminUser($pb.ServerContext ctx, $20.UpdateAdminUserRequest request);
  $async.Future<$20.DeleteAdminUserResponse> deleteAdminUser($pb.ServerContext ctx, $20.DeleteAdminUserRequest request);
  $async.Future<$21.PrepayResponse> wxPrepay($pb.ServerContext ctx, $21.PrepayRequest request);
  $async.Future<$21.CloseOrderResponse> closeOrder($pb.ServerContext ctx, $21.CloseOrderRequest request);
  $async.Future<$21.QueryOrderByIdResponse> queryOrderById($pb.ServerContext ctx, $21.QueryOrderByIdRequest request);
  $async.Future<$21.QueryOrderByOutTradeNoResponse> queryOrderByOutTrade($pb.ServerContext ctx, $21.QueryOrderByOutTradeNoRequest request);
  $async.Future<$22.AddVirtualCurrencyResponse> addVCurrency($pb.ServerContext ctx, $22.AddVirtualCurrencyRequest request);
  $async.Future<$22.RechargeCurrencyResponse> rechargeCurrency($pb.ServerContext ctx, $22.RechargeCurrencyRequest request);
  $async.Future<$22.RechargeCurrencyInBatchesResponse> rechargeCurrencyInBatches($pb.ServerContext ctx, $22.RechargeCurrencyInBatchesRequest request);
  $async.Future<$22.GetVirtualCurrencyResponse> getVCurrency($pb.ServerContext ctx, $22.GetVirtualCurrencyRequest request);
  $async.Future<$22.ListVirtualCurrencyResponse> listVCurrency($pb.ServerContext ctx, $22.ListVirtualCurrencyRequest request);
  $async.Future<$23.ListAccountOperationResponse> listAccountOperation($pb.ServerContext ctx, $23.ListAccountOperationRequest request);
  $async.Future<$24.CreateRoomResponse> createRoom($pb.ServerContext ctx, $24.CreateRoomRequest request);
  $async.Future<$24.GetRoomResponse> getRoom($pb.ServerContext ctx, $24.GetRoomRequest request);
  $async.Future<$24.UpdateRoomResponse> updateRoom($pb.ServerContext ctx, $24.UpdateRoomRequest request);
  $async.Future<$24.ListRoomResponse> listRoom($pb.ServerContext ctx, $24.ListRoomRequest request);
  $async.Future<$24.DeleteRoomResponse> deleteRoom($pb.ServerContext ctx, $24.DeleteRoomRequest request);
  $async.Future<$24.ListFinishedRoomResponse> listFinishedRoom($pb.ServerContext ctx, $24.ListFinishedRoomRequest request);
  $async.Future<$24.GetFinishedRoomResponse> getFinishedRoom($pb.ServerContext ctx, $24.GetFinishedRoomRequest request);
  $async.Future<$25.LiveRecordResponse> record($pb.ServerContext ctx, $25.LiveRecordRequest request);
  $async.Future<$26.CreateLiveUserTokenResponse> createLiveUserToken($pb.ServerContext ctx, $26.CreateLiveUserTokenRequest request);
  $async.Future<$27.UserEnterRoomResponse> userEnterRoom($pb.ServerContext ctx, $27.UserEnterRoomRequest request);
  $async.Future<$27.UserExitRoomResponse> userExitRoom($pb.ServerContext ctx, $27.UserExitRoomRequest request);
  $async.Future<$15.ListAttachmentResponse> listActiveRoomUser($pb.ServerContext ctx, $27.ListActiveRoomUserRequest request);
  $async.Future<$24.LiveSSEResponse> liveSSE($pb.ServerContext ctx, $24.LiveSSERequest request);
  $async.Future<$24.CloseShopAllLiveResponse> closeShopAllLive($pb.ServerContext ctx, $24.CloseShopAllLiveRequest request);
  $async.Future<$24.UpdateLiveCommentCountResponse> updateLiveCommentCount($pb.ServerContext ctx, $24.UpdateLiveCommentCountRequest request);
  $async.Future<$25.CreateLivePlanResponse> createLivePlan($pb.ServerContext ctx, $25.CreateLivePlanRequest request);
  $async.Future<$25.GetLivePlanResponse> getLivePlan($pb.ServerContext ctx, $25.GetLivePlanRequest request);
  $async.Future<$25.UpdateLivePlanResponse> updateLivePlan($pb.ServerContext ctx, $25.UpdateLivePlanRequest request);
  $async.Future<$25.ListLivePlanResponse> listLivePlan($pb.ServerContext ctx, $25.ListLivePlanRequest request);
  $async.Future<$25.DeleteLivePlanResponse> deleteLivePlan($pb.ServerContext ctx, $25.DeleteLivePlanRequest request);
  $async.Future<$25.CreateLivePlanProductResponse> createLivePlanProduct($pb.ServerContext ctx, $25.CreateLivePlanProductRequest request);
  $async.Future<$25.UpdateLivePlanProductResponse> updateLivePlanProduct($pb.ServerContext ctx, $25.UpdateLivePlanProductRequest request);
  $async.Future<$25.ListLivePlanProductResponse> listLivePlanProduct($pb.ServerContext ctx, $25.ListLivePlanProductRequest request);
  $async.Future<$25.DeleteLivePlanProductResponse> deleteLivePlanProduct($pb.ServerContext ctx, $25.DeleteLivePlanProductRequest request);
  $async.Future<$25.LoadLivePlanProductResponse> loadLivePlanProduct($pb.ServerContext ctx, $25.LoadLivePlanProductRequest request);
  $async.Future<$25.UpdateLiveProductStatusResponse> updateLiveProductStatus($pb.ServerContext ctx, $25.UpdateLiveProductStatusRequest request);
  $async.Future<$25.ListLiveProductStatusResponse> listLiveProductStatus($pb.ServerContext ctx, $25.ListLiveProductStatusRequest request);
  $async.Future<$25.DeleteLiveProductStatusResponse> deleteLiveProductStatus($pb.ServerContext ctx, $25.DeleteLiveProductStatusRequest request);
  $async.Future<$25.CreateLiveProductStatusResponse> createLiveProductStatus($pb.ServerContext ctx, $25.CreateLiveProductStatusRequest request);
  $async.Future<$25.GetLivingProductStatusResponse> getLivingProductStatus($pb.ServerContext ctx, $25.GetLivingProductStatusRequest request);
  $async.Future<$25.UpdateLiveProductIntroductStatusResponse> updateLiveProductIntroductStatus($pb.ServerContext ctx, $25.UpdateLiveProductIntroductStatusRequest request);
  $async.Future<$28.CreateLiveTextResponse> createLiveText($pb.ServerContext ctx, $28.CreateLiveTextRequest request);
  $async.Future<$28.UpdateLiveTextResponse> updateLiveText($pb.ServerContext ctx, $28.UpdateLiveTextRequest request);
  $async.Future<$28.ListLiveTextResponse> listLiveText($pb.ServerContext ctx, $28.ListLiveTextRequest request);
  $async.Future<$28.GetLiveTextResponse> getLiveText($pb.ServerContext ctx, $28.GetLiveTextRequest request);
  $async.Future<$28.DeleteLiveTextsResponse> deleteLiveTexts($pb.ServerContext ctx, $28.DeleteLiveTextsRequest request);
  $async.Future<$24.GetLiveChartDataResponse> getLiveChartData($pb.ServerContext ctx, $24.GetLiveChartDataRequest request);
  $async.Future<$29.GetEvaluateSelectorResponse> getEvaluateSelector($pb.ServerContext ctx, $29.GetEvaluateSelectorRequest request);
  $async.Future<$29.ListPersonalEvaluateResponse> listPersonalEvaluate($pb.ServerContext ctx, $29.ListPersonalEvaluateRequest request);
  $async.Future<$29.GetEvaluateDetailResponse> getEvaluateDetail($pb.ServerContext ctx, $29.GetEvaluateDetailRequest request);
  $async.Future<$29.SubmitEvaluateResponse> submitEvaluate($pb.ServerContext ctx, $29.SubmitEvaluateRequest request);
  $async.Future<$29.ListUnevaluatedRoomResponse> listUnevaluatedRoom($pb.ServerContext ctx, $29.ListUnevaluatedRoomRequest request);
  $async.Future<$29.ListStudentEvalutionsResponse> listStudentEvaluations($pb.ServerContext ctx, $29.ListStudentEvalutionsRequest request);
  $async.Future<$29.IgnoreLiveEvaluationResponse> ignoreEvaluation($pb.ServerContext ctx, $29.IgnoreLiveEvaluationRequest request);
  $async.Future<$29.GetRankResponse> getRank($pb.ServerContext ctx, $29.GetRankRequest request);
  $async.Future<$24.RecordLiveCallbackResponse> recordLiveCallback($pb.ServerContext ctx, $24.RecordLiveCallbackRequest request);
  $async.Future<$24.VideoToTextCallbackResponse> videoToTextCallback($pb.ServerContext ctx, $24.VideoToTextCallbackRequest request);
  $async.Future<$24.LiveStreamCallbackResponse> liveStreamCallback($pb.ServerContext ctx, $24.LiveStreamCallbackRequest request);
  $async.Future<$29.RegenerationAiFeedbackResponse> regenerationAiFeedback($pb.ServerContext ctx, $29.RegenerationAiFeedbackRequest request);
  $async.Future<$29.SubmitUserAttitudeForAIResultResponse> submitUserAttitudeForAiResult($pb.ServerContext ctx, $29.SubmitUserAttitudeForAIResultRequest request);
  $async.Future<$25.PreheatResponse> preheatProduct($pb.ServerContext ctx, $25.PreheatRequest request);
  $async.Future<$25.PublicPriceResponse> publicPrice($pb.ServerContext ctx, $25.PublicPriceRequest request);
  $async.Future<$30.CreateTenantResponse> createTenant($pb.ServerContext ctx, $30.CreateTenantRequest request);
  $async.Future<$30.GetTenantResponse> getTenant($pb.ServerContext ctx, $30.GetTenantRequest request);
  $async.Future<$30.UpdateTenantResponse> updateTenant($pb.ServerContext ctx, $30.UpdateTenantRequest request);
  $async.Future<$30.DeleteTenantResponse> deleteTenant($pb.ServerContext ctx, $30.DeleteTenantRequest request);
  $async.Future<$30.ListTenantResponse> listTenant($pb.ServerContext ctx, $30.ListTenantRequest request);
  $async.Future<$30.GetTenantOrgResponse> getTenantOrg($pb.ServerContext ctx, $30.GetTenantOrgRequest request);
  $async.Future<$30.EnterTenantResponse> enterTenant($pb.ServerContext ctx, $30.EnterTenantRequest request);
  $async.Future<$30.ExitTenantResponse> exitTenant($pb.ServerContext ctx, $30.ExitTenantRequest request);
  $async.Future<$30.InitTenantResponse> initTenant($pb.ServerContext ctx, $30.InitTenantRequest request);
  $async.Future<$31.CreateTenantDeptResponse> createTenantDept($pb.ServerContext ctx, $31.CreateTenantDeptRequest request);
  $async.Future<$31.UpdateTenantDeptResponse> updateTenantDept($pb.ServerContext ctx, $31.UpdateTenantDeptRequest request);
  $async.Future<$31.DeleteTenantDeptResponse> deleteTenantDept($pb.ServerContext ctx, $31.DeleteTenantDeptRequest request);
  $async.Future<$31.GetTenantDeptResponse> getTenantDept($pb.ServerContext ctx, $31.GetTenantDeptRequest request);
  $async.Future<$31.GetTenantDeptTypeResponse> getTenantDeptType($pb.ServerContext ctx, $31.GetTenantDeptTypeRequest request);
  $async.Future<$31.ListTenantDeptResponse> listTenantDept($pb.ServerContext ctx, $31.ListTenantDeptRequest request);
  $async.Future<$32.CreateTenantUserResponse> createTenantUser($pb.ServerContext ctx, $32.CreateTenantUserRequest request);
  $async.Future<$32.DeleteTenantUserResponse> deleteTenantUser($pb.ServerContext ctx, $32.DeleteTenantUserRequest request);
  $async.Future<$32.UpdateTenantUserResponse> updateTenantUser($pb.ServerContext ctx, $32.UpdateTenantUserRequest request);
  $async.Future<$32.GetTenantUserResponse> getTenantUser($pb.ServerContext ctx, $32.GetTenantUserRequest request);
  $async.Future<$32.ListTenantUserResponse> listTenantUser($pb.ServerContext ctx, $32.ListTenantUserRequest request);
  $async.Future<$32.ListTenantStudentResponse> listTenantStudent($pb.ServerContext ctx, $32.ListTenantStudentRequest request);
  $async.Future<$32.UpdateTenantUserPasswordResponse> updateTenantUserPassword($pb.ServerContext ctx, $32.UpdateTenantUserPasswordRequest request);
  $async.Future<$33.UpdateTenantConfigResponse> updateTenantConfig($pb.ServerContext ctx, $33.UpdateTenantConfigRequest request);
  $async.Future<$33.ListTenantConfigResponse> listTenantConfig($pb.ServerContext ctx, $33.ListTenantConfigRequest request);
  $async.Future<$34.CreateShortVideoResponse> createShortVideo($pb.ServerContext ctx, $34.CreateShortVideoRequest request);
  $async.Future<$34.StageShortVideoResponse> stageShortVideo($pb.ServerContext ctx, $34.StageShortVideoRequest request);
  $async.Future<$34.ListMyShortVideoResponse> listMyShortVideo($pb.ServerContext ctx, $34.ListMyShortVideoRequest request);
  $async.Future<$34.ListMyStageVideoResponse> listMyStageVideo($pb.ServerContext ctx, $34.ListMyStageVideoRequest request);
  $async.Future<$34.ListMyLikeVideoResponse> listMyLikeVideo($pb.ServerContext ctx, $34.ListMyLikeVideoRequest request);
  $async.Future<$34.ListMyFavoriteVideoResponse> listMyFavoriteVideo($pb.ServerContext ctx, $34.ListMyFavoriteVideoRequest request);
  $async.Future<$34.GetShortVideoResponse> getShortVideo($pb.ServerContext ctx, $34.GetShortVideoRequest request);
  $async.Future<$34.UpdateShortVideoResponse> updateShortVideo($pb.ServerContext ctx, $34.UpdateShortVideoRequest request);
  $async.Future<$34.DeleteShortVideoResponse> deleteShortVideo($pb.ServerContext ctx, $34.DeleteShortVideoRequest request);
  $async.Future<$34.GetStageVideoResponse> getStageVideo($pb.ServerContext ctx, $34.GetStageVideoRequest request);
  $async.Future<$34.DeleteStageVideoResponse> deleteStageVideo($pb.ServerContext ctx, $34.DeleteStageVideoRequest request);
  $async.Future<$34.UpdateStageVideoResponse> updateStageVideo($pb.ServerContext ctx, $34.UpdateStageVideoRequest request);
  $async.Future<$34.ManagementListShortVideoResponse> managementListShortVideo($pb.ServerContext ctx, $34.ManagementListShortVideoRequest request);
  $async.Future<$34.ManagementCensorShortVideoResponse> managementCensorShortVideo($pb.ServerContext ctx, $34.ManagementCensorShortVideoRequest request);
  $async.Future<$34.ManagementDeleteShortVideoResponse> managementDeleteShortVideo($pb.ServerContext ctx, $34.ManagementDeleteShortVideoRequest request);
  $async.Future<$34.ListShortVideoResponse> listShortVideo($pb.ServerContext ctx, $34.ListShortVideoRequest request);
  $async.Future<$34.LikeShortVideoResponse> likeShortVideo($pb.ServerContext ctx, $34.LikeShortVideoRequest request);
  $async.Future<$34.FavoriteShortVideoResponse> favoriteShortVideo($pb.ServerContext ctx, $34.FavoriteShortVideoRequest request);
  $async.Future<$34.CreateShortVideoCommentResponse> createShortVideoComment($pb.ServerContext ctx, $34.CreateShortVideoCommentRequest request);
  $async.Future<$34.DeleteShortVideoCommentResponse> deleteShortVideoComment($pb.ServerContext ctx, $34.DeleteShortVideoCommentRequest request);
  $async.Future<$34.ListShortVideoCommentResponse> listShortVideoComment($pb.ServerContext ctx, $34.ListShortVideoCommentRequest request);
  $async.Future<$35.CreateCouponResponse> createCoupon($pb.ServerContext ctx, $35.CreateCouponRequest request);
  $async.Future<$35.ListCouponResponse> listCoupon($pb.ServerContext ctx, $35.ListCouponRequest request);
  $async.Future<$35.GetCouponDetailResponse> couponDetail($pb.ServerContext ctx, $35.GetCouponDetailRequest request);
  $async.Future<$35.UpdateCouponResponse> updateCoupon($pb.ServerContext ctx, $35.UpdateCouponRequest request);
  $async.Future<$35.DeleteCouponResponse> deleteCoupon($pb.ServerContext ctx, $35.DeleteCouponRequest request);
  $async.Future<$35.AbolishCouponResponse> abolishCoupon($pb.ServerContext ctx, $35.AbolishCouponRequest request);
  $async.Future<$35.UpdateCouponDistributionStatusResponse> updateCouponDistributionStatus($pb.ServerContext ctx, $35.UpdateCouponDistributionStatusRequest request);
  $async.Future<$35.ClaimCouponResponse> claimCoupon($pb.ServerContext ctx, $35.ClaimCouponRequest request);
  $async.Future<$35.ListMyCouponResponse> listMyCoupon($pb.ServerContext ctx, $35.ListMyCouponRequest request);
  $async.Future<$36.CreateActivityResponse> createActivity($pb.ServerContext ctx, $36.CreateActivityRequest request);
  $async.Future<$36.ListActivityResponse> listActivity($pb.ServerContext ctx, $36.ListActivityRequest request);
  $async.Future<$36.GetActivityDetailResponse> activityDetail($pb.ServerContext ctx, $36.GetActivityDetailRequest request);
  $async.Future<$36.UpdateActivityResponse> updateActivity($pb.ServerContext ctx, $36.UpdateActivityRequest request);
  $async.Future<$36.DeleteActivityResponse> deleteActivity($pb.ServerContext ctx, $36.DeleteActivityRequest request);
  $async.Future<$36.DisableActivityResponse> disableActivity($pb.ServerContext ctx, $36.DisableActivityRequest request);
  $async.Future<$37.CreateCourseMaterialBoxResponse> createCourseMaterialBox($pb.ServerContext ctx, $37.CreateCourseMaterialBoxRequest request);
  $async.Future<$37.UpdateCourseMaterialBoxResponse> updateCourseMaterialBox($pb.ServerContext ctx, $37.UpdateCourseMaterialBoxRequest request);
  $async.Future<$37.ListCourseMaterialBoxResponse> listCourseMaterialBox($pb.ServerContext ctx, $37.ListCourseMaterialBoxRequest request);
  $async.Future<$37.DeleteCourseMaterialBoxResponse> deleteCourseMaterialBox($pb.ServerContext ctx, $37.DeleteCourseMaterialBoxRequest request);
  $async.Future<$37.UploadCourseMaterialResponse> uploadCourseMaterial($pb.ServerContext ctx, $37.UploadCourseMaterialRequest request);
  $async.Future<$37.ListCourseMaterialResponse> listCourseMaterial($pb.ServerContext ctx, $37.ListCourseMaterialRequest request);
  $async.Future<$37.DeleteCourseMaterialResponse> deleteCourseMaterial($pb.ServerContext ctx, $37.DeleteCourseMaterialRequest request);
  $async.Future<$38.GetCourseModuleCodeResponse> getCourseModuleCode($pb.ServerContext ctx, $38.GetCourseModuleCodeRequest request);
  $async.Future<$38.GetCourseChapterCodeResponse> getCourseChapterCode($pb.ServerContext ctx, $38.GetCourseChapterCodeRequest request);
  $async.Future<$38.CreateCourseModuleResponse> createCourseModule($pb.ServerContext ctx, $38.CreateCourseModuleRequest request);
  $async.Future<$38.GetCourseModuleResponse> getCourseModule($pb.ServerContext ctx, $38.GetCourseModuleRequest request);
  $async.Future<$38.UpdateCourseModuleResponse> updateCourseModule($pb.ServerContext ctx, $38.UpdateCourseModuleRequest request);
  $async.Future<$38.DeleteCourseModuleResponse> deleteCourseModule($pb.ServerContext ctx, $38.DeleteCourseModuleRequest request);
  $async.Future<$38.ListCourseModuleResponse> listCourseModule($pb.ServerContext ctx, $38.ListCourseModuleRequest request);
  $async.Future<$39.ListLatestCourseResponse> listLatestCourse($pb.ServerContext ctx, $39.ListLatestCourseRequest request);
  $async.Future<$39.ListHotestCourseResponse> listHotestCourse($pb.ServerContext ctx, $39.ListHotestCourseRequest request);
  $async.Future<$40.CreateCmCourseResponse> createCmCourse($pb.ServerContext ctx, $40.CreateCmCourseRequest request);
  $async.Future<$40.PreviewCmCourseResponse> previewCmCourse($pb.ServerContext ctx, $40.PreviewCmCourseRequest request);
  $async.Future<$41.CreateNmCourseChapterResourceResponse> createNmCourseResource($pb.ServerContext ctx, $41.CreateNmCourseChapterResourceRequest request);
  $async.Future<$41.CreateNmCourseChapterResponse> createNmCourseChapter($pb.ServerContext ctx, $41.CreateNmCourseChapterRequest request);
  $async.Future<$41.CreateNmCourseResponse> createNmCourse($pb.ServerContext ctx, $41.CreateNmCourseRequest request);
  $async.Future<$41.ListNmCourseResponse> listNmCourse($pb.ServerContext ctx, $41.ListNmCourseRequest request);
  $async.Future<$41.NmCourseDetailResponse> nmCourseDetail($pb.ServerContext ctx, $41.NmCourseDetailRequest request);
  $async.Future<$41.DeleteNmCourseResponse> deleteNmCourse($pb.ServerContext ctx, $41.DeleteNmCourseRequest request);
  $async.Future<$39.CreateCourseResponse> createCourse($pb.ServerContext ctx, $39.CreateCourseRequest request);
  $async.Future<$39.GetCourseResponse> getCourse($pb.ServerContext ctx, $39.GetCourseRequest request);
  $async.Future<$39.UpdateCourseResponse> updateCourse($pb.ServerContext ctx, $39.UpdateCourseRequest request);
  $async.Future<$39.DeleteCourseResponse> deleteCourse($pb.ServerContext ctx, $39.DeleteCourseRequest request);
  $async.Future<$39.ListCourseResponse> listCourse($pb.ServerContext ctx, $39.ListCourseRequest request);
  $async.Future<$42.CreateKnowledgeGraphResponse> createKnowledgeGraph($pb.ServerContext ctx, $42.CreateKnowledgeGraphRequest request);
  $async.Future<$42.GetKnowledgeGraphResponse> getKnowledgeGraph($pb.ServerContext ctx, $42.GetKnowledgeGraphRequest request);
  $async.Future<$42.GetKnowledgeGraphNodeResponse> getKnowledgeGraphNode($pb.ServerContext ctx, $42.GetKnowledgeGraphNodeRequest request);
  $async.Future<$39.GetMajorCodeResponse> getMajorCode($pb.ServerContext ctx, $39.GetMajorCodeRequest request);
  $async.Future<$39.GetCourseIdsResponse> getCourseIds($pb.ServerContext ctx, $39.GetCourseIdsRequest request);
  $async.Future<$43.EnrollCourseResponse> enrollCourse($pb.ServerContext ctx, $43.EnrollCourseRequest request);
  $async.Future<$43.DeleteMyCourseResponse> deleteMyCourse($pb.ServerContext ctx, $43.DeleteMyCourseRequest request);
  $async.Future<$43.UpdateCourseProgressResponse> updateCourseProgress($pb.ServerContext ctx, $43.UpdateCourseProgressRequest request);
  $async.Future<$43.ListMyCourseResponse> listMyCourse($pb.ServerContext ctx, $43.ListMyCourseRequest request);
  $async.Future<$44.ListTeachingPlanResponse> listTeachingPlan($pb.ServerContext ctx, $44.ListTeachingPlanRequest request);
  $async.Future<$44.CreateTeachingPlanResponse> createTeachingPlan($pb.ServerContext ctx, $44.CreateTeachingPlanRequest request);
  $async.Future<$44.UpdateTeachingPlanResponse> updateTeachingPlan($pb.ServerContext ctx, $44.UpdateTeachingPlanRequest request);
  $async.Future<$44.DeleteTeachingPlanResponse> deleteTeachingPlan($pb.ServerContext ctx, $44.DeleteTeachingPlanRequest request);
  $async.Future<$44.UpdateTeachingCourseProgressResponse> updateTeachingCourseProgress($pb.ServerContext ctx, $44.UpdateTeachingCourseProgressRequest request);
  $async.Future<$45.CreateEduSchemeResponse> createEduScheme($pb.ServerContext ctx, $45.CreateEduSchemeRequest request);
  $async.Future<$45.UpdateEduSchemeResponse> updateEduScheme($pb.ServerContext ctx, $45.UpdateEduSchemeRequest request);
  $async.Future<$45.ListEduSchemeResponse> listEduScheme($pb.ServerContext ctx, $45.ListEduSchemeRequest request);
  $async.Future<$45.EduSchemeDetailResponse> eduSchemeDetail($pb.ServerContext ctx, $45.EduSchemeDetailRequest request);
  $async.Future<$45.DeleteEduSchemeResponse> deleteEduScheme($pb.ServerContext ctx, $45.DeleteEduSchemeRequest request);
  $async.Future<$45.DistributeEduSchemeResponse> distributeEduScheme($pb.ServerContext ctx, $45.DistributeEduSchemeRequest request);
  $async.Future<$45.GetEduSchemeLikeCourseResponse> getEduSchemeLikeCourse($pb.ServerContext ctx, $45.GetEduSchemeLikeCourseRequest request);
  $async.Future<$46.GetAndroidQRCodeResponse> getAndroidQRcode($pb.ServerContext ctx, $46.GetAndroidQRCodeRequest request);
  $async.Future<$47.CreateJobResponse> createJob($pb.ServerContext ctx, $47.CreateJobRequest request);
  $async.Future<$47.UpdateJobResponse> updateJob($pb.ServerContext ctx, $47.UpdateJobRequest request);
  $async.Future<$47.DeleteJobResponse> deleteJob($pb.ServerContext ctx, $47.DeleteJobRequest request);
  $async.Future<$47.ListJobResponse> listJob($pb.ServerContext ctx, $47.ListJobRequest request);
  $async.Future<$48.GetSchoolLiveTrafficChartResponse> getSchooLiveChart($pb.ServerContext ctx, $48.GetSchoolLiveTrafficChartRequest request);
  $async.Future<$48.ListSchoolLiveTrafficResponse> listSchooLiveTraffic($pb.ServerContext ctx, $48.ListSchoolLiveTrafficRequest request);
  $async.Future<$48.GetAllLiveTrafficResponse> getLiveAllTraffic($pb.ServerContext ctx, $48.GetAllLiveTrafficRequest request);
  $async.Future<$48.ListTenantLiveTrafficConfigResponse> listTenantTrafficConfig($pb.ServerContext ctx, $48.ListTenantLiveTrafficConfigRequest request);
  $async.Future<$48.UpdateTenantLiveTrafficConfigResponse> updateTenantTrafficConfig($pb.ServerContext ctx, $48.UpdateTenantLiveTrafficConfigRequest request);

  $pb.GeneratedMessage createRequest($core.String methodName) {
    switch (methodName) {
      case 'CreateExample': return $0.CreateExampleRequest();
      case 'GetExample': return $0.GetExampleRequest();
      case 'UpdateExample': return $0.UpdateExampleRequest();
      case 'ListExample': return $0.ListExampleRequest();
      case 'DeleteExample': return $0.DeleteExampleRequest();
      case 'Login': return $1.LoginRequest();
      case 'Logout': return $1.LogoutRequest();
      case 'GetVerifyCode': return $1.GetVerifyCodeRequest();
      case 'CheckVerifyCode': return $1.CheckVerifyCodeRequest();
      case 'GetUser': return $1.GetUserRequest();
      case 'LoginWithPassword': return $1.LoginWithPasswordRequest();
      case 'UpdatePassword': return $1.UpdatePasswordRequest();
      case 'UpdateUser': return $1.UpdateUserRequest();
      case 'UpdatePhone': return $1.UpdatePhoneRequest();
      case 'UpdateUserTenant': return $1.UpdateUserTenantRequest();
      case 'FollowUser': return $1.FollowUserRequest();
      case 'ListMyFollowing': return $1.ListMyFollowingRequest();
      case 'ListMyFollower': return $1.ListMyFollowerRequest();
      case 'ListMyFriend': return $1.ListMyFriendRequest();
      case 'GetMySocialSummary': return $1.GetMySocialSummaryRequest();
      case 'GetUserPagePermission': return $1.GetUserPagePermissionRequest();
      case 'CreateRolePagePermission': return $1.CreateRolePagePermissionRequest();
      case 'UpdateRolePagePermission': return $1.UpdateRolePagePermissionRequest();
      case 'GetRolePagePermission': return $1.GetRolePagePermissionRequest();
      case 'AddAddress': return $2.AddAddressRequest();
      case 'DeleteAddress': return $2.DeleteAddressRequest();
      case 'UpdateAddress': return $2.UpdateAddressRequest();
      case 'GetAddress': return $2.GetAddressRequest();
      case 'ListAddress': return $2.ListAddressRequest();
      case 'ListUserByRole': return $1.ListUserByRoleRequest();
      case 'ListPermission': return $1.ListPermissionRequest();
      case 'ListRole': return $1.ListRoleRequest();
      case 'GiveRolePermission': return $1.GiveRolePermissionRequest();
      case 'RemoveRolePermission': return $1.RemoveRolePermissionRequest();
      case 'CreateRole': return $1.CreateRoleRequest();
      case 'DeleteRole': return $1.DeleteRoleRequest();
      case 'ListResource': return $1.ListResourceRequest();
      case 'GetRoleType': return $1.GetRoleTypeRequest();
      case 'GetRoleTemplate': return $3.GetRoleTemplateRequest();
      case 'UpdateRoleTemplate': return $3.UpdateRoleTemplateRequest();
      case 'CreateShop': return $4.CreateShopRequest();
      case 'GetShop': return $4.GetShopRequest();
      case 'UpdateShop': return $4.UpdateShopRequest();
      case 'ListShop': return $4.ListShopRequest();
      case 'DeleteShop': return $4.DeleteShopRequest();
      case 'ListOperationMetrics': return $5.ListOperationMetricsRequest();
      case 'GetShopQrcode': return $4.GetShopQrcodeRequest();
      case 'UpdateShopManager': return $4.UpdateShopManagerRequest();
      case 'GetShopBusinessData': return $4.GetShopBusinessDataRequest();
      case 'AddShopAccess': return $4.AddShopAccessRequest();
      case 'RemoveShopAccess': return $4.RemoveShopAccessRequest();
      case 'VerifyField': return $4.VerifyFieldRequest();
      case 'ListShopAccess': return $4.ListShopAccessRequest();
      case 'AddShopCategory': return $4.AddShopCategoryRequest();
      case 'GetShopCategory': return $4.GetShopCategoryRequest();
      case 'RemoveShopCategory': return $4.RemoveShopCategoryRequest();
      case 'AddFreightTemplate': return $6.CreateTemplateRequest();
      case 'GetFreightTemplate': return $6.GetTemplateRequest();
      case 'UpdateFreightTemplate': return $6.UpdateTemplateRequest();
      case 'DeleteFreightTemplate': return $6.DeleteTemplateRequest();
      case 'ListFreightTemplate': return $6.ListTemplateRequest();
      case 'ListQualification': return $4.ListShopQualificationRequest();
      case 'GetMallIndex': return $7.MallIndexRequest();
      case 'CreateCategory': return $8.CreateCategoryRequest();
      case 'GetCategory': return $8.GetCategoryRequest();
      case 'UpdateCategory': return $8.UpdateCategoryRequest();
      case 'ListCategory': return $8.ListCategoryRequest();
      case 'DeleteCategory': return $8.DeleteCategoryRequest();
      case 'ListCategoryQualification': return $9.ListCategoryQualificationRequest();
      case 'CreateProduct': return $10.CreateProductRequest();
      case 'GetProduct': return $10.GetProductRequest();
      case 'UpdateProduct': return $10.UpdateProductRequest();
      case 'ListProduct': return $10.ListProductRequest();
      case 'ListProductByIDs': return $10.ListProductByProductIDsRequest();
      case 'DeleteProduct': return $10.DeleteProductRequest();
      case 'UploadMultiImage': return $10.UploadMultiImageRequest();
      case 'DeleteImageById': return $10.DeleteImageRequest();
      case 'BindAttribute': return $10.BindAttributeRequest();
      case 'PublishProduct': return $10.PublishProductRequest();
      case 'OffShelfProductInBatches': return $10.OffSelfProductsRequest();
      case 'DeleteProductInBatches': return $10.DeleteProductsRequest();
      case 'ChangeProductsState': return $10.ChangeProductStateRequest();
      case 'SaveProductImageInfo': return $10.SaveImageInfoRequest();
      case 'CreateSku': return $11.CreateSkuRequest();
      case 'GetSku': return $11.GetSkuRequest();
      case 'UpdateSku': return $11.UpdateSkuRequest();
      case 'ListSku': return $11.ListSkuRequest();
      case 'DeleteSku': return $11.DeleteSkuRequest();
      case 'CreateAttribute': return $12.CreateAttributeRequest();
      case 'GetAttribute': return $12.GetAttributeRequest();
      case 'ListAttribute': return $12.ListAttributeRequest();
      case 'DeleteAttribute': return $12.DeleteAttributeRequest();
      case 'AddAttributeValue': return $12.AddAttributeValueRequest();
      case 'DeleteAttributeValue': return $12.DeleteAttributeValueRequest();
      case 'CreateOrder': return $13.CreateOrderRequest();
      case 'GetOrder': return $13.GetOrderRequest();
      case 'UpdateOrder': return $13.UpdateOrderRequest();
      case 'ListOrder': return $13.ListOrderRequest();
      case 'DeleteOrder': return $13.DeleteOrderRequest();
      case 'ShipGoods': return $13.ShipGoodsRequest();
      case 'ConfirmReceiptGoods': return $13.ConfirmReceiptGoodsRequest();
      case 'CancelOrder': return $13.CancelOrderRequest();
      case 'ShipGoodsInBatches': return $13.ShipGoodsInBatchesRequest();
      case 'FreeShippingInBatches': return $13.FreeShippingInBatchesRequest();
      case 'ListShopSummary': return $4.ListShopSummaryRequest();
      case 'ListShopBySellerID': return $4.ListShopBySellerIDRequest();
      case 'CreateCart': return $14.AddCartRequest();
      case 'GetCart': return $14.GetCartRequest();
      case 'UpdateCart': return $14.UpdateCartRequest();
      case 'DeleteCart': return $14.DeleteCartRequest();
      case 'UploadAttachment': return $15.UploadAttachmentRequest();
      case 'SaveAttachment': return $15.SaveAttachmentRequest();
      case 'ListAttachment': return $15.ListAttachmentRequest();
      case 'DeleteAttachment': return $15.DeleteAttachmentRequest();
      case 'CreateSeller': return $16.CreateSellerRequest();
      case 'CreatePayment': return $17.CreatePaymentRequest();
      case 'GetPayment': return $17.GetPaymentRequest();
      case 'UpdatePayment': return $17.UpdatePaymentRequest();
      case 'DeletePayment': return $17.DeletePaymentRequest();
      case 'CreateConfig': return $18.CreateConfigRequest();
      case 'UpdateConfig': return $18.UpdateConfigRequest();
      case 'DeleteConfig': return $18.DeleteConfigRequest();
      case 'GetConfig': return $18.GetConfigRequest();
      case 'GetSTS': return $18.GetSTSRequest();
      case 'ListTenantOrg': return $19.ListTenantOrgRequest();
      case 'GetAdminTenant': return $20.GetAdminTenantRequest();
      case 'ListAdminUser': return $20.ListAdminUserRequest();
      case 'CreateAdminUser': return $20.CreateAdminUserRequest();
      case 'UpdateAdminUser': return $20.UpdateAdminUserRequest();
      case 'DeleteAdminUser': return $20.DeleteAdminUserRequest();
      case 'WxPrepay': return $21.PrepayRequest();
      case 'CloseOrder': return $21.CloseOrderRequest();
      case 'QueryOrderById': return $21.QueryOrderByIdRequest();
      case 'QueryOrderByOutTrade': return $21.QueryOrderByOutTradeNoRequest();
      case 'AddVCurrency': return $22.AddVirtualCurrencyRequest();
      case 'RechargeCurrency': return $22.RechargeCurrencyRequest();
      case 'RechargeCurrencyInBatches': return $22.RechargeCurrencyInBatchesRequest();
      case 'GetVCurrency': return $22.GetVirtualCurrencyRequest();
      case 'ListVCurrency': return $22.ListVirtualCurrencyRequest();
      case 'ListAccountOperation': return $23.ListAccountOperationRequest();
      case 'CreateRoom': return $24.CreateRoomRequest();
      case 'GetRoom': return $24.GetRoomRequest();
      case 'UpdateRoom': return $24.UpdateRoomRequest();
      case 'ListRoom': return $24.ListRoomRequest();
      case 'DeleteRoom': return $24.DeleteRoomRequest();
      case 'ListFinishedRoom': return $24.ListFinishedRoomRequest();
      case 'GetFinishedRoom': return $24.GetFinishedRoomRequest();
      case 'Record': return $25.LiveRecordRequest();
      case 'CreateLiveUserToken': return $26.CreateLiveUserTokenRequest();
      case 'UserEnterRoom': return $27.UserEnterRoomRequest();
      case 'UserExitRoom': return $27.UserExitRoomRequest();
      case 'ListActiveRoomUser': return $27.ListActiveRoomUserRequest();
      case 'LiveSSE': return $24.LiveSSERequest();
      case 'CloseShopAllLive': return $24.CloseShopAllLiveRequest();
      case 'UpdateLiveCommentCount': return $24.UpdateLiveCommentCountRequest();
      case 'CreateLivePlan': return $25.CreateLivePlanRequest();
      case 'GetLivePlan': return $25.GetLivePlanRequest();
      case 'UpdateLivePlan': return $25.UpdateLivePlanRequest();
      case 'ListLivePlan': return $25.ListLivePlanRequest();
      case 'DeleteLivePlan': return $25.DeleteLivePlanRequest();
      case 'CreateLivePlanProduct': return $25.CreateLivePlanProductRequest();
      case 'UpdateLivePlanProduct': return $25.UpdateLivePlanProductRequest();
      case 'ListLivePlanProduct': return $25.ListLivePlanProductRequest();
      case 'DeleteLivePlanProduct': return $25.DeleteLivePlanProductRequest();
      case 'LoadLivePlanProduct': return $25.LoadLivePlanProductRequest();
      case 'UpdateLiveProductStatus': return $25.UpdateLiveProductStatusRequest();
      case 'ListLiveProductStatus': return $25.ListLiveProductStatusRequest();
      case 'DeleteLiveProductStatus': return $25.DeleteLiveProductStatusRequest();
      case 'CreateLiveProductStatus': return $25.CreateLiveProductStatusRequest();
      case 'GetLivingProductStatus': return $25.GetLivingProductStatusRequest();
      case 'UpdateLiveProductIntroductStatus': return $25.UpdateLiveProductIntroductStatusRequest();
      case 'CreateLiveText': return $28.CreateLiveTextRequest();
      case 'UpdateLiveText': return $28.UpdateLiveTextRequest();
      case 'ListLiveText': return $28.ListLiveTextRequest();
      case 'GetLiveText': return $28.GetLiveTextRequest();
      case 'DeleteLiveTexts': return $28.DeleteLiveTextsRequest();
      case 'GetLiveChartData': return $24.GetLiveChartDataRequest();
      case 'GetEvaluateSelector': return $29.GetEvaluateSelectorRequest();
      case 'ListPersonalEvaluate': return $29.ListPersonalEvaluateRequest();
      case 'GetEvaluateDetail': return $29.GetEvaluateDetailRequest();
      case 'SubmitEvaluate': return $29.SubmitEvaluateRequest();
      case 'ListUnevaluatedRoom': return $29.ListUnevaluatedRoomRequest();
      case 'ListStudentEvaluations': return $29.ListStudentEvalutionsRequest();
      case 'IgnoreEvaluation': return $29.IgnoreLiveEvaluationRequest();
      case 'GetRank': return $29.GetRankRequest();
      case 'RecordLiveCallback': return $24.RecordLiveCallbackRequest();
      case 'VideoToTextCallback': return $24.VideoToTextCallbackRequest();
      case 'LiveStreamCallback': return $24.LiveStreamCallbackRequest();
      case 'RegenerationAiFeedback': return $29.RegenerationAiFeedbackRequest();
      case 'SubmitUserAttitudeForAiResult': return $29.SubmitUserAttitudeForAIResultRequest();
      case 'PreheatProduct': return $25.PreheatRequest();
      case 'PublicPrice': return $25.PublicPriceRequest();
      case 'CreateTenant': return $30.CreateTenantRequest();
      case 'GetTenant': return $30.GetTenantRequest();
      case 'UpdateTenant': return $30.UpdateTenantRequest();
      case 'DeleteTenant': return $30.DeleteTenantRequest();
      case 'ListTenant': return $30.ListTenantRequest();
      case 'GetTenantOrg': return $30.GetTenantOrgRequest();
      case 'EnterTenant': return $30.EnterTenantRequest();
      case 'ExitTenant': return $30.ExitTenantRequest();
      case 'InitTenant': return $30.InitTenantRequest();
      case 'CreateTenantDept': return $31.CreateTenantDeptRequest();
      case 'UpdateTenantDept': return $31.UpdateTenantDeptRequest();
      case 'DeleteTenantDept': return $31.DeleteTenantDeptRequest();
      case 'GetTenantDept': return $31.GetTenantDeptRequest();
      case 'GetTenantDeptType': return $31.GetTenantDeptTypeRequest();
      case 'ListTenantDept': return $31.ListTenantDeptRequest();
      case 'CreateTenantUser': return $32.CreateTenantUserRequest();
      case 'DeleteTenantUser': return $32.DeleteTenantUserRequest();
      case 'UpdateTenantUser': return $32.UpdateTenantUserRequest();
      case 'GetTenantUser': return $32.GetTenantUserRequest();
      case 'ListTenantUser': return $32.ListTenantUserRequest();
      case 'ListTenantStudent': return $32.ListTenantStudentRequest();
      case 'UpdateTenantUserPassword': return $32.UpdateTenantUserPasswordRequest();
      case 'UpdateTenantConfig': return $33.UpdateTenantConfigRequest();
      case 'ListTenantConfig': return $33.ListTenantConfigRequest();
      case 'CreateShortVideo': return $34.CreateShortVideoRequest();
      case 'StageShortVideo': return $34.StageShortVideoRequest();
      case 'ListMyShortVideo': return $34.ListMyShortVideoRequest();
      case 'ListMyStageVideo': return $34.ListMyStageVideoRequest();
      case 'ListMyLikeVideo': return $34.ListMyLikeVideoRequest();
      case 'ListMyFavoriteVideo': return $34.ListMyFavoriteVideoRequest();
      case 'GetShortVideo': return $34.GetShortVideoRequest();
      case 'UpdateShortVideo': return $34.UpdateShortVideoRequest();
      case 'DeleteShortVideo': return $34.DeleteShortVideoRequest();
      case 'GetStageVideo': return $34.GetStageVideoRequest();
      case 'DeleteStageVideo': return $34.DeleteStageVideoRequest();
      case 'UpdateStageVideo': return $34.UpdateStageVideoRequest();
      case 'ManagementListShortVideo': return $34.ManagementListShortVideoRequest();
      case 'ManagementCensorShortVideo': return $34.ManagementCensorShortVideoRequest();
      case 'ManagementDeleteShortVideo': return $34.ManagementDeleteShortVideoRequest();
      case 'ListShortVideo': return $34.ListShortVideoRequest();
      case 'LikeShortVideo': return $34.LikeShortVideoRequest();
      case 'FavoriteShortVideo': return $34.FavoriteShortVideoRequest();
      case 'CreateShortVideoComment': return $34.CreateShortVideoCommentRequest();
      case 'DeleteShortVideoComment': return $34.DeleteShortVideoCommentRequest();
      case 'ListShortVideoComment': return $34.ListShortVideoCommentRequest();
      case 'CreateCoupon': return $35.CreateCouponRequest();
      case 'ListCoupon': return $35.ListCouponRequest();
      case 'CouponDetail': return $35.GetCouponDetailRequest();
      case 'UpdateCoupon': return $35.UpdateCouponRequest();
      case 'DeleteCoupon': return $35.DeleteCouponRequest();
      case 'AbolishCoupon': return $35.AbolishCouponRequest();
      case 'UpdateCouponDistributionStatus': return $35.UpdateCouponDistributionStatusRequest();
      case 'ClaimCoupon': return $35.ClaimCouponRequest();
      case 'ListMyCoupon': return $35.ListMyCouponRequest();
      case 'CreateActivity': return $36.CreateActivityRequest();
      case 'ListActivity': return $36.ListActivityRequest();
      case 'ActivityDetail': return $36.GetActivityDetailRequest();
      case 'UpdateActivity': return $36.UpdateActivityRequest();
      case 'DeleteActivity': return $36.DeleteActivityRequest();
      case 'DisableActivity': return $36.DisableActivityRequest();
      case 'CreateCourseMaterialBox': return $37.CreateCourseMaterialBoxRequest();
      case 'UpdateCourseMaterialBox': return $37.UpdateCourseMaterialBoxRequest();
      case 'ListCourseMaterialBox': return $37.ListCourseMaterialBoxRequest();
      case 'DeleteCourseMaterialBox': return $37.DeleteCourseMaterialBoxRequest();
      case 'UploadCourseMaterial': return $37.UploadCourseMaterialRequest();
      case 'ListCourseMaterial': return $37.ListCourseMaterialRequest();
      case 'DeleteCourseMaterial': return $37.DeleteCourseMaterialRequest();
      case 'GetCourseModuleCode': return $38.GetCourseModuleCodeRequest();
      case 'GetCourseChapterCode': return $38.GetCourseChapterCodeRequest();
      case 'CreateCourseModule': return $38.CreateCourseModuleRequest();
      case 'GetCourseModule': return $38.GetCourseModuleRequest();
      case 'UpdateCourseModule': return $38.UpdateCourseModuleRequest();
      case 'DeleteCourseModule': return $38.DeleteCourseModuleRequest();
      case 'ListCourseModule': return $38.ListCourseModuleRequest();
      case 'ListLatestCourse': return $39.ListLatestCourseRequest();
      case 'ListHotestCourse': return $39.ListHotestCourseRequest();
      case 'CreateCmCourse': return $40.CreateCmCourseRequest();
      case 'PreviewCmCourse': return $40.PreviewCmCourseRequest();
      case 'CreateNmCourseResource': return $41.CreateNmCourseChapterResourceRequest();
      case 'CreateNmCourseChapter': return $41.CreateNmCourseChapterRequest();
      case 'CreateNmCourse': return $41.CreateNmCourseRequest();
      case 'ListNmCourse': return $41.ListNmCourseRequest();
      case 'NmCourseDetail': return $41.NmCourseDetailRequest();
      case 'DeleteNmCourse': return $41.DeleteNmCourseRequest();
      case 'CreateCourse': return $39.CreateCourseRequest();
      case 'GetCourse': return $39.GetCourseRequest();
      case 'UpdateCourse': return $39.UpdateCourseRequest();
      case 'DeleteCourse': return $39.DeleteCourseRequest();
      case 'ListCourse': return $39.ListCourseRequest();
      case 'CreateKnowledgeGraph': return $42.CreateKnowledgeGraphRequest();
      case 'GetKnowledgeGraph': return $42.GetKnowledgeGraphRequest();
      case 'GetKnowledgeGraphNode': return $42.GetKnowledgeGraphNodeRequest();
      case 'GetMajorCode': return $39.GetMajorCodeRequest();
      case 'GetCourseIds': return $39.GetCourseIdsRequest();
      case 'EnrollCourse': return $43.EnrollCourseRequest();
      case 'DeleteMyCourse': return $43.DeleteMyCourseRequest();
      case 'UpdateCourseProgress': return $43.UpdateCourseProgressRequest();
      case 'ListMyCourse': return $43.ListMyCourseRequest();
      case 'ListTeachingPlan': return $44.ListTeachingPlanRequest();
      case 'CreateTeachingPlan': return $44.CreateTeachingPlanRequest();
      case 'UpdateTeachingPlan': return $44.UpdateTeachingPlanRequest();
      case 'DeleteTeachingPlan': return $44.DeleteTeachingPlanRequest();
      case 'UpdateTeachingCourseProgress': return $44.UpdateTeachingCourseProgressRequest();
      case 'CreateEduScheme': return $45.CreateEduSchemeRequest();
      case 'UpdateEduScheme': return $45.UpdateEduSchemeRequest();
      case 'ListEduScheme': return $45.ListEduSchemeRequest();
      case 'EduSchemeDetail': return $45.EduSchemeDetailRequest();
      case 'DeleteEduScheme': return $45.DeleteEduSchemeRequest();
      case 'DistributeEduScheme': return $45.DistributeEduSchemeRequest();
      case 'GetEduSchemeLikeCourse': return $45.GetEduSchemeLikeCourseRequest();
      case 'GetAndroidQRcode': return $46.GetAndroidQRCodeRequest();
      case 'CreateJob': return $47.CreateJobRequest();
      case 'UpdateJob': return $47.UpdateJobRequest();
      case 'DeleteJob': return $47.DeleteJobRequest();
      case 'ListJob': return $47.ListJobRequest();
      case 'GetSchooLiveChart': return $48.GetSchoolLiveTrafficChartRequest();
      case 'ListSchooLiveTraffic': return $48.ListSchoolLiveTrafficRequest();
      case 'GetLiveAllTraffic': return $48.GetAllLiveTrafficRequest();
      case 'ListTenantTrafficConfig': return $48.ListTenantLiveTrafficConfigRequest();
      case 'UpdateTenantTrafficConfig': return $48.UpdateTenantLiveTrafficConfigRequest();
      default: throw $core.ArgumentError('Unknown method: $methodName');
    }
  }

  $async.Future<$pb.GeneratedMessage> handleCall($pb.ServerContext ctx, $core.String methodName, $pb.GeneratedMessage request) {
    switch (methodName) {
      case 'CreateExample': return this.createExample(ctx, request as $0.CreateExampleRequest);
      case 'GetExample': return this.getExample(ctx, request as $0.GetExampleRequest);
      case 'UpdateExample': return this.updateExample(ctx, request as $0.UpdateExampleRequest);
      case 'ListExample': return this.listExample(ctx, request as $0.ListExampleRequest);
      case 'DeleteExample': return this.deleteExample(ctx, request as $0.DeleteExampleRequest);
      case 'Login': return this.login(ctx, request as $1.LoginRequest);
      case 'Logout': return this.logout(ctx, request as $1.LogoutRequest);
      case 'GetVerifyCode': return this.getVerifyCode(ctx, request as $1.GetVerifyCodeRequest);
      case 'CheckVerifyCode': return this.checkVerifyCode(ctx, request as $1.CheckVerifyCodeRequest);
      case 'GetUser': return this.getUser(ctx, request as $1.GetUserRequest);
      case 'LoginWithPassword': return this.loginWithPassword(ctx, request as $1.LoginWithPasswordRequest);
      case 'UpdatePassword': return this.updatePassword(ctx, request as $1.UpdatePasswordRequest);
      case 'UpdateUser': return this.updateUser(ctx, request as $1.UpdateUserRequest);
      case 'UpdatePhone': return this.updatePhone(ctx, request as $1.UpdatePhoneRequest);
      case 'UpdateUserTenant': return this.updateUserTenant(ctx, request as $1.UpdateUserTenantRequest);
      case 'FollowUser': return this.followUser(ctx, request as $1.FollowUserRequest);
      case 'ListMyFollowing': return this.listMyFollowing(ctx, request as $1.ListMyFollowingRequest);
      case 'ListMyFollower': return this.listMyFollower(ctx, request as $1.ListMyFollowerRequest);
      case 'ListMyFriend': return this.listMyFriend(ctx, request as $1.ListMyFriendRequest);
      case 'GetMySocialSummary': return this.getMySocialSummary(ctx, request as $1.GetMySocialSummaryRequest);
      case 'GetUserPagePermission': return this.getUserPagePermission(ctx, request as $1.GetUserPagePermissionRequest);
      case 'CreateRolePagePermission': return this.createRolePagePermission(ctx, request as $1.CreateRolePagePermissionRequest);
      case 'UpdateRolePagePermission': return this.updateRolePagePermission(ctx, request as $1.UpdateRolePagePermissionRequest);
      case 'GetRolePagePermission': return this.getRolePagePermission(ctx, request as $1.GetRolePagePermissionRequest);
      case 'AddAddress': return this.addAddress(ctx, request as $2.AddAddressRequest);
      case 'DeleteAddress': return this.deleteAddress(ctx, request as $2.DeleteAddressRequest);
      case 'UpdateAddress': return this.updateAddress(ctx, request as $2.UpdateAddressRequest);
      case 'GetAddress': return this.getAddress(ctx, request as $2.GetAddressRequest);
      case 'ListAddress': return this.listAddress(ctx, request as $2.ListAddressRequest);
      case 'ListUserByRole': return this.listUserByRole(ctx, request as $1.ListUserByRoleRequest);
      case 'ListPermission': return this.listPermission(ctx, request as $1.ListPermissionRequest);
      case 'ListRole': return this.listRole(ctx, request as $1.ListRoleRequest);
      case 'GiveRolePermission': return this.giveRolePermission(ctx, request as $1.GiveRolePermissionRequest);
      case 'RemoveRolePermission': return this.removeRolePermission(ctx, request as $1.RemoveRolePermissionRequest);
      case 'CreateRole': return this.createRole(ctx, request as $1.CreateRoleRequest);
      case 'DeleteRole': return this.deleteRole(ctx, request as $1.DeleteRoleRequest);
      case 'ListResource': return this.listResource(ctx, request as $1.ListResourceRequest);
      case 'GetRoleType': return this.getRoleType(ctx, request as $1.GetRoleTypeRequest);
      case 'GetRoleTemplate': return this.getRoleTemplate(ctx, request as $3.GetRoleTemplateRequest);
      case 'UpdateRoleTemplate': return this.updateRoleTemplate(ctx, request as $3.UpdateRoleTemplateRequest);
      case 'CreateShop': return this.createShop(ctx, request as $4.CreateShopRequest);
      case 'GetShop': return this.getShop(ctx, request as $4.GetShopRequest);
      case 'UpdateShop': return this.updateShop(ctx, request as $4.UpdateShopRequest);
      case 'ListShop': return this.listShop(ctx, request as $4.ListShopRequest);
      case 'DeleteShop': return this.deleteShop(ctx, request as $4.DeleteShopRequest);
      case 'ListOperationMetrics': return this.listOperationMetrics(ctx, request as $5.ListOperationMetricsRequest);
      case 'GetShopQrcode': return this.getShopQrcode(ctx, request as $4.GetShopQrcodeRequest);
      case 'UpdateShopManager': return this.updateShopManager(ctx, request as $4.UpdateShopManagerRequest);
      case 'GetShopBusinessData': return this.getShopBusinessData(ctx, request as $4.GetShopBusinessDataRequest);
      case 'AddShopAccess': return this.addShopAccess(ctx, request as $4.AddShopAccessRequest);
      case 'RemoveShopAccess': return this.removeShopAccess(ctx, request as $4.RemoveShopAccessRequest);
      case 'VerifyField': return this.verifyField(ctx, request as $4.VerifyFieldRequest);
      case 'ListShopAccess': return this.listShopAccess(ctx, request as $4.ListShopAccessRequest);
      case 'AddShopCategory': return this.addShopCategory(ctx, request as $4.AddShopCategoryRequest);
      case 'GetShopCategory': return this.getShopCategory(ctx, request as $4.GetShopCategoryRequest);
      case 'RemoveShopCategory': return this.removeShopCategory(ctx, request as $4.RemoveShopCategoryRequest);
      case 'AddFreightTemplate': return this.addFreightTemplate(ctx, request as $6.CreateTemplateRequest);
      case 'GetFreightTemplate': return this.getFreightTemplate(ctx, request as $6.GetTemplateRequest);
      case 'UpdateFreightTemplate': return this.updateFreightTemplate(ctx, request as $6.UpdateTemplateRequest);
      case 'DeleteFreightTemplate': return this.deleteFreightTemplate(ctx, request as $6.DeleteTemplateRequest);
      case 'ListFreightTemplate': return this.listFreightTemplate(ctx, request as $6.ListTemplateRequest);
      case 'ListQualification': return this.listQualification(ctx, request as $4.ListShopQualificationRequest);
      case 'GetMallIndex': return this.getMallIndex(ctx, request as $7.MallIndexRequest);
      case 'CreateCategory': return this.createCategory(ctx, request as $8.CreateCategoryRequest);
      case 'GetCategory': return this.getCategory(ctx, request as $8.GetCategoryRequest);
      case 'UpdateCategory': return this.updateCategory(ctx, request as $8.UpdateCategoryRequest);
      case 'ListCategory': return this.listCategory(ctx, request as $8.ListCategoryRequest);
      case 'DeleteCategory': return this.deleteCategory(ctx, request as $8.DeleteCategoryRequest);
      case 'ListCategoryQualification': return this.listCategoryQualification(ctx, request as $9.ListCategoryQualificationRequest);
      case 'CreateProduct': return this.createProduct(ctx, request as $10.CreateProductRequest);
      case 'GetProduct': return this.getProduct(ctx, request as $10.GetProductRequest);
      case 'UpdateProduct': return this.updateProduct(ctx, request as $10.UpdateProductRequest);
      case 'ListProduct': return this.listProduct(ctx, request as $10.ListProductRequest);
      case 'ListProductByIDs': return this.listProductByIDs(ctx, request as $10.ListProductByProductIDsRequest);
      case 'DeleteProduct': return this.deleteProduct(ctx, request as $10.DeleteProductRequest);
      case 'UploadMultiImage': return this.uploadMultiImage(ctx, request as $10.UploadMultiImageRequest);
      case 'DeleteImageById': return this.deleteImageById(ctx, request as $10.DeleteImageRequest);
      case 'BindAttribute': return this.bindAttribute(ctx, request as $10.BindAttributeRequest);
      case 'PublishProduct': return this.publishProduct(ctx, request as $10.PublishProductRequest);
      case 'OffShelfProductInBatches': return this.offShelfProductInBatches(ctx, request as $10.OffSelfProductsRequest);
      case 'DeleteProductInBatches': return this.deleteProductInBatches(ctx, request as $10.DeleteProductsRequest);
      case 'ChangeProductsState': return this.changeProductsState(ctx, request as $10.ChangeProductStateRequest);
      case 'SaveProductImageInfo': return this.saveProductImageInfo(ctx, request as $10.SaveImageInfoRequest);
      case 'CreateSku': return this.createSku(ctx, request as $11.CreateSkuRequest);
      case 'GetSku': return this.getSku(ctx, request as $11.GetSkuRequest);
      case 'UpdateSku': return this.updateSku(ctx, request as $11.UpdateSkuRequest);
      case 'ListSku': return this.listSku(ctx, request as $11.ListSkuRequest);
      case 'DeleteSku': return this.deleteSku(ctx, request as $11.DeleteSkuRequest);
      case 'CreateAttribute': return this.createAttribute(ctx, request as $12.CreateAttributeRequest);
      case 'GetAttribute': return this.getAttribute(ctx, request as $12.GetAttributeRequest);
      case 'ListAttribute': return this.listAttribute(ctx, request as $12.ListAttributeRequest);
      case 'DeleteAttribute': return this.deleteAttribute(ctx, request as $12.DeleteAttributeRequest);
      case 'AddAttributeValue': return this.addAttributeValue(ctx, request as $12.AddAttributeValueRequest);
      case 'DeleteAttributeValue': return this.deleteAttributeValue(ctx, request as $12.DeleteAttributeValueRequest);
      case 'CreateOrder': return this.createOrder(ctx, request as $13.CreateOrderRequest);
      case 'GetOrder': return this.getOrder(ctx, request as $13.GetOrderRequest);
      case 'UpdateOrder': return this.updateOrder(ctx, request as $13.UpdateOrderRequest);
      case 'ListOrder': return this.listOrder(ctx, request as $13.ListOrderRequest);
      case 'DeleteOrder': return this.deleteOrder(ctx, request as $13.DeleteOrderRequest);
      case 'ShipGoods': return this.shipGoods(ctx, request as $13.ShipGoodsRequest);
      case 'ConfirmReceiptGoods': return this.confirmReceiptGoods(ctx, request as $13.ConfirmReceiptGoodsRequest);
      case 'CancelOrder': return this.cancelOrder(ctx, request as $13.CancelOrderRequest);
      case 'ShipGoodsInBatches': return this.shipGoodsInBatches(ctx, request as $13.ShipGoodsInBatchesRequest);
      case 'FreeShippingInBatches': return this.freeShippingInBatches(ctx, request as $13.FreeShippingInBatchesRequest);
      case 'ListShopSummary': return this.listShopSummary(ctx, request as $4.ListShopSummaryRequest);
      case 'ListShopBySellerID': return this.listShopBySellerID(ctx, request as $4.ListShopBySellerIDRequest);
      case 'CreateCart': return this.createCart(ctx, request as $14.AddCartRequest);
      case 'GetCart': return this.getCart(ctx, request as $14.GetCartRequest);
      case 'UpdateCart': return this.updateCart(ctx, request as $14.UpdateCartRequest);
      case 'DeleteCart': return this.deleteCart(ctx, request as $14.DeleteCartRequest);
      case 'UploadAttachment': return this.uploadAttachment(ctx, request as $15.UploadAttachmentRequest);
      case 'SaveAttachment': return this.saveAttachment(ctx, request as $15.SaveAttachmentRequest);
      case 'ListAttachment': return this.listAttachment(ctx, request as $15.ListAttachmentRequest);
      case 'DeleteAttachment': return this.deleteAttachment(ctx, request as $15.DeleteAttachmentRequest);
      case 'CreateSeller': return this.createSeller(ctx, request as $16.CreateSellerRequest);
      case 'CreatePayment': return this.createPayment(ctx, request as $17.CreatePaymentRequest);
      case 'GetPayment': return this.getPayment(ctx, request as $17.GetPaymentRequest);
      case 'UpdatePayment': return this.updatePayment(ctx, request as $17.UpdatePaymentRequest);
      case 'DeletePayment': return this.deletePayment(ctx, request as $17.DeletePaymentRequest);
      case 'CreateConfig': return this.createConfig(ctx, request as $18.CreateConfigRequest);
      case 'UpdateConfig': return this.updateConfig(ctx, request as $18.UpdateConfigRequest);
      case 'DeleteConfig': return this.deleteConfig(ctx, request as $18.DeleteConfigRequest);
      case 'GetConfig': return this.getConfig(ctx, request as $18.GetConfigRequest);
      case 'GetSTS': return this.getSTS(ctx, request as $18.GetSTSRequest);
      case 'ListTenantOrg': return this.listTenantOrg(ctx, request as $19.ListTenantOrgRequest);
      case 'GetAdminTenant': return this.getAdminTenant(ctx, request as $20.GetAdminTenantRequest);
      case 'ListAdminUser': return this.listAdminUser(ctx, request as $20.ListAdminUserRequest);
      case 'CreateAdminUser': return this.createAdminUser(ctx, request as $20.CreateAdminUserRequest);
      case 'UpdateAdminUser': return this.updateAdminUser(ctx, request as $20.UpdateAdminUserRequest);
      case 'DeleteAdminUser': return this.deleteAdminUser(ctx, request as $20.DeleteAdminUserRequest);
      case 'WxPrepay': return this.wxPrepay(ctx, request as $21.PrepayRequest);
      case 'CloseOrder': return this.closeOrder(ctx, request as $21.CloseOrderRequest);
      case 'QueryOrderById': return this.queryOrderById(ctx, request as $21.QueryOrderByIdRequest);
      case 'QueryOrderByOutTrade': return this.queryOrderByOutTrade(ctx, request as $21.QueryOrderByOutTradeNoRequest);
      case 'AddVCurrency': return this.addVCurrency(ctx, request as $22.AddVirtualCurrencyRequest);
      case 'RechargeCurrency': return this.rechargeCurrency(ctx, request as $22.RechargeCurrencyRequest);
      case 'RechargeCurrencyInBatches': return this.rechargeCurrencyInBatches(ctx, request as $22.RechargeCurrencyInBatchesRequest);
      case 'GetVCurrency': return this.getVCurrency(ctx, request as $22.GetVirtualCurrencyRequest);
      case 'ListVCurrency': return this.listVCurrency(ctx, request as $22.ListVirtualCurrencyRequest);
      case 'ListAccountOperation': return this.listAccountOperation(ctx, request as $23.ListAccountOperationRequest);
      case 'CreateRoom': return this.createRoom(ctx, request as $24.CreateRoomRequest);
      case 'GetRoom': return this.getRoom(ctx, request as $24.GetRoomRequest);
      case 'UpdateRoom': return this.updateRoom(ctx, request as $24.UpdateRoomRequest);
      case 'ListRoom': return this.listRoom(ctx, request as $24.ListRoomRequest);
      case 'DeleteRoom': return this.deleteRoom(ctx, request as $24.DeleteRoomRequest);
      case 'ListFinishedRoom': return this.listFinishedRoom(ctx, request as $24.ListFinishedRoomRequest);
      case 'GetFinishedRoom': return this.getFinishedRoom(ctx, request as $24.GetFinishedRoomRequest);
      case 'Record': return this.record(ctx, request as $25.LiveRecordRequest);
      case 'CreateLiveUserToken': return this.createLiveUserToken(ctx, request as $26.CreateLiveUserTokenRequest);
      case 'UserEnterRoom': return this.userEnterRoom(ctx, request as $27.UserEnterRoomRequest);
      case 'UserExitRoom': return this.userExitRoom(ctx, request as $27.UserExitRoomRequest);
      case 'ListActiveRoomUser': return this.listActiveRoomUser(ctx, request as $27.ListActiveRoomUserRequest);
      case 'LiveSSE': return this.liveSSE(ctx, request as $24.LiveSSERequest);
      case 'CloseShopAllLive': return this.closeShopAllLive(ctx, request as $24.CloseShopAllLiveRequest);
      case 'UpdateLiveCommentCount': return this.updateLiveCommentCount(ctx, request as $24.UpdateLiveCommentCountRequest);
      case 'CreateLivePlan': return this.createLivePlan(ctx, request as $25.CreateLivePlanRequest);
      case 'GetLivePlan': return this.getLivePlan(ctx, request as $25.GetLivePlanRequest);
      case 'UpdateLivePlan': return this.updateLivePlan(ctx, request as $25.UpdateLivePlanRequest);
      case 'ListLivePlan': return this.listLivePlan(ctx, request as $25.ListLivePlanRequest);
      case 'DeleteLivePlan': return this.deleteLivePlan(ctx, request as $25.DeleteLivePlanRequest);
      case 'CreateLivePlanProduct': return this.createLivePlanProduct(ctx, request as $25.CreateLivePlanProductRequest);
      case 'UpdateLivePlanProduct': return this.updateLivePlanProduct(ctx, request as $25.UpdateLivePlanProductRequest);
      case 'ListLivePlanProduct': return this.listLivePlanProduct(ctx, request as $25.ListLivePlanProductRequest);
      case 'DeleteLivePlanProduct': return this.deleteLivePlanProduct(ctx, request as $25.DeleteLivePlanProductRequest);
      case 'LoadLivePlanProduct': return this.loadLivePlanProduct(ctx, request as $25.LoadLivePlanProductRequest);
      case 'UpdateLiveProductStatus': return this.updateLiveProductStatus(ctx, request as $25.UpdateLiveProductStatusRequest);
      case 'ListLiveProductStatus': return this.listLiveProductStatus(ctx, request as $25.ListLiveProductStatusRequest);
      case 'DeleteLiveProductStatus': return this.deleteLiveProductStatus(ctx, request as $25.DeleteLiveProductStatusRequest);
      case 'CreateLiveProductStatus': return this.createLiveProductStatus(ctx, request as $25.CreateLiveProductStatusRequest);
      case 'GetLivingProductStatus': return this.getLivingProductStatus(ctx, request as $25.GetLivingProductStatusRequest);
      case 'UpdateLiveProductIntroductStatus': return this.updateLiveProductIntroductStatus(ctx, request as $25.UpdateLiveProductIntroductStatusRequest);
      case 'CreateLiveText': return this.createLiveText(ctx, request as $28.CreateLiveTextRequest);
      case 'UpdateLiveText': return this.updateLiveText(ctx, request as $28.UpdateLiveTextRequest);
      case 'ListLiveText': return this.listLiveText(ctx, request as $28.ListLiveTextRequest);
      case 'GetLiveText': return this.getLiveText(ctx, request as $28.GetLiveTextRequest);
      case 'DeleteLiveTexts': return this.deleteLiveTexts(ctx, request as $28.DeleteLiveTextsRequest);
      case 'GetLiveChartData': return this.getLiveChartData(ctx, request as $24.GetLiveChartDataRequest);
      case 'GetEvaluateSelector': return this.getEvaluateSelector(ctx, request as $29.GetEvaluateSelectorRequest);
      case 'ListPersonalEvaluate': return this.listPersonalEvaluate(ctx, request as $29.ListPersonalEvaluateRequest);
      case 'GetEvaluateDetail': return this.getEvaluateDetail(ctx, request as $29.GetEvaluateDetailRequest);
      case 'SubmitEvaluate': return this.submitEvaluate(ctx, request as $29.SubmitEvaluateRequest);
      case 'ListUnevaluatedRoom': return this.listUnevaluatedRoom(ctx, request as $29.ListUnevaluatedRoomRequest);
      case 'ListStudentEvaluations': return this.listStudentEvaluations(ctx, request as $29.ListStudentEvalutionsRequest);
      case 'IgnoreEvaluation': return this.ignoreEvaluation(ctx, request as $29.IgnoreLiveEvaluationRequest);
      case 'GetRank': return this.getRank(ctx, request as $29.GetRankRequest);
      case 'RecordLiveCallback': return this.recordLiveCallback(ctx, request as $24.RecordLiveCallbackRequest);
      case 'VideoToTextCallback': return this.videoToTextCallback(ctx, request as $24.VideoToTextCallbackRequest);
      case 'LiveStreamCallback': return this.liveStreamCallback(ctx, request as $24.LiveStreamCallbackRequest);
      case 'RegenerationAiFeedback': return this.regenerationAiFeedback(ctx, request as $29.RegenerationAiFeedbackRequest);
      case 'SubmitUserAttitudeForAiResult': return this.submitUserAttitudeForAiResult(ctx, request as $29.SubmitUserAttitudeForAIResultRequest);
      case 'PreheatProduct': return this.preheatProduct(ctx, request as $25.PreheatRequest);
      case 'PublicPrice': return this.publicPrice(ctx, request as $25.PublicPriceRequest);
      case 'CreateTenant': return this.createTenant(ctx, request as $30.CreateTenantRequest);
      case 'GetTenant': return this.getTenant(ctx, request as $30.GetTenantRequest);
      case 'UpdateTenant': return this.updateTenant(ctx, request as $30.UpdateTenantRequest);
      case 'DeleteTenant': return this.deleteTenant(ctx, request as $30.DeleteTenantRequest);
      case 'ListTenant': return this.listTenant(ctx, request as $30.ListTenantRequest);
      case 'GetTenantOrg': return this.getTenantOrg(ctx, request as $30.GetTenantOrgRequest);
      case 'EnterTenant': return this.enterTenant(ctx, request as $30.EnterTenantRequest);
      case 'ExitTenant': return this.exitTenant(ctx, request as $30.ExitTenantRequest);
      case 'InitTenant': return this.initTenant(ctx, request as $30.InitTenantRequest);
      case 'CreateTenantDept': return this.createTenantDept(ctx, request as $31.CreateTenantDeptRequest);
      case 'UpdateTenantDept': return this.updateTenantDept(ctx, request as $31.UpdateTenantDeptRequest);
      case 'DeleteTenantDept': return this.deleteTenantDept(ctx, request as $31.DeleteTenantDeptRequest);
      case 'GetTenantDept': return this.getTenantDept(ctx, request as $31.GetTenantDeptRequest);
      case 'GetTenantDeptType': return this.getTenantDeptType(ctx, request as $31.GetTenantDeptTypeRequest);
      case 'ListTenantDept': return this.listTenantDept(ctx, request as $31.ListTenantDeptRequest);
      case 'CreateTenantUser': return this.createTenantUser(ctx, request as $32.CreateTenantUserRequest);
      case 'DeleteTenantUser': return this.deleteTenantUser(ctx, request as $32.DeleteTenantUserRequest);
      case 'UpdateTenantUser': return this.updateTenantUser(ctx, request as $32.UpdateTenantUserRequest);
      case 'GetTenantUser': return this.getTenantUser(ctx, request as $32.GetTenantUserRequest);
      case 'ListTenantUser': return this.listTenantUser(ctx, request as $32.ListTenantUserRequest);
      case 'ListTenantStudent': return this.listTenantStudent(ctx, request as $32.ListTenantStudentRequest);
      case 'UpdateTenantUserPassword': return this.updateTenantUserPassword(ctx, request as $32.UpdateTenantUserPasswordRequest);
      case 'UpdateTenantConfig': return this.updateTenantConfig(ctx, request as $33.UpdateTenantConfigRequest);
      case 'ListTenantConfig': return this.listTenantConfig(ctx, request as $33.ListTenantConfigRequest);
      case 'CreateShortVideo': return this.createShortVideo(ctx, request as $34.CreateShortVideoRequest);
      case 'StageShortVideo': return this.stageShortVideo(ctx, request as $34.StageShortVideoRequest);
      case 'ListMyShortVideo': return this.listMyShortVideo(ctx, request as $34.ListMyShortVideoRequest);
      case 'ListMyStageVideo': return this.listMyStageVideo(ctx, request as $34.ListMyStageVideoRequest);
      case 'ListMyLikeVideo': return this.listMyLikeVideo(ctx, request as $34.ListMyLikeVideoRequest);
      case 'ListMyFavoriteVideo': return this.listMyFavoriteVideo(ctx, request as $34.ListMyFavoriteVideoRequest);
      case 'GetShortVideo': return this.getShortVideo(ctx, request as $34.GetShortVideoRequest);
      case 'UpdateShortVideo': return this.updateShortVideo(ctx, request as $34.UpdateShortVideoRequest);
      case 'DeleteShortVideo': return this.deleteShortVideo(ctx, request as $34.DeleteShortVideoRequest);
      case 'GetStageVideo': return this.getStageVideo(ctx, request as $34.GetStageVideoRequest);
      case 'DeleteStageVideo': return this.deleteStageVideo(ctx, request as $34.DeleteStageVideoRequest);
      case 'UpdateStageVideo': return this.updateStageVideo(ctx, request as $34.UpdateStageVideoRequest);
      case 'ManagementListShortVideo': return this.managementListShortVideo(ctx, request as $34.ManagementListShortVideoRequest);
      case 'ManagementCensorShortVideo': return this.managementCensorShortVideo(ctx, request as $34.ManagementCensorShortVideoRequest);
      case 'ManagementDeleteShortVideo': return this.managementDeleteShortVideo(ctx, request as $34.ManagementDeleteShortVideoRequest);
      case 'ListShortVideo': return this.listShortVideo(ctx, request as $34.ListShortVideoRequest);
      case 'LikeShortVideo': return this.likeShortVideo(ctx, request as $34.LikeShortVideoRequest);
      case 'FavoriteShortVideo': return this.favoriteShortVideo(ctx, request as $34.FavoriteShortVideoRequest);
      case 'CreateShortVideoComment': return this.createShortVideoComment(ctx, request as $34.CreateShortVideoCommentRequest);
      case 'DeleteShortVideoComment': return this.deleteShortVideoComment(ctx, request as $34.DeleteShortVideoCommentRequest);
      case 'ListShortVideoComment': return this.listShortVideoComment(ctx, request as $34.ListShortVideoCommentRequest);
      case 'CreateCoupon': return this.createCoupon(ctx, request as $35.CreateCouponRequest);
      case 'ListCoupon': return this.listCoupon(ctx, request as $35.ListCouponRequest);
      case 'CouponDetail': return this.couponDetail(ctx, request as $35.GetCouponDetailRequest);
      case 'UpdateCoupon': return this.updateCoupon(ctx, request as $35.UpdateCouponRequest);
      case 'DeleteCoupon': return this.deleteCoupon(ctx, request as $35.DeleteCouponRequest);
      case 'AbolishCoupon': return this.abolishCoupon(ctx, request as $35.AbolishCouponRequest);
      case 'UpdateCouponDistributionStatus': return this.updateCouponDistributionStatus(ctx, request as $35.UpdateCouponDistributionStatusRequest);
      case 'ClaimCoupon': return this.claimCoupon(ctx, request as $35.ClaimCouponRequest);
      case 'ListMyCoupon': return this.listMyCoupon(ctx, request as $35.ListMyCouponRequest);
      case 'CreateActivity': return this.createActivity(ctx, request as $36.CreateActivityRequest);
      case 'ListActivity': return this.listActivity(ctx, request as $36.ListActivityRequest);
      case 'ActivityDetail': return this.activityDetail(ctx, request as $36.GetActivityDetailRequest);
      case 'UpdateActivity': return this.updateActivity(ctx, request as $36.UpdateActivityRequest);
      case 'DeleteActivity': return this.deleteActivity(ctx, request as $36.DeleteActivityRequest);
      case 'DisableActivity': return this.disableActivity(ctx, request as $36.DisableActivityRequest);
      case 'CreateCourseMaterialBox': return this.createCourseMaterialBox(ctx, request as $37.CreateCourseMaterialBoxRequest);
      case 'UpdateCourseMaterialBox': return this.updateCourseMaterialBox(ctx, request as $37.UpdateCourseMaterialBoxRequest);
      case 'ListCourseMaterialBox': return this.listCourseMaterialBox(ctx, request as $37.ListCourseMaterialBoxRequest);
      case 'DeleteCourseMaterialBox': return this.deleteCourseMaterialBox(ctx, request as $37.DeleteCourseMaterialBoxRequest);
      case 'UploadCourseMaterial': return this.uploadCourseMaterial(ctx, request as $37.UploadCourseMaterialRequest);
      case 'ListCourseMaterial': return this.listCourseMaterial(ctx, request as $37.ListCourseMaterialRequest);
      case 'DeleteCourseMaterial': return this.deleteCourseMaterial(ctx, request as $37.DeleteCourseMaterialRequest);
      case 'GetCourseModuleCode': return this.getCourseModuleCode(ctx, request as $38.GetCourseModuleCodeRequest);
      case 'GetCourseChapterCode': return this.getCourseChapterCode(ctx, request as $38.GetCourseChapterCodeRequest);
      case 'CreateCourseModule': return this.createCourseModule(ctx, request as $38.CreateCourseModuleRequest);
      case 'GetCourseModule': return this.getCourseModule(ctx, request as $38.GetCourseModuleRequest);
      case 'UpdateCourseModule': return this.updateCourseModule(ctx, request as $38.UpdateCourseModuleRequest);
      case 'DeleteCourseModule': return this.deleteCourseModule(ctx, request as $38.DeleteCourseModuleRequest);
      case 'ListCourseModule': return this.listCourseModule(ctx, request as $38.ListCourseModuleRequest);
      case 'ListLatestCourse': return this.listLatestCourse(ctx, request as $39.ListLatestCourseRequest);
      case 'ListHotestCourse': return this.listHotestCourse(ctx, request as $39.ListHotestCourseRequest);
      case 'CreateCmCourse': return this.createCmCourse(ctx, request as $40.CreateCmCourseRequest);
      case 'PreviewCmCourse': return this.previewCmCourse(ctx, request as $40.PreviewCmCourseRequest);
      case 'CreateNmCourseResource': return this.createNmCourseResource(ctx, request as $41.CreateNmCourseChapterResourceRequest);
      case 'CreateNmCourseChapter': return this.createNmCourseChapter(ctx, request as $41.CreateNmCourseChapterRequest);
      case 'CreateNmCourse': return this.createNmCourse(ctx, request as $41.CreateNmCourseRequest);
      case 'ListNmCourse': return this.listNmCourse(ctx, request as $41.ListNmCourseRequest);
      case 'NmCourseDetail': return this.nmCourseDetail(ctx, request as $41.NmCourseDetailRequest);
      case 'DeleteNmCourse': return this.deleteNmCourse(ctx, request as $41.DeleteNmCourseRequest);
      case 'CreateCourse': return this.createCourse(ctx, request as $39.CreateCourseRequest);
      case 'GetCourse': return this.getCourse(ctx, request as $39.GetCourseRequest);
      case 'UpdateCourse': return this.updateCourse(ctx, request as $39.UpdateCourseRequest);
      case 'DeleteCourse': return this.deleteCourse(ctx, request as $39.DeleteCourseRequest);
      case 'ListCourse': return this.listCourse(ctx, request as $39.ListCourseRequest);
      case 'CreateKnowledgeGraph': return this.createKnowledgeGraph(ctx, request as $42.CreateKnowledgeGraphRequest);
      case 'GetKnowledgeGraph': return this.getKnowledgeGraph(ctx, request as $42.GetKnowledgeGraphRequest);
      case 'GetKnowledgeGraphNode': return this.getKnowledgeGraphNode(ctx, request as $42.GetKnowledgeGraphNodeRequest);
      case 'GetMajorCode': return this.getMajorCode(ctx, request as $39.GetMajorCodeRequest);
      case 'GetCourseIds': return this.getCourseIds(ctx, request as $39.GetCourseIdsRequest);
      case 'EnrollCourse': return this.enrollCourse(ctx, request as $43.EnrollCourseRequest);
      case 'DeleteMyCourse': return this.deleteMyCourse(ctx, request as $43.DeleteMyCourseRequest);
      case 'UpdateCourseProgress': return this.updateCourseProgress(ctx, request as $43.UpdateCourseProgressRequest);
      case 'ListMyCourse': return this.listMyCourse(ctx, request as $43.ListMyCourseRequest);
      case 'ListTeachingPlan': return this.listTeachingPlan(ctx, request as $44.ListTeachingPlanRequest);
      case 'CreateTeachingPlan': return this.createTeachingPlan(ctx, request as $44.CreateTeachingPlanRequest);
      case 'UpdateTeachingPlan': return this.updateTeachingPlan(ctx, request as $44.UpdateTeachingPlanRequest);
      case 'DeleteTeachingPlan': return this.deleteTeachingPlan(ctx, request as $44.DeleteTeachingPlanRequest);
      case 'UpdateTeachingCourseProgress': return this.updateTeachingCourseProgress(ctx, request as $44.UpdateTeachingCourseProgressRequest);
      case 'CreateEduScheme': return this.createEduScheme(ctx, request as $45.CreateEduSchemeRequest);
      case 'UpdateEduScheme': return this.updateEduScheme(ctx, request as $45.UpdateEduSchemeRequest);
      case 'ListEduScheme': return this.listEduScheme(ctx, request as $45.ListEduSchemeRequest);
      case 'EduSchemeDetail': return this.eduSchemeDetail(ctx, request as $45.EduSchemeDetailRequest);
      case 'DeleteEduScheme': return this.deleteEduScheme(ctx, request as $45.DeleteEduSchemeRequest);
      case 'DistributeEduScheme': return this.distributeEduScheme(ctx, request as $45.DistributeEduSchemeRequest);
      case 'GetEduSchemeLikeCourse': return this.getEduSchemeLikeCourse(ctx, request as $45.GetEduSchemeLikeCourseRequest);
      case 'GetAndroidQRcode': return this.getAndroidQRcode(ctx, request as $46.GetAndroidQRCodeRequest);
      case 'CreateJob': return this.createJob(ctx, request as $47.CreateJobRequest);
      case 'UpdateJob': return this.updateJob(ctx, request as $47.UpdateJobRequest);
      case 'DeleteJob': return this.deleteJob(ctx, request as $47.DeleteJobRequest);
      case 'ListJob': return this.listJob(ctx, request as $47.ListJobRequest);
      case 'GetSchooLiveChart': return this.getSchooLiveChart(ctx, request as $48.GetSchoolLiveTrafficChartRequest);
      case 'ListSchooLiveTraffic': return this.listSchooLiveTraffic(ctx, request as $48.ListSchoolLiveTrafficRequest);
      case 'GetLiveAllTraffic': return this.getLiveAllTraffic(ctx, request as $48.GetAllLiveTrafficRequest);
      case 'ListTenantTrafficConfig': return this.listTenantTrafficConfig(ctx, request as $48.ListTenantLiveTrafficConfigRequest);
      case 'UpdateTenantTrafficConfig': return this.updateTenantTrafficConfig(ctx, request as $48.UpdateTenantLiveTrafficConfigRequest);
      default: throw $core.ArgumentError('Unknown method: $methodName');
    }
  }

  $core.Map<$core.String, $core.dynamic> get $json => glory_apiServiceBase$json;
  $core.Map<$core.String, $core.Map<$core.String, $core.dynamic>> get $messageJson => glory_apiServiceBase$messageJson;
}

