# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  JENKINS_USER_TOKEN: ${{ secrets.JENKINS_USER_TOKEN }}
  JENKINS_DEPLOYMENT_TOKEN: ${{ secrets.JENKINS_DEPLOYMENT_TOKEN }}

jobs:

  changes:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: test
        run: cat $HOME/files_*.json |grep "idl/" && curl -XPOST "http://47.104.198.79:8080/job/idl_web_client_code_gen/build?token=${{ secrets.JENKINS_DEPLOYMENT_TOKEN }}" --user fan:${{ secrets.JENKINS_USER_TOKEN }}




