name: 'nightly artifacts cleanup'
on:
  schedule:
    - cron: '0 22 * * *' # every night at 1 am UTC

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.CI_GITHUB_USER_TOKE }}
          expire-in: 0