# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main", "fan/ios" ]
  pull_request:
    branches: [ "main", "fan/ios" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: protoc --swift_out=. idl/idl/api.proto && ls

#      - name: Run tests
#        run: swift test -v
