# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main", "fan/ios" ]
  pull_request:
    branches: [ "main", "fan/ios" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          brew install protobuf
          brew install swift-protobuf
          mkdir swift_client ||true
          for f in $(find ./idl -name *.proto)
          do
            protoc -I idl --swift_out=./swift_client $f -I idl/
          done
  

#      - name: Run tests
#        run: swift test -v
