# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main", "fan/ios" ]
  pull_request:
    branches: [ "main", "fan/ios" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: install the package
        run: |
          brew install protobuf
          brew install swift-protobuf
          ls -l

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: generate the code
        run: |    
          mkdir -p swift_client ||true
          ls -l
          for f in $(find ./idl -name *.proto)
          do
            protoc -I idl --swift_out=./swift_client $f -I idl/
          done
          ls -l swift_client

      - name: Commit files
        run: |
          set -e
          git config --local user.email "fan20230101-ci@gmail.com"
          git config --local user.name "fan20230101-ci"
          git add .
          git commit -a -m "generate the code"
          

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.CI_GITHUB_USER_TOKE }}
          force: true

      - name: trigger the web client generation based on the changed files
        run: |
          set +e
          idlChange="no"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo $file |grep "idl/"
            if [ $? -eq 0 ];then
              idlChange="yes"
            fi
            echo "$file was changed"
          done
          if [ $idlChange == "yes" ];then
            curl -XPOST "http://47.104.198.79:8080/job/idl_web_client_code_gen/build?token=${{ secrets.JENKINS_DEPLOYMENT_TOKEN }}" --user fan:${{ secrets.JENKINS_USER_TOKEN }}
          fi  
          
          
          
          
  

#      - name: Run tests
#        run: swift test -v
