# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]


env:
  JENKINS_USER_TOKEN: ${{ secrets.JENKINS_USER_TOKEN }}
  JENKINS_DEPLOYMENT_TOKEN: ${{ secrets.JENKINS_DEPLOYMENT_TOKEN }}


jobs:
  build:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: install the package
        run: |
          brew install protobuf
          brew install swift-protobuf
          ls -l

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: generate the code
        run: |    
          mkdir -p swift_client ||true
          ls -l
          for f in $(find ./idl -name *.proto)
          do
            protoc -I idl --swift_out=./swift_client $f -I idl/
          done
          tar -czvf swift_client.tar.gz swift_client

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
            path: ./swift_client.tar.gz

      - name: trigger the web client generation based on the changed files
        run: |
          set +e
          idlChange="no"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo $file |grep "idl/"
            if [ $? -eq 0 ];then
              idlChange="yes"
            fi
            echo "$file was changed"
          done
          if [ $idlChange == "yes" ];then
            curl -XPOST "http://47.104.198.79:8080/job/idl_web_client_code_gen/buildWithParameters?token=${{ secrets.JENKINS_DEPLOYMENT_TOKEN }}&runID=${{ github.run_id }}" --user fan:${{ secrets.JENKINS_USER_TOKEN }}
          fi  
          
          
          
    
