# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main", "fan/ios" ]
  pull_request:
    branches: [ "main", "fan/ios" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: install the package
        run: |
          brew install protobuf
          brew install swift-protobuf
          ls -l
          

      - name: generate the code
        run: |    
          mkdir -p swift_client ||true
          ls -l
          for f in $(find ./idl -name *.proto)
          do
            protoc -I idl --swift_out=./swift_client $f -I idl/
          done
          ls -l swift_client

      - name: Commit files
        run: |
          set -e
          git config --local user.email "fan20230101-ci@gmail.com"
          git config --local user.name "fan20230101-ci"
          git commit -a -m "generate the code"
          

      - name: Push changes
        uses: ad-m/github-push-action@main
        with:
          token: ${{ secrets.CI_GITHUB_USER_TOKE }}
          force: true
          
          
          
          
  

#      - name: Run tests
#        run: swift test -v
